// Package ui renders the project's alacris components from Go.
//
// Code in this package is generated by alacris-go from the define() calls in the
// component sources. Edit the components, or the manifest, not this.
//
// A component's shadow content is rendered in the browser; what these functions
// produce is the element, its props and its light-DOM children.
//
// Code generated by alacris-go. DO NOT EDIT.
package ui

// Tags lists every component in this package.
//
// It is what alacris.Pending wants, so that elements do not flash before their
// module has loaded:
//
//	@alacris.Pending{Tags: ui.Tags}
var Tags = []string{
	"ala-board",
	"ala-member-select",
}
