// Code generated by alacris-go from ../web/components.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	todo "github.com/bmartel/alacris-go/examples/todo/model"
)

// ChipTag is the name of the <ala-chip> custom element.
const ChipTag = "ala-chip"

// Slots exposed by <ala-chip>. Put one on your own markup to fill it:
//
//	<h3 slot={ ChipSlotDefault }>
const (
	// the label text
	ChipSlotDefault = ""
)

// ChipVars is the theming contract of <ala-chip>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Chip(props).Apply(ChipVars, map[string]string{"--chip-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var ChipVars = alacris.Vars(
	"--chip-bg", // the background (defaults to #eee)
	"--chip-fg", // the text colour (defaults to #111)
)

// ChipProps are the props of <ala-chip>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type ChipProps struct {
	// The component defaults it to 'neutral'.
	Tone string
}

// Chip renders <ala-chip>.
//
// A small label. Themed entirely through custom properties, so the page can
// restyle it without knowing anything about its shadow root.
func Chip(p ChipProps) *alacris.Element {
	e := alacris.E(ChipTag)
	if p.Tone != "" && p.Tone != "neutral" {
		e.Prop("tone", p.Tone)
	}
	return e
}

// CounterTag is the name of the <ala-counter> custom element.
const CounterTag = "ala-counter"

// Events emitted by <ala-counter>. Forward one to a server action with On:
//
//	Counter(props).On(CounterEventChange, "handler-name")
const (
	// the number changed
	CounterEventChange = "change"
)

// CounterChangeDetail is the detail of the "change" event of <ala-counter>.
//
// the number changed
type CounterChangeDetail struct {
	Value int `json:"value"`
}

// CounterProps are the props of <ala-counter>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type CounterProps struct {
	// Start is the value it opens on.
	//
	// The component defaults it to 0.
	Start int

	// Step is how much each press moves it.
	//
	// The component defaults it to 1.
	Step int
}

// Counter renders <ala-counter>.
//
// A number the user can nudge, kept in the browser.
//
// Nothing here touches the server: local state that no one else needs is
// exactly what a signal is for.
func Counter(p CounterProps) *alacris.Element {
	e := alacris.E(CounterTag)
	if p.Start != 0 {
		e.Prop("start", p.Start)
	}
	if p.Step != 0 && p.Step != 1 {
		e.Prop("step", p.Step)
	}
	return e
}

// TodoListTag is the name of the <ala-todo-list> custom element.
const TodoListTag = "ala-todo-list"

// Slots exposed by <ala-todo-list>. Put one on your own markup to fill it:
//
//	<h3 slot={ TodoListSlotEmpty }>
const (
	// shown instead of the list when there is nothing to show
	TodoListSlotEmpty = "empty"
)

// Events emitted by <ala-todo-list>. Forward one to a server action with On:
//
//	TodoList(props).On(TodoListEventAdd, "handler-name")
const (
	// the user entered a new todo
	TodoListEventAdd = "add"
	// the user flipped one done or undone
	TodoListEventToggle = "toggle"
	// the user deleted one
	TodoListEventRemove = "remove"
	// the user picked a different filter
	TodoListEventFilter = "filter"
)

// TodoListAddDetail is the detail of the "add" event of <ala-todo-list>.
//
// the user entered a new todo
type TodoListAddDetail struct {
	Text string `json:"text"`
}

// TodoListToggleDetail is the detail of the "toggle" event of <ala-todo-list>.
//
// the user flipped one done or undone
type TodoListToggleDetail struct {
	ID int `json:"id"`
}

// TodoListRemoveDetail is the detail of the "remove" event of <ala-todo-list>.
//
// the user deleted one
type TodoListRemoveDetail struct {
	ID int `json:"id"`
}

// TodoListFilterDetail is the detail of the "filter" event of <ala-todo-list>.
//
// the user picked a different filter
type TodoListFilterDetail struct {
	Filter string `json:"filter"`
}

// TodoListProps are the props of <ala-todo-list>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type TodoListProps struct {
	// Items is the list, as rendered by the server.
	//
	// Crosses as JSON in the items attribute.
	Items []todo.Item

	// Filter is "all", "active" or "done".
	//
	// The component defaults it to 'all'.
	Filter string

	// Busy is true while the server is working.
	//
	// The component defaults it to false.
	Busy bool
}

// TodoList renders <ala-todo-list>.
//
// The todo list.
//
// The list itself is a prop, so the server is the only thing that decides what
// is in it. Every interaction leaves as an event and comes back as a new
// value for `items`.
func TodoList(p TodoListProps) *alacris.Element {
	e := alacris.E(TodoListTag)
	if len(p.Items) > 0 {
		e.Prop("items", p.Items)
	}
	if p.Filter != "" && p.Filter != "all" {
		e.Prop("filter", p.Filter)
	}
	if p.Busy {
		e.Prop("busy", p.Busy)
	}
	return e
}
