// Code generated by alacris-go from ../web/components.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	todo "github.com/bmartel/alacris-go/examples/todo/model"
	live "github.com/bmartel/alacris-go/live"
)

// BoardTag is the name of the <ala-board> custom element.
const BoardTag = "ala-board"

// Slots exposed by <ala-board>. Put one on your own markup to fill it:
//
//	<h3 slot={ BoardSlotEmpty }>
const (
	// kept in the light DOM for first paint / no-JS
	BoardSlotEmpty = "empty"
	// overlapping avatars; the server rewrites this slot
	BoardSlotMembers = "members"
)

// Events emitted by <ala-board>. Forward one to a server action with On:
//
//	Board(props).On(BoardEventAdd, "handler-name")
const (
	// the user added a card
	BoardEventAdd = "add"
	// the user dropped a card
	BoardEventMove = "move"
	// the user added a list
	BoardEventAddlist = "addlist"
	// the user dropped a list
	BoardEventMovelist = "movelist"
	// the user renamed a list
	BoardEventRename = "rename"
	// the user deleted a list
	BoardEventDeletelist = "deletelist"
	// the user edited a card
	BoardEventEdit = "edit"
	// the user deleted a card
	BoardEventRemove = "remove"
)

// BoardAddDetail is the detail of the "add" event of <ala-board>.
//
// the user added a card
type BoardAddDetail struct {
	Text   string `json:"text"`
	Column string `json:"column"`
}

// BoardMoveDetail is the detail of the "move" event of <ala-board>.
//
// the user dropped a card
type BoardMoveDetail struct {
	ID     int    `json:"id"`
	Column string `json:"column"`
	Index  int    `json:"index"`
}

// BoardAddlistDetail is the detail of the "addlist" event of <ala-board>.
//
// the user added a list
type BoardAddlistDetail struct {
	Title string `json:"title"`
}

// BoardMovelistDetail is the detail of the "movelist" event of <ala-board>.
//
// the user dropped a list
type BoardMovelistDetail struct {
	ID    string `json:"id"`
	Index int    `json:"index"`
}

// BoardRenameDetail is the detail of the "rename" event of <ala-board>.
//
// the user renamed a list
type BoardRenameDetail struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

// BoardDeletelistDetail is the detail of the "deletelist" event of <ala-board>.
//
// the user deleted a list
type BoardDeletelistDetail struct {
	ID string `json:"id"`
}

// BoardEditDetail is the detail of the "edit" event of <ala-board>.
//
// the user edited a card
type BoardEditDetail struct {
	ID     int      `json:"id"`
	Text   string   `json:"text"`
	Body   string   `json:"body"`
	Who    []string `json:"who"`
	Labels []string `json:"labels"`
}

// BoardRemoveDetail is the detail of the "remove" event of <ala-board>.
//
// the user deleted a card
type BoardRemoveDetail struct {
	ID int `json:"id"`
}

// BoardProps are the props of <ala-board>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type BoardProps struct {
	// Title is the board name.
	//
	// The component defaults it to 'Ship it'.
	Title string

	// Items is the cards, as rendered by the server.
	//
	// Crosses as JSON in the items attribute.
	Items []todo.Item

	// Columns is the lists, left to right.
	//
	// Crosses as JSON in the columns attribute.
	Columns []todo.Column

	// Busy is true while the server is working.
	//
	// The component defaults it to false.
	Busy bool
}

// Board renders <ala-board>.
//
// The shared board.
func Board(p BoardProps) *alacris.Element {
	e := alacris.E(BoardTag)
	if p.Title != "" && p.Title != "Ship it" {
		e.Prop("title", p.Title)
	}
	if len(p.Items) > 0 {
		e.Prop("items", p.Items)
	}
	if len(p.Columns) > 0 {
		e.Prop("columns", p.Columns)
	}
	if p.Busy {
		e.Prop("busy", p.Busy)
	}
	return e
}

// BoardHandle patches a rendered <ala-board> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with BoardElement.
type BoardHandle struct {
	handle live.Handle
}

// BoardElement addresses the <ala-board> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	BoardElement(c.Session, "id").SetTitle(v)
func BoardElement(s *live.Session, id string) BoardHandle {
	return BoardHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h BoardHandle) Handle() live.Handle { return h.handle }

// SetTitle writes the title prop.
func (h BoardHandle) SetTitle(v string) { h.handle.Set("title", v) }

// SetItems writes the items prop.
func (h BoardHandle) SetItems(v []todo.Item) { h.handle.Set("items", v) }

// SetColumns writes the columns prop.
func (h BoardHandle) SetColumns(v []todo.Column) { h.handle.Set("columns", v) }

// SetBusy writes the busy prop.
func (h BoardHandle) SetBusy(v bool) { h.handle.Set("busy", v) }

// MemberSelectTag is the name of the <ala-member-select> custom element.
const MemberSelectTag = "ala-member-select"

// Events emitted by <ala-member-select>. Forward one to a server action with On:
//
//	MemberSelect(props).On(MemberSelectEventChange, "handler-name")
const (
	// the selection changed
	MemberSelectEventChange = "change"
)

// MemberSelectChangeDetail is the detail of the "change" event of <ala-member-select>.
//
// the selection changed
type MemberSelectChangeDetail struct {
	Value []string `json:"value"`
}

// MemberSelectProps are the props of <ala-member-select>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type MemberSelectProps struct {
	// Value is selected names.
	//
	// Crosses as JSON in the value attribute.
	Value []string

	// Options is people that can be assigned.
	//
	// Crosses as JSON in the options attribute.
	Options []string

	// The component defaults it to 'Members'.
	Label string

	// The component defaults it to 'Search people'.
	Placeholder string
}

// MemberSelect renders <ala-member-select>.
//
// Multi-select people picker: dismissible input chips plus <ui-autocomplete>.
//
// Alacris UI's combobox is single-select; this is the MD3 composition for
// assigning several people — chips for who is on the card, a filtering
// autocomplete to add someone else.
func MemberSelect(p MemberSelectProps) *alacris.Element {
	e := alacris.E(MemberSelectTag)
	if len(p.Value) > 0 {
		e.Prop("value", p.Value)
	}
	if len(p.Options) > 0 {
		e.Prop("options", p.Options)
	}
	if p.Label != "" && p.Label != "Members" {
		e.Prop("label", p.Label)
	}
	if p.Placeholder != "" && p.Placeholder != "Search people" {
		e.Prop("placeholder", p.Placeholder)
	}
	return e
}

// MemberSelectHandle patches a rendered <ala-member-select> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with MemberSelectElement.
type MemberSelectHandle struct {
	handle live.Handle
}

// MemberSelectElement addresses the <ala-member-select> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	MemberSelectElement(c.Session, "id").SetValue(v)
func MemberSelectElement(s *live.Session, id string) MemberSelectHandle {
	return MemberSelectHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h MemberSelectHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h MemberSelectHandle) SetValue(v []string) { h.handle.Set("value", v) }

// SetOptions writes the options prop.
func (h MemberSelectHandle) SetOptions(v []string) { h.handle.Set("options", v) }

// SetLabel writes the label prop.
func (h MemberSelectHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetPlaceholder writes the placeholder prop.
func (h MemberSelectHandle) SetPlaceholder(v string) { h.handle.Set("placeholder", v) }
