// Package ui is the typed Go surface of Alacris UI — sixty-nine Material
// Design 3 components, a three-tier token system, and a theme engine.
//
// Enable it on a page with alacris.Config{UI: true}. That loads every component
// and applies Material defaults (seed #e8ad18, Google Sans Flex, scheme from
// the OS). Config.Theme re-skins the whole page; every component follows
// because they consume system tokens.
//
// A component's shadow content is rendered in the browser. What these functions
// produce is the element, its props and its light-DOM children.
//
// Code in this package is generated from the vendored @alacris/ui sources.
// Do not edit it; change the upstream component or regenerate.
//
// Code generated by alacris-go. DO NOT EDIT.
package ui

// Tags lists every component in this package.
//
// It is what alacris.Pending wants, so that elements do not flash before their
// module has loaded:
//
//	@alacris.Pending{Tags: ui.Tags}
var Tags = []string{
	"ui-accordion",
	"ui-accordion-item",
	"ui-alert",
	"ui-app-bar",
	"ui-autocomplete",
	"ui-avatar",
	"ui-backdrop",
	"ui-badge",
	"ui-bottom-app-bar",
	"ui-bottom-nav",
	"ui-breadcrumbs",
	"ui-button",
	"ui-button-group",
	"ui-card",
	"ui-carousel",
	"ui-carousel-item",
	"ui-checkbox",
	"ui-chip",
	"ui-chip-set",
	"ui-container",
	"ui-date-picker",
	"ui-dialog",
	"ui-divider",
	"ui-drawer",
	"ui-fab",
	"ui-fab-menu",
	"ui-icon",
	"ui-icon-button",
	"ui-list",
	"ui-list-item",
	"ui-loading-indicator",
	"ui-menu",
	"ui-menu-item",
	"ui-nav-item",
	"ui-nav-rail",
	"ui-option",
	"ui-pagination",
	"ui-progress",
	"ui-radio",
	"ui-radio-group",
	"ui-rating",
	"ui-search",
	"ui-select",
	"ui-sheet",
	"ui-side-sheet",
	"ui-skeleton",
	"ui-slider",
	"ui-snackbar",
	"ui-spinner",
	"ui-split-button",
	"ui-stack",
	"ui-step",
	"ui-stepper",
	"ui-surface",
	"ui-swipe-row",
	"ui-switch",
	"ui-tab",
	"ui-tab-panel",
	"ui-table",
	"ui-table-footer",
	"ui-table-toolbar",
	"ui-tabs",
	"ui-text",
	"ui-text-field",
	"ui-time-picker",
	"ui-toggle-button",
	"ui-toggle-group",
	"ui-toolbar",
	"ui-tooltip",
}
