// Code generated by alacris-go from ../assets/ui/components/ui-accordion.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// AccordionTag is the name of the <ui-accordion> custom element.
const AccordionTag = "ui-accordion"

// Slots exposed by <ui-accordion>. Put one on your own markup to fill it:
//
//	<h3 slot={ AccordionSlotDefault }>
const (
	// <ui-accordion-item> children
	AccordionSlotDefault = ""
)

// Events emitted by <ui-accordion>. Forward one to a server action with On:
//
//	Accordion(props).On(AccordionEventChange, "handler-name")
const (
	// a panel was toggled by the user; detail: { value }
	AccordionEventChange = "change"
)

// AccordionChangeDetail is the detail of the "change" event of <ui-accordion>.
//
// a panel was toggled by the user; detail: { value }
type AccordionChangeDetail struct {
	Value any `json:"value"`
}

// AccordionVars is the theming contract of <ui-accordion>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Accordion(props).Apply(AccordionVars, map[string]string{"--ui-accordion-divider-color": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var AccordionVars = alacris.Vars(
	"--ui-accordion-divider-color",
)

// AccordionProps are the props of <ui-accordion>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type AccordionProps struct {
	// Multi is allow several panels open at once; when false, expanding one collapses the others.
	//
	// The component defaults it to false.
	Multi bool
}

// Accordion renders <ui-accordion>.
//
// <ui-accordion> — groups <ui-accordion-item> panels.
//
// <ui-accordion>
// <ui-accordion-item value="a" headline="First">…</ui-accordion-item>
// <ui-accordion-item value="b" headline="Second">…</ui-accordion-item>
// </ui-accordion>
//
// Coordination rides the bubbling `ui-accordion-toggle` event from the items,
// so only user interaction triggers single-open collapse; programmatic
// `expanded` writes on an item are left alone.
func Accordion(p AccordionProps) *alacris.Element {
	e := alacris.E(AccordionTag)
	if p.Multi {
		e.Prop("multi", p.Multi)
	}
	return e
}

// AccordionHandle patches a rendered <ui-accordion> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with AccordionElement.
type AccordionHandle struct {
	handle live.Handle
}

// AccordionElement addresses the <ui-accordion> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	AccordionElement(c.Session, "id").SetMulti(v)
func AccordionElement(s *live.Session, id string) AccordionHandle {
	return AccordionHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h AccordionHandle) Handle() live.Handle { return h.handle }

// SetMulti writes the multi prop.
func (h AccordionHandle) SetMulti(v bool) { h.handle.Set("multi", v) }
