// Code generated by alacris-go from ../assets/ui/components/ui-alert.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// AlertTag is the name of the <ui-alert> custom element.
const AlertTag = "ui-alert"

// Slots exposed by <ui-alert>. Put one on your own markup to fill it:
//
//	<h3 slot={ AlertSlotDefault }>
const (
	// message body
	AlertSlotDefault = ""
	// trailing action, e.g. a text <ui-button>
	AlertSlotAction = "action"
)

// Events emitted by <ui-alert>. Forward one to a server action with On:
//
//	Alert(props).On(AlertEventDismiss, "handler-name")
const (
	// close button pressed, after the collapse animation
	AlertEventDismiss = "dismiss"
)

// AlertVars is the theming contract of <ui-alert>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Alert(props).Apply(AlertVars, map[string]string{"--ui-alert-radius": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var AlertVars = alacris.Vars(
	"--ui-alert-radius",
	"--ui-alert-padding",
	"--ui-alert-gap",
	"--ui-alert-font",
	"--ui-alert-title-font",
)

// AlertProps are the props of <ui-alert>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type AlertProps struct {
	// Severity is info | success | warning | error.
	//
	// The component defaults it to 'info'.
	Severity string

	// Variant is tonal | filled | outlined.
	//
	// The component defaults it to 'tonal'.
	Variant string

	// Dismissible is shows a trailing close button.
	//
	// The component defaults it to false.
	Dismissible bool

	// Icon is leading icon override; defaults per severity (info → 'info', success → 'check-circle', warning → 'warning', error → 'error').
	//
	// The component defaults it to ''.
	Icon string

	// Title is optional bold first line.
	//
	// The component defaults it to ''.
	Title string
}

// Alert renders <ui-alert>.
//
// <ui-alert> — a severity-colored callout for statuses and messages.
//
// <ui-alert severity="success" title="Saved" dismissible @dismiss=${remove}>
// Your changes are safe.
// <ui-button slot="action" variant="text">Undo</ui-button>
// </ui-alert>
//
// Live-region semantics: the host defaults to role="status" (announced
// politely). If the alert appears dynamically in response to an event and must
// interrupt, set role="alert" on the element yourself — an author-set role is
// never overwritten.
//
// Dismissing: the close button collapses the alert (height + opacity), then
// emits `dismiss`. The PARENT owns the DOM and removes the element (or flips
// the condition rendering it).
func Alert(p AlertProps) *alacris.Element {
	e := alacris.E(AlertTag)
	if p.Severity != "" && p.Severity != "info" {
		e.Prop("severity", p.Severity)
	}
	if p.Variant != "" && p.Variant != "tonal" {
		e.Prop("variant", p.Variant)
	}
	if p.Dismissible {
		e.Prop("dismissible", p.Dismissible)
	}
	if p.Icon != "" {
		e.Prop("icon", p.Icon)
	}
	if p.Title != "" {
		e.Prop("title", p.Title)
	}
	return e
}

// AlertHandle patches a rendered <ui-alert> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with AlertElement.
type AlertHandle struct {
	handle live.Handle
}

// AlertElement addresses the <ui-alert> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	AlertElement(c.Session, "id").SetSeverity(v)
func AlertElement(s *live.Session, id string) AlertHandle {
	return AlertHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h AlertHandle) Handle() live.Handle { return h.handle }

// SetSeverity writes the severity prop.
func (h AlertHandle) SetSeverity(v string) { h.handle.Set("severity", v) }

// SetVariant writes the variant prop.
func (h AlertHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetDismissible writes the dismissible prop.
func (h AlertHandle) SetDismissible(v bool) { h.handle.Set("dismissible", v) }

// SetIcon writes the icon prop.
func (h AlertHandle) SetIcon(v string) { h.handle.Set("icon", v) }

// SetTitle writes the title prop.
func (h AlertHandle) SetTitle(v string) { h.handle.Set("title", v) }
