// Code generated by alacris-go from ../assets/ui/components/ui-autocomplete.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// AutocompleteTag is the name of the <ui-autocomplete> custom element.
const AutocompleteTag = "ui-autocomplete"

// Events emitted by <ui-autocomplete>. Forward one to a server action with On:
//
//	Autocomplete(props).On(AutocompleteEventInput, "handler-name")
const (
	// every keystroke; detail: { value } (the raw text)
	AutocompleteEventInput = "input"
	// committed; detail: { value }
	AutocompleteEventChange = "change"
)

// AutocompleteInputDetail is the detail of the "input" event of <ui-autocomplete>.
//
// every keystroke; detail: { value } (the raw text)
type AutocompleteInputDetail struct {
	Value any `json:"value"`
}

// AutocompleteChangeDetail is the detail of the "change" event of <ui-autocomplete>.
//
// committed; detail: { value }
type AutocompleteChangeDetail struct {
	Value any `json:"value"`
}

// AutocompleteVars is the theming contract of <ui-autocomplete>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Autocomplete(props).Apply(AutocompleteVars, map[string]string{"--ui-autocomplete-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var AutocompleteVars = alacris.Vars(
	"--ui-autocomplete-bg",
	"--ui-autocomplete-fg",
	"--ui-autocomplete-label-fg",
	"--ui-autocomplete-accent",
	"--ui-autocomplete-outline-color",
	"--ui-autocomplete-radius",
	"--ui-autocomplete-font",
	"--ui-autocomplete-height",
	"--ui-autocomplete-panel-bg",
)

// AutocompleteProps are the props of <ui-autocomplete>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type AutocompleteProps struct {
	// The component defaults it to ''.
	Label string

	// Value is the committed value.
	//
	// The component defaults it to ''.
	Value string

	// Options is strings or { value, label } objects (JSON attribute or property).
	//
	// Crosses as JSON in the options attribute.
	Options []any

	// Variant is filled | outlined.
	//
	// The component defaults it to 'filled'.
	Variant string

	// The component defaults it to false.
	Disabled bool

	// The component defaults it to false.
	Required bool

	// Name is form participation.
	//
	// The component defaults it to ''.
	Name string

	// The component defaults it to ''.
	Placeholder string

	// FreeSolo is allow values not present in options.
	//
	// The component defaults it to false.
	FreeSolo bool
}

// Autocomplete renders <ui-autocomplete>.
//
// <ui-autocomplete> — a combobox with a filtering text input.
//
// <ui-autocomplete label="Fruit" options=${['Apple', 'Banana']}
// Typing filters the options case-insensitively and opens a listbox panel
// while there are matches. ArrowUp/Down move the active option, Enter commits
// the active option (or, with `freeSolo`, the raw text), Escape closes, blur
// commits an exact label match — or the raw text when `freeSolo` — and
// otherwise reverts to the last committed value.
func Autocomplete(p AutocompleteProps) *alacris.Element {
	e := alacris.E(AutocompleteTag)
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if len(p.Options) > 0 {
		e.Prop("options", p.Options)
	}
	if p.Variant != "" && p.Variant != "filled" {
		e.Prop("variant", p.Variant)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Required {
		e.Prop("required", p.Required)
	}
	if p.Name != "" {
		e.Prop("name", p.Name)
	}
	if p.Placeholder != "" {
		e.Prop("placeholder", p.Placeholder)
	}
	if p.FreeSolo {
		e.Prop("freeSolo", p.FreeSolo)
	}
	return e
}

// AutocompleteHandle patches a rendered <ui-autocomplete> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with AutocompleteElement.
type AutocompleteHandle struct {
	handle live.Handle
}

// AutocompleteElement addresses the <ui-autocomplete> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	AutocompleteElement(c.Session, "id").SetLabel(v)
func AutocompleteElement(s *live.Session, id string) AutocompleteHandle {
	return AutocompleteHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h AutocompleteHandle) Handle() live.Handle { return h.handle }

// SetLabel writes the label prop.
func (h AutocompleteHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetValue writes the value prop.
func (h AutocompleteHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetOptions writes the options prop.
func (h AutocompleteHandle) SetOptions(v []any) { h.handle.Set("options", v) }

// SetVariant writes the variant prop.
func (h AutocompleteHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetDisabled writes the disabled prop.
func (h AutocompleteHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetRequired writes the required prop.
func (h AutocompleteHandle) SetRequired(v bool) { h.handle.Set("required", v) }

// SetName writes the name prop.
func (h AutocompleteHandle) SetName(v string) { h.handle.Set("name", v) }

// SetPlaceholder writes the placeholder prop.
func (h AutocompleteHandle) SetPlaceholder(v string) { h.handle.Set("placeholder", v) }

// SetFreeSolo writes the freeSolo prop.
func (h AutocompleteHandle) SetFreeSolo(v bool) { h.handle.Set("freeSolo", v) }
