// Code generated by alacris-go from ../assets/ui/components/ui-app-bar.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// AppBarTag is the name of the <ui-app-bar> custom element.
const AppBarTag = "ui-app-bar"

// Slots exposed by <ui-app-bar>. Put one on your own markup to fill it:
//
//	<h3 slot={ AppBarSlotNavigation }>
const (
	// leading icon button
	AppBarSlotNavigation = "navigation"
	// title text
	AppBarSlotDefault = ""
	// trailing icon buttons
	AppBarSlotActions = "actions"
)

// AppBarVars is the theming contract of <ui-app-bar>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	AppBar(props).Apply(AppBarVars, map[string]string{"--ui-app-bar-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var AppBarVars = alacris.Vars(
	"--ui-app-bar-bg",
	"--ui-app-bar-scrolled-bg",
	"--ui-app-bar-fg",
	"--ui-app-bar-height-small",
	"--ui-app-bar-height-medium",
	"--ui-app-bar-height-large",
	"--ui-app-bar-font",
	"--ui-app-bar-tracking",
)

// AppBarProps are the props of <ui-app-bar>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type AppBarProps struct {
	// Variant is small | center | medium | large.
	//
	// The component defaults it to 'small'.
	Variant string

	// Elevated is force the scrolled container/elevation.
	//
	// The component defaults it to false.
	Elevated bool

	// ScrollElevate is auto-elevate once window is scrolled.
	//
	// The component defaults it to false.
	ScrollElevate bool
}

// AppBar renders <ui-app-bar>.
//
// <ui-app-bar> — the Material top app bar.
//
// <ui-app-bar variant="small" scroll-elevate>
// <ui-icon-button slot="navigation" icon="menu" label="Menu"></ui-icon-button>
// Page title
// <ui-icon-button slot="actions" icon="search" label="Search"></ui-icon-button>
// </ui-app-bar>
//
// The host is position:sticky at the top. `elevated` forces the on-scroll
// container tint + shadow; `scrollElevate` listens to window scroll and
// applies it automatically once the page is scrolled (listener removed when
// the prop turns off or the element leaves the document).
func AppBar(p AppBarProps) *alacris.Element {
	e := alacris.E(AppBarTag)
	if p.Variant != "" && p.Variant != "small" {
		e.Prop("variant", p.Variant)
	}
	if p.Elevated {
		e.Prop("elevated", p.Elevated)
	}
	if p.ScrollElevate {
		e.Prop("scrollElevate", p.ScrollElevate)
	}
	return e
}

// AppBarHandle patches a rendered <ui-app-bar> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with AppBarElement.
type AppBarHandle struct {
	handle live.Handle
}

// AppBarElement addresses the <ui-app-bar> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	AppBarElement(c.Session, "id").SetVariant(v)
func AppBarElement(s *live.Session, id string) AppBarHandle {
	return AppBarHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h AppBarHandle) Handle() live.Handle { return h.handle }

// SetVariant writes the variant prop.
func (h AppBarHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetElevated writes the elevated prop.
func (h AppBarHandle) SetElevated(v bool) { h.handle.Set("elevated", v) }

// SetScrollElevate writes the scrollElevate prop.
func (h AppBarHandle) SetScrollElevate(v bool) { h.handle.Set("scrollElevate", v) }
