// Code generated by alacris-go from ../assets/ui/components/ui-accordion-item.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// AccordionItemTag is the name of the <ui-accordion-item> custom element.
const AccordionItemTag = "ui-accordion-item"

// Slots exposed by <ui-accordion-item>. Put one on your own markup to fill it:
//
//	<h3 slot={ AccordionItemSlotDefault }>
const (
	// panel content
	AccordionItemSlotDefault = ""
)

// Events emitted by <ui-accordion-item>. Forward one to a server action with On:
//
//	AccordionItem(props).On(AccordionItemEventUIAccordionToggle, "handler-name")
const (
	// header activated; detail: { value, expanded }
	AccordionItemEventUIAccordionToggle = "ui-accordion-toggle"
)

// AccordionItemUIAccordionToggleDetail is the detail of the "ui-accordion-toggle" event of <ui-accordion-item>.
//
// header activated; detail: { value, expanded }
type AccordionItemUIAccordionToggleDetail struct {
	Value    any `json:"value"`
	Expanded any `json:"expanded"`
}

// AccordionItemVars is the theming contract of <ui-accordion-item>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	AccordionItem(props).Apply(AccordionItemVars, map[string]string{"--ui-accordion-item-header-min-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var AccordionItemVars = alacris.Vars(
	"--ui-accordion-item-header-min-height",
	"--ui-accordion-item-pad-inline",
	"--ui-accordion-item-header-fg",
	"--ui-accordion-item-icon-fg",
	"--ui-accordion-item-content-fg",
	"--ui-accordion-item-font",
	"--ui-accordion-item-tracking",
	"--ui-accordion-item-content-font",
	"--ui-accordion-item-content-tracking",
)

// AccordionItemProps are the props of <ui-accordion-item>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type AccordionItemProps struct {
	// Value is REQUIRED identity of the panel (reported in events).
	//
	// The component defaults it to ''.
	Value string

	// The component defaults it to false.
	Expanded bool

	// The component defaults it to false.
	Disabled bool

	// Headline is header text.
	//
	// The component defaults it to ''.
	Headline string
}

// AccordionItem renders <ui-accordion-item>.
//
// <ui-accordion-item> — one expandable panel inside <ui-accordion>.
//
// Expand/collapse animates block-size from the measured content height; in
// environments without layout (zero heights) the animation is skipped and the
// state applies instantly. The content region gets `hidden` only AFTER the
// collapse animation completes.
func AccordionItem(p AccordionItemProps) *alacris.Element {
	e := alacris.E(AccordionItemTag)
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Expanded {
		e.Prop("expanded", p.Expanded)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Headline != "" {
		e.Prop("headline", p.Headline)
	}
	return e
}

// AccordionItemHandle patches a rendered <ui-accordion-item> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with AccordionItemElement.
type AccordionItemHandle struct {
	handle live.Handle
}

// AccordionItemElement addresses the <ui-accordion-item> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	AccordionItemElement(c.Session, "id").SetValue(v)
func AccordionItemElement(s *live.Session, id string) AccordionItemHandle {
	return AccordionItemHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h AccordionItemHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h AccordionItemHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetExpanded writes the expanded prop.
func (h AccordionItemHandle) SetExpanded(v bool) { h.handle.Set("expanded", v) }

// SetDisabled writes the disabled prop.
func (h AccordionItemHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetHeadline writes the headline prop.
func (h AccordionItemHandle) SetHeadline(v string) { h.handle.Set("headline", v) }
