// Code generated by alacris-go from ../assets/ui/components/ui-avatar.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// AvatarTag is the name of the <ui-avatar> custom element.
const AvatarTag = "ui-avatar"

// Slots exposed by <ui-avatar>. Put one on your own markup to fill it:
//
//	<h3 slot={ AvatarSlotDefault }>
const (
	// custom content when src/name/icon are all empty
	AvatarSlotDefault = ""
)

// AvatarVars is the theming contract of <ui-avatar>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Avatar(props).Apply(AvatarVars, map[string]string{"--ui-avatar-size": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var AvatarVars = alacris.Vars(
	"--ui-avatar-size",
	"--ui-avatar-bg",
	"--ui-avatar-fg",
	"--ui-avatar-radius",
)

// AvatarProps are the props of <ui-avatar>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type AvatarProps struct {
	// Src is image URL (object-fit: cover).
	//
	// The component defaults it to ''.
	Src string

	// Name is person's name; drives initials and the aria-label fallback.
	//
	// The component defaults it to ''.
	Name string

	// Icon is registry icon shown when there is no image and no name.
	//
	// The component defaults it to ''.
	Icon string

	// Size is CSS length overriding the 40px default (sets --ui-avatar-size).
	//
	// The component defaults it to ''.
	Size string

	// Label is accessible name; falls back to `name`, else decorative.
	//
	// The component defaults it to ''.
	Label string
}

// Avatar renders <ui-avatar>.
//
// <ui-avatar> — a circular avatar: image, initials, or icon.
//
// Fallback chain: `src` image → initials from `name` (first + last word) →
// `icon` → slotted content. A broken image (error event) falls back to the
// initials automatically. Initials scale with the avatar (~40% of its size).
func Avatar(p AvatarProps) *alacris.Element {
	e := alacris.E(AvatarTag)
	if p.Src != "" {
		e.Prop("src", p.Src)
	}
	if p.Name != "" {
		e.Prop("name", p.Name)
	}
	if p.Icon != "" {
		e.Prop("icon", p.Icon)
	}
	if p.Size != "" {
		e.Prop("size", p.Size)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// AvatarHandle patches a rendered <ui-avatar> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with AvatarElement.
type AvatarHandle struct {
	handle live.Handle
}

// AvatarElement addresses the <ui-avatar> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	AvatarElement(c.Session, "id").SetSrc(v)
func AvatarElement(s *live.Session, id string) AvatarHandle {
	return AvatarHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h AvatarHandle) Handle() live.Handle { return h.handle }

// SetSrc writes the src prop.
func (h AvatarHandle) SetSrc(v string) { h.handle.Set("src", v) }

// SetName writes the name prop.
func (h AvatarHandle) SetName(v string) { h.handle.Set("name", v) }

// SetIcon writes the icon prop.
func (h AvatarHandle) SetIcon(v string) { h.handle.Set("icon", v) }

// SetSize writes the size prop.
func (h AvatarHandle) SetSize(v string) { h.handle.Set("size", v) }

// SetLabel writes the label prop.
func (h AvatarHandle) SetLabel(v string) { h.handle.Set("label", v) }
