// Code generated by alacris-go from ../assets/ui/components/ui-button-group.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// ButtonGroupTag is the name of the <ui-button-group> custom element.
const ButtonGroupTag = "ui-button-group"

// Slots exposed by <ui-button-group>. Put one on your own markup to fill it:
//
//	<h3 slot={ ButtonGroupSlotDefault }>
const (
	// the <ui-button> children
	ButtonGroupSlotDefault = ""
)

// ButtonGroupVars is the theming contract of <ui-button-group>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	ButtonGroup(props).Apply(ButtonGroupVars, map[string]string{"--ui-button-group-radius": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var ButtonGroupVars = alacris.Vars(
	"--ui-button-group-radius",
	"--ui-button-group-divider",
)

// ButtonGroupProps are the props of <ui-button-group>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type ButtonGroupProps struct {
	// Label is accessible name for the group.
	//
	// The component defaults it to ''.
	Label string
}

// ButtonGroup renders <ui-button-group>.
//
// <ui-button-group> — joins slotted <ui-button>s into one segmented bar.
//
// Slotted buttons lose their own rounding (their `--ui-button-radius` is
// zeroed); the group container carries the full radius and clips, and a 1px
// gap lets the container's divider color show between segments — the Material
// connected button group.
func ButtonGroup(p ButtonGroupProps) *alacris.Element {
	e := alacris.E(ButtonGroupTag)
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// ButtonGroupHandle patches a rendered <ui-button-group> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with ButtonGroupElement.
type ButtonGroupHandle struct {
	handle live.Handle
}

// ButtonGroupElement addresses the <ui-button-group> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	ButtonGroupElement(c.Session, "id").SetLabel(v)
func ButtonGroupElement(s *live.Session, id string) ButtonGroupHandle {
	return ButtonGroupHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h ButtonGroupHandle) Handle() live.Handle { return h.handle }

// SetLabel writes the label prop.
func (h ButtonGroupHandle) SetLabel(v string) { h.handle.Set("label", v) }
