// Code generated by alacris-go from ../assets/ui/components/ui-button.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// ButtonTag is the name of the <ui-button> custom element.
const ButtonTag = "ui-button"

// Slots exposed by <ui-button>. Put one on your own markup to fill it:
//
//	<h3 slot={ ButtonSlotDefault }>
const (
	// label
	ButtonSlotDefault = ""
	// leading icon
	ButtonSlotIcon = "icon"
	// trailing icon
	ButtonSlotTrailing = "trailing"
)

// ButtonVars is the theming contract of <ui-button>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Button(props).Apply(ButtonVars, map[string]string{"--ui-button-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var ButtonVars = alacris.Vars(
	"--ui-button-height",
	"--ui-button-pad-inline",
	"--ui-button-gap",
	"--ui-button-radius",
	"--ui-button-font",
	"--ui-button-tracking",
	"--ui-button-filled-bg",
	"--ui-button-filled-fg",
	"--ui-button-tonal-bg",
	"--ui-button-tonal-fg",
	"--ui-button-outlined-fg",
	"--ui-button-outline-color",
	"--ui-button-text-fg",
	"--ui-button-elevated-bg",
	"--ui-button-elevated-fg",
)

// ButtonProps are the props of <ui-button>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type ButtonProps struct {
	// Variant is filled | tonal | outlined | text | elevated.
	//
	// The component defaults it to 'filled'.
	Variant string

	// The component defaults it to false.
	Disabled bool

	// Type is button | submit (submit reaches the enclosing form).
	//
	// The component defaults it to 'button'.
	Type string

	// Href is renders a link styled as a button.
	//
	// The component defaults it to ''.
	Href string

	// Target is link target when href is set.
	//
	// The component defaults it to ''.
	Target string
}

// Button renders <ui-button>.
//
// <ui-button> — the Material common button, all five variants.
func Button(p ButtonProps) *alacris.Element {
	e := alacris.E(ButtonTag)
	if p.Variant != "" && p.Variant != "filled" {
		e.Prop("variant", p.Variant)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Type != "" && p.Type != "button" {
		e.Prop("type", p.Type)
	}
	if p.Href != "" {
		e.Prop("href", p.Href)
	}
	if p.Target != "" {
		e.Prop("target", p.Target)
	}
	return e
}

// ButtonHandle patches a rendered <ui-button> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with ButtonElement.
type ButtonHandle struct {
	handle live.Handle
}

// ButtonElement addresses the <ui-button> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	ButtonElement(c.Session, "id").SetVariant(v)
func ButtonElement(s *live.Session, id string) ButtonHandle {
	return ButtonHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h ButtonHandle) Handle() live.Handle { return h.handle }

// SetVariant writes the variant prop.
func (h ButtonHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetDisabled writes the disabled prop.
func (h ButtonHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetType writes the type prop.
func (h ButtonHandle) SetType(v string) { h.handle.Set("type", v) }

// SetHref writes the href prop.
func (h ButtonHandle) SetHref(v string) { h.handle.Set("href", v) }

// SetTarget writes the target prop.
func (h ButtonHandle) SetTarget(v string) { h.handle.Set("target", v) }
