// Code generated by alacris-go from ../assets/ui/components/ui-badge.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// BadgeTag is the name of the <ui-badge> custom element.
const BadgeTag = "ui-badge"

// Slots exposed by <ui-badge>. Put one on your own markup to fill it:
//
//	<h3 slot={ BadgeSlotDefault }>
const (
	// the anchored content
	BadgeSlotDefault = ""
)

// BadgeVars is the theming contract of <ui-badge>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Badge(props).Apply(BadgeVars, map[string]string{"--ui-badge-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var BadgeVars = alacris.Vars(
	"--ui-badge-bg",
	"--ui-badge-fg",
	"--ui-badge-size",
	"--ui-badge-dot-size",
	"--ui-badge-font",
	"--ui-badge-tracking",
)

// BadgeProps are the props of <ui-badge>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type BadgeProps struct {
	// Value is the count; 0 hides the badge (unless `dot`).
	//
	// The component defaults it to 0.
	Value float64

	// Max is counts above this render as 'max+'.
	//
	// The component defaults it to 99.
	Max float64

	// Dot is a plain 8px dot instead of a count.
	//
	// The component defaults it to false.
	Dot bool

	// Show is master visibility switch.
	//
	// The component defaults it to true.
	Show *bool

	// Label is accessible meaning of the badge ('3 unread'); empty marks the badge decorative.
	//
	// The component defaults it to ''.
	Label string
}

// Badge renders <ui-badge>.
//
// <ui-badge> — a small status badge anchored to the top-end corner of its
// slotted content (an icon button, a nav item, an avatar…).
//
// Hidden while `value` is 0 unless `dot`. Counts above `max` render '99+'
// style. Appearing/disappearing animates with a scale-in/out.
func Badge(p BadgeProps) *alacris.Element {
	e := alacris.E(BadgeTag)
	if p.Value != 0 {
		e.Prop("value", p.Value)
	}
	if p.Max != 0 && p.Max != 99 {
		e.Prop("max", p.Max)
	}
	if p.Dot {
		e.Prop("dot", p.Dot)
	}
	if p.Show != nil {
		e.Prop("show", *p.Show)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// BadgeHandle patches a rendered <ui-badge> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with BadgeElement.
type BadgeHandle struct {
	handle live.Handle
}

// BadgeElement addresses the <ui-badge> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	BadgeElement(c.Session, "id").SetValue(v)
func BadgeElement(s *live.Session, id string) BadgeHandle {
	return BadgeHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h BadgeHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h BadgeHandle) SetValue(v float64) { h.handle.Set("value", v) }

// SetMax writes the max prop.
func (h BadgeHandle) SetMax(v float64) { h.handle.Set("max", v) }

// SetDot writes the dot prop.
func (h BadgeHandle) SetDot(v bool) { h.handle.Set("dot", v) }

// SetShow writes the show prop.
func (h BadgeHandle) SetShow(v bool) { h.handle.Set("show", v) }

// SetLabel writes the label prop.
func (h BadgeHandle) SetLabel(v string) { h.handle.Set("label", v) }
