// Code generated by alacris-go from ../assets/ui/components/ui-bottom-nav.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// BottomNavTag is the name of the <ui-bottom-nav> custom element.
const BottomNavTag = "ui-bottom-nav"

// Slots exposed by <ui-bottom-nav>. Put one on your own markup to fill it:
//
//	<h3 slot={ BottomNavSlotDefault }>
const (
	// <ui-nav-item> children
	BottomNavSlotDefault = ""
)

// Events emitted by <ui-bottom-nav>. Forward one to a server action with On:
//
//	BottomNav(props).On(BottomNavEventChange, "handler-name")
const (
	// a destination was chosen; detail: { value }
	BottomNavEventChange = "change"
)

// BottomNavChangeDetail is the detail of the "change" event of <ui-bottom-nav>.
//
// a destination was chosen; detail: { value }
type BottomNavChangeDetail struct {
	Value any `json:"value"`
}

// BottomNavVars is the theming contract of <ui-bottom-nav>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	BottomNav(props).Apply(BottomNavVars, map[string]string{"--ui-bottom-nav-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var BottomNavVars = alacris.Vars(
	"--ui-bottom-nav-height",
	"--ui-bottom-nav-bg",
	"--ui-bottom-nav-shadow",
)

// BottomNavProps are the props of <ui-bottom-nav>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type BottomNavProps struct {
	// Value is the selected item's `value`.
	//
	// The component defaults it to ''.
	Value string

	// Label is accessible name of the <nav>.
	//
	// The component defaults it to ''.
	Label string
}

// BottomNav renders <ui-bottom-nav>.
//
// <ui-bottom-nav> — the Material navigation bar.
//
// <ui-bottom-nav value=${route} @change=${(e) => route(e.detail.value)}>
// <ui-nav-item value="home" icon="home" label="Home"></ui-nav-item>
// <ui-nav-item value="search" icon="search" label="Search"></ui-nav-item>
// </ui-bottom-nav>
//
// The host is `display: block` and flows with the page — apps that want the
// bar pinned to the viewport position it themselves (position: fixed; bottom:
// 0; left: 0; right: 0). Selection reflects down: every `value` write (or
// slotchange) sets `selected` on the children. Keyboard: one Tab stop, arrow
// keys rove between items (rovingTabindex, horizontal).
func BottomNav(p BottomNavProps) *alacris.Element {
	e := alacris.E(BottomNavTag)
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// BottomNavHandle patches a rendered <ui-bottom-nav> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with BottomNavElement.
type BottomNavHandle struct {
	handle live.Handle
}

// BottomNavElement addresses the <ui-bottom-nav> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	BottomNavElement(c.Session, "id").SetValue(v)
func BottomNavElement(s *live.Session, id string) BottomNavHandle {
	return BottomNavHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h BottomNavHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h BottomNavHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetLabel writes the label prop.
func (h BottomNavHandle) SetLabel(v string) { h.handle.Set("label", v) }
