// Code generated by alacris-go from ../assets/ui/components/ui-backdrop.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// BackdropTag is the name of the <ui-backdrop> custom element.
const BackdropTag = "ui-backdrop"

// Events emitted by <ui-backdrop>. Forward one to a server action with On:
//
//	Backdrop(props).On(BackdropEventClose, "handler-name")
const (
	// scrim clicked; detail: { reason: 'scrim' }
	BackdropEventClose = "close"
)

// BackdropCloseDetail is the detail of the "close" event of <ui-backdrop>.
//
// scrim clicked; detail: { reason: 'scrim' }
type BackdropCloseDetail struct {
	Reason any `json:"reason"`
}

// BackdropVars is the theming contract of <ui-backdrop>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Backdrop(props).Apply(BackdropVars, map[string]string{"--ui-backdrop-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var BackdropVars = alacris.Vars(
	"--ui-backdrop-bg",
)

// BackdropProps are the props of <ui-backdrop>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type BackdropProps struct {
	// The component defaults it to false.
	Open bool

	// Invisible is transparent scrim (still catches clicks).
	//
	// The component defaults it to false.
	Invisible bool
}

// Backdrop renders <ui-backdrop>.
//
// <ui-backdrop> — a full-screen scrim behind custom overlays.
//
// <ui-backdrop open=${open} @close=${() => open(false)}></ui-backdrop>
//
// Fades in/out, locks page scroll while open, and requests closing by
// emitting `close` when the scrim is clicked — the PARENT owns the state and
// flips the signal.
func Backdrop(p BackdropProps) *alacris.Element {
	e := alacris.E(BackdropTag)
	if p.Open {
		e.Prop("open", p.Open)
	}
	if p.Invisible {
		e.Prop("invisible", p.Invisible)
	}
	return e
}

// BackdropHandle patches a rendered <ui-backdrop> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with BackdropElement.
type BackdropHandle struct {
	handle live.Handle
}

// BackdropElement addresses the <ui-backdrop> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	BackdropElement(c.Session, "id").SetOpen(v)
func BackdropElement(s *live.Session, id string) BackdropHandle {
	return BackdropHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h BackdropHandle) Handle() live.Handle { return h.handle }

// SetOpen writes the open prop.
func (h BackdropHandle) SetOpen(v bool) { h.handle.Set("open", v) }

// SetInvisible writes the invisible prop.
func (h BackdropHandle) SetInvisible(v bool) { h.handle.Set("invisible", v) }
