// Code generated by alacris-go from ../assets/ui/components/ui-bottom-app-bar.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// BottomAppBarTag is the name of the <ui-bottom-app-bar> custom element.
const BottomAppBarTag = "ui-bottom-app-bar"

// Slots exposed by <ui-bottom-app-bar>. Put one on your own markup to fill it:
//
//	<h3 slot={ BottomAppBarSlotNavigation }>
const (
	// leading icon button
	BottomAppBarSlotNavigation = "navigation"
	// trailing icon buttons
	BottomAppBarSlotActions = "actions"
	// optional <ui-fab>
	BottomAppBarSlotFab = "fab"
)

// BottomAppBarVars is the theming contract of <ui-bottom-app-bar>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	BottomAppBar(props).Apply(BottomAppBarVars, map[string]string{"--ui-bottom-app-bar-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var BottomAppBarVars = alacris.Vars(
	"--ui-bottom-app-bar-height",
	"--ui-bottom-app-bar-bg",
	"--ui-bottom-app-bar-fg",
	"--ui-bottom-app-bar-shadow",
)

// BottomAppBarProps are the props of <ui-bottom-app-bar>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type BottomAppBarProps struct {
	// Label is accessible name of the toolbar.
	//
	// The component defaults it to 'Bottom app bar'.
	Label string

	// FabAlign is end | center | start — where the FAB sits.
	//
	// The component defaults it to 'end'.
	FabAlign string
}

// BottomAppBar renders <ui-bottom-app-bar>.
//
// <ui-bottom-app-bar> — the Material bottom app bar.
//
// <ui-bottom-app-bar>
// <ui-icon-button slot="navigation" icon="menu" label="Menu"></ui-icon-button>
// <ui-icon-button slot="actions" icon="search" label="Search"></ui-icon-button>
// <ui-fab slot="fab" icon="add"></ui-fab>
// </ui-bottom-app-bar>
//
// A surface for a leading navigation icon, trailing actions, and an optional
// FAB. The host flows with the page — pin it with CSS when it should hug the
// viewport bottom. Distinct from <ui-bottom-nav>, which is destination tabs.
func BottomAppBar(p BottomAppBarProps) *alacris.Element {
	e := alacris.E(BottomAppBarTag)
	if p.Label != "" && p.Label != "Bottom app bar" {
		e.Prop("label", p.Label)
	}
	if p.FabAlign != "" && p.FabAlign != "end" {
		e.Prop("fabAlign", p.FabAlign)
	}
	return e
}

// BottomAppBarHandle patches a rendered <ui-bottom-app-bar> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with BottomAppBarElement.
type BottomAppBarHandle struct {
	handle live.Handle
}

// BottomAppBarElement addresses the <ui-bottom-app-bar> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	BottomAppBarElement(c.Session, "id").SetLabel(v)
func BottomAppBarElement(s *live.Session, id string) BottomAppBarHandle {
	return BottomAppBarHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h BottomAppBarHandle) Handle() live.Handle { return h.handle }

// SetLabel writes the label prop.
func (h BottomAppBarHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetFabAlign writes the fabAlign prop.
func (h BottomAppBarHandle) SetFabAlign(v string) { h.handle.Set("fabAlign", v) }
