// Code generated by alacris-go from ../assets/ui/components/ui-breadcrumbs.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// BreadcrumbsTag is the name of the <ui-breadcrumbs> custom element.
const BreadcrumbsTag = "ui-breadcrumbs"

// Slots exposed by <ui-breadcrumbs>. Put one on your own markup to fill it:
//
//	<h3 slot={ BreadcrumbsSlotDefault }>
const (
	// the trail items. Children MUST be elements (<a>, <span>, <ui-button variant="text">, …), never bare text nodes — separators are drawn with ::slotted(*)::before, which only exists on element children. Mark the current page with aria-current="page".
	BreadcrumbsSlotDefault = ""
)

// BreadcrumbsVars is the theming contract of <ui-breadcrumbs>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Breadcrumbs(props).Apply(BreadcrumbsVars, map[string]string{"--ui-breadcrumbs-fg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var BreadcrumbsVars = alacris.Vars(
	"--ui-breadcrumbs-fg",
	"--ui-breadcrumbs-current-fg",
	"--ui-breadcrumbs-separator-fg",
	"--ui-breadcrumbs-gap",
	"--ui-breadcrumbs-font",
	"--ui-breadcrumbs-tracking",
)

// BreadcrumbsProps are the props of <ui-breadcrumbs>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type BreadcrumbsProps struct {
	// Separator is separator text between items.
	//
	// The component defaults it to '/'.
	Separator string

	// SeparatorIcon is registry icon name; overrides `separator`.
	//
	// The component defaults it to ''.
	SeparatorIcon string

	// Label is accessible name of the <nav>.
	//
	// The component defaults it to 'Breadcrumb'.
	Label string
}

// Breadcrumbs renders <ui-breadcrumbs>.
//
// <ui-breadcrumbs> — a navigation trail of slotted links.
//
// <ui-breadcrumbs separator-icon="chevron-right">
// <a href="/">Home</a>
// <a href="/library">Library</a>
// <span aria-current="page">Data</span>
// </ui-breadcrumbs>
//
// Separators are rendered as generated content on every item but the first:
// text mode sets the `content` from a private custom property; icon mode masks
// a currentColor box with the icon's path, so it themes like any glyph.
func Breadcrumbs(p BreadcrumbsProps) *alacris.Element {
	e := alacris.E(BreadcrumbsTag)
	if p.Separator != "" && p.Separator != "/" {
		e.Prop("separator", p.Separator)
	}
	if p.SeparatorIcon != "" {
		e.Prop("separatorIcon", p.SeparatorIcon)
	}
	if p.Label != "" && p.Label != "Breadcrumb" {
		e.Prop("label", p.Label)
	}
	return e
}

// BreadcrumbsHandle patches a rendered <ui-breadcrumbs> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with BreadcrumbsElement.
type BreadcrumbsHandle struct {
	handle live.Handle
}

// BreadcrumbsElement addresses the <ui-breadcrumbs> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	BreadcrumbsElement(c.Session, "id").SetSeparator(v)
func BreadcrumbsElement(s *live.Session, id string) BreadcrumbsHandle {
	return BreadcrumbsHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h BreadcrumbsHandle) Handle() live.Handle { return h.handle }

// SetSeparator writes the separator prop.
func (h BreadcrumbsHandle) SetSeparator(v string) { h.handle.Set("separator", v) }

// SetSeparatorIcon writes the separatorIcon prop.
func (h BreadcrumbsHandle) SetSeparatorIcon(v string) { h.handle.Set("separatorIcon", v) }

// SetLabel writes the label prop.
func (h BreadcrumbsHandle) SetLabel(v string) { h.handle.Set("label", v) }
