// Code generated by alacris-go from ../assets/ui/components/ui-chip.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// ChipTag is the name of the <ui-chip> custom element.
const ChipTag = "ui-chip"

// Slots exposed by <ui-chip>. Put one on your own markup to fill it:
//
//	<h3 slot={ ChipSlotDefault }>
const (
	// the chip label
	ChipSlotDefault = ""
)

// Events emitted by <ui-chip>. Forward one to a server action with On:
//
//	Chip(props).On(ChipEventChange, "handler-name")
const (
	// filter chip toggled; detail: { selected }
	ChipEventChange = "change"
	// remove requested (after the collapse animation)
	ChipEventDismiss = "dismiss"
)

// ChipChangeDetail is the detail of the "change" event of <ui-chip>.
//
// filter chip toggled; detail: { selected }
type ChipChangeDetail struct {
	Selected any `json:"selected"`
}

// ChipVars is the theming contract of <ui-chip>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Chip(props).Apply(ChipVars, map[string]string{"--ui-chip-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var ChipVars = alacris.Vars(
	"--ui-chip-height",
	"--ui-chip-radius",
	"--ui-chip-fg",
	"--ui-chip-label-fg",
	"--ui-chip-outline-color",
	"--ui-chip-selected-bg",
	"--ui-chip-selected-fg",
	"--ui-chip-font",
)

// ChipProps are the props of <ui-chip>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type ChipProps struct {
	// Variant is assist | filter | input | suggestion.
	//
	// The component defaults it to 'assist'.
	Variant string

	// Selected is filter chips only.
	//
	// The component defaults it to false.
	Selected bool

	// The component defaults it to false.
	Disabled bool

	// Icon is leading icon name (check replaces it while a filter chip is selected).
	//
	// The component defaults it to ''.
	Icon string

	// Dismissible is trailing remove button.
	//
	// The component defaults it to false.
	Dismissible bool

	// Value is identity within a <ui-chip-set>.
	//
	// The component defaults it to ''.
	Value string
}

// Chip renders <ui-chip>.
//
// <ui-chip> — Material chip: assist, filter, input, and suggestion.
//
// The HOST is the interactive element (focusable, role="button" — or
// role="option" with aria-selected for filter chips) so that <ui-chip-set>'s
// roving tabindex can move focus across plain light-DOM chips.
//
// Filter chips toggle `selected` on click/Enter/Space and emit `change`;
// assist/suggestion/input chips just let the native click bubble. A
// dismissible chip animates the host collapsing, then emits `dismiss` — the
// PARENT owns the list and removes the chip from the DOM; the chip never
// removes itself.
func Chip(p ChipProps) *alacris.Element {
	e := alacris.E(ChipTag)
	if p.Variant != "" && p.Variant != "assist" {
		e.Prop("variant", p.Variant)
	}
	if p.Selected {
		e.Prop("selected", p.Selected)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Icon != "" {
		e.Prop("icon", p.Icon)
	}
	if p.Dismissible {
		e.Prop("dismissible", p.Dismissible)
	}
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	return e
}

// ChipHandle patches a rendered <ui-chip> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with ChipElement.
type ChipHandle struct {
	handle live.Handle
}

// ChipElement addresses the <ui-chip> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	ChipElement(c.Session, "id").SetVariant(v)
func ChipElement(s *live.Session, id string) ChipHandle {
	return ChipHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h ChipHandle) Handle() live.Handle { return h.handle }

// SetVariant writes the variant prop.
func (h ChipHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetSelected writes the selected prop.
func (h ChipHandle) SetSelected(v bool) { h.handle.Set("selected", v) }

// SetDisabled writes the disabled prop.
func (h ChipHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetIcon writes the icon prop.
func (h ChipHandle) SetIcon(v string) { h.handle.Set("icon", v) }

// SetDismissible writes the dismissible prop.
func (h ChipHandle) SetDismissible(v bool) { h.handle.Set("dismissible", v) }

// SetValue writes the value prop.
func (h ChipHandle) SetValue(v string) { h.handle.Set("value", v) }
