// Code generated by alacris-go from ../assets/ui/components/ui-carousel-item.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// CarouselItemTag is the name of the <ui-carousel-item> custom element.
const CarouselItemTag = "ui-carousel-item"

// Slots exposed by <ui-carousel-item>. Put one on your own markup to fill it:
//
//	<h3 slot={ CarouselItemSlotDefault }>
const (
	// slide content
	CarouselItemSlotDefault = ""
)

// CarouselItemVars is the theming contract of <ui-carousel-item>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	CarouselItem(props).Apply(CarouselItemVars, map[string]string{"--ui-carousel-item-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var CarouselItemVars = alacris.Vars(
	"--ui-carousel-item-bg",
	"--ui-carousel-item-fg",
	"--ui-carousel-item-radius",
)

// CarouselItemProps are the props of <ui-carousel-item>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type CarouselItemProps struct {
	// Selected is managed by the parent <ui-carousel>.
	//
	// The component defaults it to false.
	Selected bool
}

// CarouselItem renders <ui-carousel-item>.
//
// <ui-carousel-item> — one slide inside <ui-carousel>.
//
// `selected` is written by the parent carousel; set the carousel's `index`
// instead of this prop. Width comes from `--ui-carousel-item-basis` on the
// parent (so the carousel variants can size slides without fighting `:host`).
// The last item snaps to the end of the track so it can be scrolled fully into
// view.
func CarouselItem(p CarouselItemProps) *alacris.Element {
	e := alacris.E(CarouselItemTag)
	if p.Selected {
		e.Prop("selected", p.Selected)
	}
	return e
}

// CarouselItemHandle patches a rendered <ui-carousel-item> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with CarouselItemElement.
type CarouselItemHandle struct {
	handle live.Handle
}

// CarouselItemElement addresses the <ui-carousel-item> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	CarouselItemElement(c.Session, "id").SetSelected(v)
func CarouselItemElement(s *live.Session, id string) CarouselItemHandle {
	return CarouselItemHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h CarouselItemHandle) Handle() live.Handle { return h.handle }

// SetSelected writes the selected prop.
func (h CarouselItemHandle) SetSelected(v bool) { h.handle.Set("selected", v) }
