// Code generated by alacris-go from ../assets/ui/components/ui-carousel.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// CarouselTag is the name of the <ui-carousel> custom element.
const CarouselTag = "ui-carousel"

// Slots exposed by <ui-carousel>. Put one on your own markup to fill it:
//
//	<h3 slot={ CarouselSlotDefault }>
const (
	// <ui-carousel-item> children
	CarouselSlotDefault = ""
)

// Events emitted by <ui-carousel>. Forward one to a server action with On:
//
//	Carousel(props).On(CarouselEventChange, "handler-name")
const (
	// index moved; detail: { index }
	CarouselEventChange = "change"
)

// CarouselChangeDetail is the detail of the "change" event of <ui-carousel>.
//
// index moved; detail: { index }
type CarouselChangeDetail struct {
	Index any `json:"index"`
}

// CarouselVars is the theming contract of <ui-carousel>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Carousel(props).Apply(CarouselVars, map[string]string{"--ui-carousel-gap": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var CarouselVars = alacris.Vars(
	"--ui-carousel-gap",
	"--ui-carousel-height",
	"--ui-carousel-hero-size",
	"--ui-carousel-control-fg",
	"--ui-carousel-item-basis",
)

// CarouselProps are the props of <ui-carousel>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type CarouselProps struct {
	// Index is the selected slide.
	//
	// The component defaults it to 0.
	Index float64

	// Variant is multi-browse | uncontained | hero.
	//
	// The component defaults it to 'multi-browse'.
	Variant string

	// Label is accessible name for the region.
	//
	// The component defaults it to ''.
	Label string
}

// Carousel renders <ui-carousel>.
//
// <ui-carousel> — a Material carousel: snap-scrolling slides with previous /
// next controls.
//
// <ui-carousel label="Photos" variant="multi-browse">
// <ui-carousel-item>One</ui-carousel-item>
// <ui-carousel-item>Two</ui-carousel-item>
// </ui-carousel>
//
// multi-browse shows several items; uncontained lets slides overflow the
// frame; hero makes the selected slide dominate. Selection reflects down as
// `selected` on each <ui-carousel-item>. Prev/next (and arrow keys) scroll
// the selected slide into view; dragging the track updates `index`. The last
// slide snaps to the end of the viewport so a hero (or any oversized) last
// item can still become selected.
func Carousel(p CarouselProps) *alacris.Element {
	e := alacris.E(CarouselTag)
	if p.Index != 0 {
		e.Prop("index", p.Index)
	}
	if p.Variant != "" && p.Variant != "multi-browse" {
		e.Prop("variant", p.Variant)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// CarouselHandle patches a rendered <ui-carousel> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with CarouselElement.
type CarouselHandle struct {
	handle live.Handle
}

// CarouselElement addresses the <ui-carousel> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	CarouselElement(c.Session, "id").SetIndex(v)
func CarouselElement(s *live.Session, id string) CarouselHandle {
	return CarouselHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h CarouselHandle) Handle() live.Handle { return h.handle }

// SetIndex writes the index prop.
func (h CarouselHandle) SetIndex(v float64) { h.handle.Set("index", v) }

// SetVariant writes the variant prop.
func (h CarouselHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetLabel writes the label prop.
func (h CarouselHandle) SetLabel(v string) { h.handle.Set("label", v) }
