// Code generated by alacris-go from ../assets/ui/components/ui-chip-set.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// ChipSetTag is the name of the <ui-chip-set> custom element.
const ChipSetTag = "ui-chip-set"

// Slots exposed by <ui-chip-set>. Put one on your own markup to fill it:
//
//	<h3 slot={ ChipSetSlotDefault }>
const (
	// <ui-chip> children
	ChipSetSlotDefault = ""
)

// Events emitted by <ui-chip-set>. Forward one to a server action with On:
//
//	ChipSet(props).On(ChipSetEventChange, "handler-name")
const (
	// single-select mode only; detail: { value }
	ChipSetEventChange = "change"
)

// ChipSetChangeDetail is the detail of the "change" event of <ui-chip-set>.
//
// single-select mode only; detail: { value }
type ChipSetChangeDetail struct {
	Value any `json:"value"`
}

// ChipSetVars is the theming contract of <ui-chip-set>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	ChipSet(props).Apply(ChipSetVars, map[string]string{"--ui-chip-set-gap": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var ChipSetVars = alacris.Vars(
	"--ui-chip-set-gap",
)

// ChipSetProps are the props of <ui-chip-set>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type ChipSetProps struct {
	// Label is accessible name for the set.
	//
	// The component defaults it to ''.
	Label string

	// Multi is allow several filter chips selected at once.
	//
	// The component defaults it to false.
	Multi bool
}

// ChipSet renders <ui-chip-set>.
//
// <ui-chip-set> — a wrapping row of <ui-chip>s with roving-tabindex focus.
//
// When any slotted chip is a filter chip the set is a listbox
// (aria-multiselectable mirrors `multi`); otherwise it is a plain group.
// Single-select coordination: with `multi=false`, selecting a filter chip
// deselects its siblings and the set emits `change` with the selected chip's
// `value`; deselecting the active chip emits `change` with ”.
func ChipSet(p ChipSetProps) *alacris.Element {
	e := alacris.E(ChipSetTag)
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Multi {
		e.Prop("multi", p.Multi)
	}
	return e
}

// ChipSetHandle patches a rendered <ui-chip-set> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with ChipSetElement.
type ChipSetHandle struct {
	handle live.Handle
}

// ChipSetElement addresses the <ui-chip-set> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	ChipSetElement(c.Session, "id").SetLabel(v)
func ChipSetElement(s *live.Session, id string) ChipSetHandle {
	return ChipSetHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h ChipSetHandle) Handle() live.Handle { return h.handle }

// SetLabel writes the label prop.
func (h ChipSetHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetMulti writes the multi prop.
func (h ChipSetHandle) SetMulti(v bool) { h.handle.Set("multi", v) }
