// Code generated by alacris-go from ../assets/ui/components/ui-card.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// CardTag is the name of the <ui-card> custom element.
const CardTag = "ui-card"

// Slots exposed by <ui-card>. Put one on your own markup to fill it:
//
//	<h3 slot={ CardSlotDefault }>
const (
	// card body (compose freely; padding is yours via parts/vars)
	CardSlotDefault = ""
	// full-bleed media at the top
	CardSlotMedia = "media"
)

// Events emitted by <ui-card>. Forward one to a server action with On:
//
//	Card(props).On(CardEventAction, "handler-name")
const (
	// interactive card activated (click/Enter/Space)
	CardEventAction = "action"
)

// CardVars is the theming contract of <ui-card>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Card(props).Apply(CardVars, map[string]string{"--ui-card-radius": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var CardVars = alacris.Vars(
	"--ui-card-radius",
	"--ui-card-bg",
	"--ui-card-fg",
	"--ui-card-filled-bg",
	"--ui-card-outline-color",
	"--ui-card-padding",
)

// CardProps are the props of <ui-card>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type CardProps struct {
	// Variant is elevated | filled | outlined.
	//
	// The component defaults it to 'elevated'.
	Variant string

	// Interactive is hover elevation + ripple + button semantics.
	//
	// The component defaults it to false.
	Interactive bool
}

// Card renders <ui-card>.
//
// <ui-card> — a Material card surface.
func Card(p CardProps) *alacris.Element {
	e := alacris.E(CardTag)
	if p.Variant != "" && p.Variant != "elevated" {
		e.Prop("variant", p.Variant)
	}
	if p.Interactive {
		e.Prop("interactive", p.Interactive)
	}
	return e
}

// CardHandle patches a rendered <ui-card> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with CardElement.
type CardHandle struct {
	handle live.Handle
}

// CardElement addresses the <ui-card> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	CardElement(c.Session, "id").SetVariant(v)
func CardElement(s *live.Session, id string) CardHandle {
	return CardHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h CardHandle) Handle() live.Handle { return h.handle }

// SetVariant writes the variant prop.
func (h CardHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetInteractive writes the interactive prop.
func (h CardHandle) SetInteractive(v bool) { h.handle.Set("interactive", v) }
