// Code generated by alacris-go from ../assets/ui/components/ui-container.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// ContainerTag is the name of the <ui-container> custom element.
const ContainerTag = "ui-container"

// Slots exposed by <ui-container>. Put one on your own markup to fill it:
//
//	<h3 slot={ ContainerSlotDefault }>
const (
	ContainerSlotDefault = ""
)

// ContainerVars is the theming contract of <ui-container>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Container(props).Apply(ContainerVars, map[string]string{"--ui-container-sm": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var ContainerVars = alacris.Vars(
	"--ui-container-sm",
	"--ui-container-md",
	"--ui-container-lg",
	"--ui-container-xl",
	"--ui-container-gutter",
	"--ui-container-gutter-narrow",
)

// ContainerProps are the props of <ui-container>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type ContainerProps struct {
	// Size is sm (640px) | md (960px) | lg (1280px) | xl (1536px) | full (no max width).
	//
	// The component defaults it to 'md'.
	Size string

	// Gutters is inline padding: space(6), space(4) under 600px.
	//
	// The component defaults it to true.
	Gutters *bool
}

// Container renders <ui-container>.
//
// <ui-container> — a centered max-width content wrapper.
//
// <ui-container size="lg">…</ui-container>
func Container(p ContainerProps) *alacris.Element {
	e := alacris.E(ContainerTag)
	if p.Size != "" && p.Size != "md" {
		e.Prop("size", p.Size)
	}
	if p.Gutters != nil {
		e.Prop("gutters", *p.Gutters)
	}
	return e
}

// ContainerHandle patches a rendered <ui-container> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with ContainerElement.
type ContainerHandle struct {
	handle live.Handle
}

// ContainerElement addresses the <ui-container> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	ContainerElement(c.Session, "id").SetSize(v)
func ContainerElement(s *live.Session, id string) ContainerHandle {
	return ContainerHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h ContainerHandle) Handle() live.Handle { return h.handle }

// SetSize writes the size prop.
func (h ContainerHandle) SetSize(v string) { h.handle.Set("size", v) }

// SetGutters writes the gutters prop.
func (h ContainerHandle) SetGutters(v bool) { h.handle.Set("gutters", v) }
