// Code generated by alacris-go from ../assets/ui/components/ui-checkbox.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// CheckboxTag is the name of the <ui-checkbox> custom element.
const CheckboxTag = "ui-checkbox"

// Events emitted by <ui-checkbox>. Forward one to a server action with On:
//
//	Checkbox(props).On(CheckboxEventChange, "handler-name")
const (
	// detail: { checked, indeterminate: false }
	CheckboxEventChange = "change"
)

// CheckboxChangeDetail is the detail of the "change" event of <ui-checkbox>.
//
// detail: { checked, indeterminate: false }
type CheckboxChangeDetail struct {
	Checked       any `json:"checked"`
	Indeterminate any `json:"indeterminate"`
}

// CheckboxVars is the theming contract of <ui-checkbox>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Checkbox(props).Apply(CheckboxVars, map[string]string{"--ui-checkbox-target": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var CheckboxVars = alacris.Vars(
	"--ui-checkbox-target",
	"--ui-checkbox-box-size",
	"--ui-checkbox-radius",
	"--ui-checkbox-outline-color",
	"--ui-checkbox-bg",
	"--ui-checkbox-mark-fg",
	"--ui-checkbox-label-fg",
)

// CheckboxProps are the props of <ui-checkbox>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type CheckboxProps struct {
	// The component defaults it to false.
	Checked bool

	// Indeterminate is aria-checked="mixed", shows a dash.
	//
	// The component defaults it to false.
	Indeterminate bool

	// The component defaults it to false.
	Disabled bool

	// Label is visible label; also the accessible name. Empty leaves the control unnamed (authoring error).
	//
	// The component defaults it to ''.
	Label string

	// Name is form field name (submits `value` while checked).
	//
	// The component defaults it to ''.
	Name string

	// The component defaults it to 'on'.
	Value string
}

// Checkbox renders <ui-checkbox>.
//
// <ui-checkbox> — the Material checkbox with indeterminate support.
//
// The interactive element is a native <button role="checkbox"> sized to a
// 40px touch target; the visible 18px box sits centered inside it. Clicking
// clears `indeterminate` and toggles `checked`. The check/dash is the MD3
// 2px stroke mark in the 18dp icon, not the generic 24dp `check` glyph.
func Checkbox(p CheckboxProps) *alacris.Element {
	e := alacris.E(CheckboxTag)
	if p.Checked {
		e.Prop("checked", p.Checked)
	}
	if p.Indeterminate {
		e.Prop("indeterminate", p.Indeterminate)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Name != "" {
		e.Prop("name", p.Name)
	}
	if p.Value != "" && p.Value != "on" {
		e.Prop("value", p.Value)
	}
	return e
}

// CheckboxHandle patches a rendered <ui-checkbox> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with CheckboxElement.
type CheckboxHandle struct {
	handle live.Handle
}

// CheckboxElement addresses the <ui-checkbox> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	CheckboxElement(c.Session, "id").SetChecked(v)
func CheckboxElement(s *live.Session, id string) CheckboxHandle {
	return CheckboxHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h CheckboxHandle) Handle() live.Handle { return h.handle }

// SetChecked writes the checked prop.
func (h CheckboxHandle) SetChecked(v bool) { h.handle.Set("checked", v) }

// SetIndeterminate writes the indeterminate prop.
func (h CheckboxHandle) SetIndeterminate(v bool) { h.handle.Set("indeterminate", v) }

// SetDisabled writes the disabled prop.
func (h CheckboxHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetLabel writes the label prop.
func (h CheckboxHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetName writes the name prop.
func (h CheckboxHandle) SetName(v string) { h.handle.Set("name", v) }

// SetValue writes the value prop.
func (h CheckboxHandle) SetValue(v string) { h.handle.Set("value", v) }
