// Code generated by alacris-go from ../assets/ui/components/ui-dialog.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// DialogTag is the name of the <ui-dialog> custom element.
const DialogTag = "ui-dialog"

// Slots exposed by <ui-dialog>. Put one on your own markup to fill it:
//
//	<h3 slot={ DialogSlotDefault }>
const (
	// body content
	DialogSlotDefault  = ""
	DialogSlotHeadline = "headline"
	// right-aligned buttons
	DialogSlotActions = "actions"
)

// Events emitted by <ui-dialog>. Forward one to a server action with On:
//
//	Dialog(props).On(DialogEventClose, "handler-name")
const (
	// detail: { reason: 'esc' | 'scrim' | 'method' }
	DialogEventClose = "close"
	// enter animation finished
	DialogEventOpened = "opened"
	// exit animation finished, DOM removed
	DialogEventClosed = "closed"
)

// DialogCloseDetail is the detail of the "close" event of <ui-dialog>.
//
// detail: { reason: 'esc' | 'scrim' | 'method' }
type DialogCloseDetail struct {
	Reason any `json:"reason"`
}

// DialogVars is the theming contract of <ui-dialog>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Dialog(props).Apply(DialogVars, map[string]string{"--ui-dialog-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var DialogVars = alacris.Vars(
	"--ui-dialog-bg",
	"--ui-dialog-fg",
	"--ui-dialog-headline-fg",
	"--ui-dialog-radius",
	"--ui-dialog-width",
	"--ui-dialog-scrim",
)

// DialogProps are the props of <ui-dialog>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type DialogProps struct {
	// The component defaults it to false.
	Open bool

	// Persistent is escape/scrim do not request closing.
	//
	// The component defaults it to false.
	Persistent bool

	// Label is accessible name if no headline slot.
	//
	// The component defaults it to ''.
	Label string
}

// Dialog renders <ui-dialog>.
//
// <ui-dialog> — a modal dialog.
//
// <ui-dialog open=${open} @close=${() => open(false)}>
// <span slot="headline">Discard draft?</span>
// Your changes will be lost.
// <ui-button slot="actions" variant="text">Cancel</ui-button>
// <ui-button slot="actions">Discard</ui-button>
// </ui-dialog>
//
// Opening: set the `open` prop (pass a signal from the parent to stay live).
// The dialog animates in, traps focus, and locks page scroll. It requests
// closing by emitting `close` with a reason — the PARENT owns the state and
// flips the signal; Escape and scrim clicks emit `close` too (unless
// `persistent`).
func Dialog(p DialogProps) *alacris.Element {
	e := alacris.E(DialogTag)
	if p.Open {
		e.Prop("open", p.Open)
	}
	if p.Persistent {
		e.Prop("persistent", p.Persistent)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// DialogHandle patches a rendered <ui-dialog> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with DialogElement.
type DialogHandle struct {
	handle live.Handle
}

// DialogElement addresses the <ui-dialog> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	DialogElement(c.Session, "id").SetOpen(v)
func DialogElement(s *live.Session, id string) DialogHandle {
	return DialogHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h DialogHandle) Handle() live.Handle { return h.handle }

// SetOpen writes the open prop.
func (h DialogHandle) SetOpen(v bool) { h.handle.Set("open", v) }

// SetPersistent writes the persistent prop.
func (h DialogHandle) SetPersistent(v bool) { h.handle.Set("persistent", v) }

// SetLabel writes the label prop.
func (h DialogHandle) SetLabel(v string) { h.handle.Set("label", v) }
