// Code generated by alacris-go from ../assets/ui/components/ui-divider.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// DividerTag is the name of the <ui-divider> custom element.
const DividerTag = "ui-divider"

// DividerVars is the theming contract of <ui-divider>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Divider(props).Apply(DividerVars, map[string]string{"--ui-divider-color": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var DividerVars = alacris.Vars(
	"--ui-divider-color",
	"--ui-divider-thickness",
)

// DividerProps are the props of <ui-divider>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type DividerProps struct {
	// Orientation is horizontal | vertical.
	//
	// The component defaults it to 'horizontal'.
	Orientation string

	// Inset is indented from the start edge (16px).
	//
	// The component defaults it to false.
	Inset bool

	// Middle is indented from both edges.
	//
	// The component defaults it to false.
	Middle bool
}

// Divider renders <ui-divider>.
//
// <ui-divider> — a 1px rule separating content, horizontal or vertical.
//
// Props reflect to host attributes so the styling is pure CSS on :host.
//
// role="separator" with aria-orientation.
func Divider(p DividerProps) *alacris.Element {
	e := alacris.E(DividerTag)
	if p.Orientation != "" && p.Orientation != "horizontal" {
		e.Prop("orientation", p.Orientation)
	}
	if p.Inset {
		e.Prop("inset", p.Inset)
	}
	if p.Middle {
		e.Prop("middle", p.Middle)
	}
	return e
}

// DividerHandle patches a rendered <ui-divider> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with DividerElement.
type DividerHandle struct {
	handle live.Handle
}

// DividerElement addresses the <ui-divider> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	DividerElement(c.Session, "id").SetOrientation(v)
func DividerElement(s *live.Session, id string) DividerHandle {
	return DividerHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h DividerHandle) Handle() live.Handle { return h.handle }

// SetOrientation writes the orientation prop.
func (h DividerHandle) SetOrientation(v string) { h.handle.Set("orientation", v) }

// SetInset writes the inset prop.
func (h DividerHandle) SetInset(v bool) { h.handle.Set("inset", v) }

// SetMiddle writes the middle prop.
func (h DividerHandle) SetMiddle(v bool) { h.handle.Set("middle", v) }
