// Code generated by alacris-go from ../assets/ui/components/ui-date-picker.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// DatePickerTag is the name of the <ui-date-picker> custom element.
const DatePickerTag = "ui-date-picker"

// Events emitted by <ui-date-picker>. Forward one to a server action with On:
//
//	DatePicker(props).On(DatePickerEventChange, "handler-name")
const (
	// committed; detail: { value } or { start, end, value } when range
	DatePickerEventChange = "change"
	// field keystroke; detail: { value } (the raw text)
	DatePickerEventInput = "input"
	// calendar visible (after the enter animation)
	DatePickerEventOpen = "open"
	// calendar removed (after the exit animation)
	DatePickerEventClose = "close"
)

// DatePickerChangeDetail is the detail of the "change" event of <ui-date-picker>.
//
// committed; detail: { value } or { start, end, value } when range
type DatePickerChangeDetail struct {
	Value any `json:"value"`
}

// DatePickerInputDetail is the detail of the "input" event of <ui-date-picker>.
//
// field keystroke; detail: { value } (the raw text)
type DatePickerInputDetail struct {
	Value any `json:"value"`
}

// DatePickerVars is the theming contract of <ui-date-picker>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	DatePicker(props).Apply(DatePickerVars, map[string]string{"--ui-date-picker-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var DatePickerVars = alacris.Vars(
	"--ui-date-picker-bg",
	"--ui-date-picker-fg",
	"--ui-date-picker-label-fg",
	"--ui-date-picker-accent",
	"--ui-date-picker-on-accent",
	"--ui-date-picker-outline-color",
	"--ui-date-picker-radius",
	"--ui-date-picker-font",
	"--ui-date-picker-height",
	"--ui-date-picker-panel-bg",
	"--ui-date-picker-panel-radius",
	"--ui-date-picker-day-radius",
	"--ui-date-picker-today-fg",
	"--ui-date-picker-muted-fg",
	"--ui-date-picker-range-bg",
	"--ui-date-picker-range-fg",
	"--ui-date-picker-scrim",
)

// DatePickerProps are the props of <ui-date-picker>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type DatePickerProps struct {
	// The component defaults it to ''.
	Label string

	// Value is ISO date (YYYY-MM-DD); range: start/end.
	//
	// The component defaults it to ''.
	Value string

	// Range is pick a start and end date.
	//
	// The component defaults it to false.
	Range bool

	// Start is range start ISO.
	//
	// The component defaults it to ''.
	Start string

	// End is range end ISO.
	//
	// The component defaults it to ''.
	End string

	// Variant is filled | outlined.
	//
	// The component defaults it to 'filled'.
	Variant string

	// Presentation is docked | modal.
	//
	// The component defaults it to 'docked'.
	Presentation string

	// Min is inclusive ISO lower bound.
	//
	// The component defaults it to ''.
	Min string

	// Max is inclusive ISO upper bound.
	//
	// The component defaults it to ''.
	Max string

	// Locale is BCP 47 tag; empty uses the runtime locale.
	//
	// The component defaults it to ''.
	Locale string

	// The component defaults it to false.
	Disabled bool

	// The component defaults it to false.
	Required bool

	// Name is form participation.
	//
	// The component defaults it to ''.
	Name string

	// The component defaults it to ''.
	Placeholder string
}

// DatePicker renders <ui-date-picker>.
//
// <ui-date-picker> — Material date picker: a text-field-style control that
// opens a calendar. Docked (default) commits on day click; modal confirms
// with OK / Cancel.
//
// <ui-date-picker label="Event" value=${date}
// `value` is an ISO date string (YYYY-MM-DD), or ” for none. Typing an
// ISO or locale-formatted date into the field commits on blur / Enter.
// Set `range` to pick a start and end; `change` then reports
// `{ start, end, value }` where `value` is `start/end`.
func DatePicker(p DatePickerProps) *alacris.Element {
	e := alacris.E(DatePickerTag)
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Range {
		e.Prop("range", p.Range)
	}
	if p.Start != "" {
		e.Prop("start", p.Start)
	}
	if p.End != "" {
		e.Prop("end", p.End)
	}
	if p.Variant != "" && p.Variant != "filled" {
		e.Prop("variant", p.Variant)
	}
	if p.Presentation != "" && p.Presentation != "docked" {
		e.Prop("presentation", p.Presentation)
	}
	if p.Min != "" {
		e.Prop("min", p.Min)
	}
	if p.Max != "" {
		e.Prop("max", p.Max)
	}
	if p.Locale != "" {
		e.Prop("locale", p.Locale)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Required {
		e.Prop("required", p.Required)
	}
	if p.Name != "" {
		e.Prop("name", p.Name)
	}
	if p.Placeholder != "" {
		e.Prop("placeholder", p.Placeholder)
	}
	return e
}

// DatePickerHandle patches a rendered <ui-date-picker> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with DatePickerElement.
type DatePickerHandle struct {
	handle live.Handle
}

// DatePickerElement addresses the <ui-date-picker> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	DatePickerElement(c.Session, "id").SetLabel(v)
func DatePickerElement(s *live.Session, id string) DatePickerHandle {
	return DatePickerHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h DatePickerHandle) Handle() live.Handle { return h.handle }

// SetLabel writes the label prop.
func (h DatePickerHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetValue writes the value prop.
func (h DatePickerHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetRange writes the range prop.
func (h DatePickerHandle) SetRange(v bool) { h.handle.Set("range", v) }

// SetStart writes the start prop.
func (h DatePickerHandle) SetStart(v string) { h.handle.Set("start", v) }

// SetEnd writes the end prop.
func (h DatePickerHandle) SetEnd(v string) { h.handle.Set("end", v) }

// SetVariant writes the variant prop.
func (h DatePickerHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetPresentation writes the presentation prop.
func (h DatePickerHandle) SetPresentation(v string) { h.handle.Set("presentation", v) }

// SetMin writes the min prop.
func (h DatePickerHandle) SetMin(v string) { h.handle.Set("min", v) }

// SetMax writes the max prop.
func (h DatePickerHandle) SetMax(v string) { h.handle.Set("max", v) }

// SetLocale writes the locale prop.
func (h DatePickerHandle) SetLocale(v string) { h.handle.Set("locale", v) }

// SetDisabled writes the disabled prop.
func (h DatePickerHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetRequired writes the required prop.
func (h DatePickerHandle) SetRequired(v bool) { h.handle.Set("required", v) }

// SetName writes the name prop.
func (h DatePickerHandle) SetName(v string) { h.handle.Set("name", v) }

// SetPlaceholder writes the placeholder prop.
func (h DatePickerHandle) SetPlaceholder(v string) { h.handle.Set("placeholder", v) }
