// Code generated by alacris-go from ../assets/ui/components/ui-drawer.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// DrawerTag is the name of the <ui-drawer> custom element.
const DrawerTag = "ui-drawer"

// Slots exposed by <ui-drawer>. Put one on your own markup to fill it:
//
//	<h3 slot={ DrawerSlotDefault }>
const (
	// drawer content
	DrawerSlotDefault = ""
)

// Events emitted by <ui-drawer>. Forward one to a server action with On:
//
//	Drawer(props).On(DrawerEventClose, "handler-name")
const (
	// modal dismissed; detail: { reason: 'esc' | 'scrim' }
	DrawerEventClose = "close"
	// modal enter animation finished
	DrawerEventOpened = "opened"
	// modal exit animation finished, DOM removed
	DrawerEventClosed = "closed"
)

// DrawerCloseDetail is the detail of the "close" event of <ui-drawer>.
//
// modal dismissed; detail: { reason: 'esc' | 'scrim' }
type DrawerCloseDetail struct {
	Reason any `json:"reason"`
}

// DrawerVars is the theming contract of <ui-drawer>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Drawer(props).Apply(DrawerVars, map[string]string{"--ui-drawer-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var DrawerVars = alacris.Vars(
	"--ui-drawer-bg",
	"--ui-drawer-std-bg",
	"--ui-drawer-fg",
	"--ui-drawer-width",
	"--ui-drawer-radius",
	"--ui-drawer-pad",
	"--ui-drawer-scrim",
)

// DrawerProps are the props of <ui-drawer>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type DrawerProps struct {
	// The component defaults it to false.
	Open bool

	// Variant is modal | standard.
	//
	// The component defaults it to 'modal'.
	Variant string

	// Anchor is start | end (which edge it slides from).
	//
	// The component defaults it to 'start'.
	Anchor string

	// Label is accessible name; falls back to "Navigation".
	//
	// The component defaults it to ''.
	Label string
}

// Drawer renders <ui-drawer>.
//
// <ui-drawer> — a navigation drawer, modal or standard.
//
// <ui-drawer open=${open} @close=${() => open(false)}>…nav content…</ui-drawer>
// <ui-drawer variant="standard" anchor="start" open=${open}>…</ui-drawer>
//
// Modal: a fixed overlay — scrim plus a full-height panel that slides in from
// the anchor side. Focus is trapped and page scroll locked while open. The
// PARENT owns `open`: Escape and scrim clicks emit `close` with a reason and
// the parent flips the signal. `opened`/`closed` fire after the enter/exit
// animations settle.
// Standard: an in-flow panel; the host animates its inline size open/closed —
// no scrim, no trap.
func Drawer(p DrawerProps) *alacris.Element {
	e := alacris.E(DrawerTag)
	if p.Open {
		e.Prop("open", p.Open)
	}
	if p.Variant != "" && p.Variant != "modal" {
		e.Prop("variant", p.Variant)
	}
	if p.Anchor != "" && p.Anchor != "start" {
		e.Prop("anchor", p.Anchor)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// DrawerHandle patches a rendered <ui-drawer> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with DrawerElement.
type DrawerHandle struct {
	handle live.Handle
}

// DrawerElement addresses the <ui-drawer> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	DrawerElement(c.Session, "id").SetOpen(v)
func DrawerElement(s *live.Session, id string) DrawerHandle {
	return DrawerHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h DrawerHandle) Handle() live.Handle { return h.handle }

// SetOpen writes the open prop.
func (h DrawerHandle) SetOpen(v bool) { h.handle.Set("open", v) }

// SetVariant writes the variant prop.
func (h DrawerHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetAnchor writes the anchor prop.
func (h DrawerHandle) SetAnchor(v string) { h.handle.Set("anchor", v) }

// SetLabel writes the label prop.
func (h DrawerHandle) SetLabel(v string) { h.handle.Set("label", v) }
