// Code generated by alacris-go from ../assets/ui/components/ui-fab.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// FabTag is the name of the <ui-fab> custom element.
const FabTag = "ui-fab"

// Slots exposed by <ui-fab>. Put one on your own markup to fill it:
//
//	<h3 slot={ FabSlotDefault }>
const (
	// custom icon content when `icon` is empty
	FabSlotDefault = ""
)

// FabVars is the theming contract of <ui-fab>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Fab(props).Apply(FabVars, map[string]string{"--ui-fab-size-sm": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var FabVars = alacris.Vars(
	"--ui-fab-size-sm",
	"--ui-fab-size-md",
	"--ui-fab-size-lg",
	"--ui-fab-radius-sm",
	"--ui-fab-radius-md",
	"--ui-fab-radius-lg",
	"--ui-fab-font",
	"--ui-fab-tracking",
	"--ui-fab-primary-bg",
	"--ui-fab-primary-fg",
	"--ui-fab-secondary-bg",
	"--ui-fab-secondary-fg",
	"--ui-fab-tertiary-bg",
	"--ui-fab-tertiary-fg",
	"--ui-fab-surface-bg",
	"--ui-fab-surface-fg",
)

// FabProps are the props of <ui-fab>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type FabProps struct {
	// Icon is registry icon name (or slot custom content).
	//
	// The component defaults it to ''.
	Icon string

	// Label is extended-FAB text; always used as aria-label (falls back to the icon name when empty).
	//
	// The component defaults it to ''.
	Label string

	// Variant is primary | secondary | tertiary | surface.
	//
	// The component defaults it to 'primary'.
	Variant string

	// Size is sm (40px) | md (56px) | lg (96px).
	//
	// The component defaults it to 'md'.
	Size string

	// The component defaults it to false.
	Disabled bool
}

// Fab renders <ui-fab>.
//
// <ui-fab> — the Material floating action button, regular and extended.
//
// A non-empty `label` renders the extended FAB (icon + text) and is always the
// accessible name, extended or not.
func Fab(p FabProps) *alacris.Element {
	e := alacris.E(FabTag)
	if p.Icon != "" {
		e.Prop("icon", p.Icon)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Variant != "" && p.Variant != "primary" {
		e.Prop("variant", p.Variant)
	}
	if p.Size != "" && p.Size != "md" {
		e.Prop("size", p.Size)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	return e
}

// FabHandle patches a rendered <ui-fab> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with FabElement.
type FabHandle struct {
	handle live.Handle
}

// FabElement addresses the <ui-fab> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	FabElement(c.Session, "id").SetIcon(v)
func FabElement(s *live.Session, id string) FabHandle {
	return FabHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h FabHandle) Handle() live.Handle { return h.handle }

// SetIcon writes the icon prop.
func (h FabHandle) SetIcon(v string) { h.handle.Set("icon", v) }

// SetLabel writes the label prop.
func (h FabHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetVariant writes the variant prop.
func (h FabHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetSize writes the size prop.
func (h FabHandle) SetSize(v string) { h.handle.Set("size", v) }

// SetDisabled writes the disabled prop.
func (h FabHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }
