// Code generated by alacris-go from ../assets/ui/components/ui-fab-menu.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// FabMenuTag is the name of the <ui-fab-menu> custom element.
const FabMenuTag = "ui-fab-menu"

// Slots exposed by <ui-fab-menu>. Put one on your own markup to fill it:
//
//	<h3 slot={ FabMenuSlotTrigger }>
const (
	// the <ui-fab> that toggles the menu
	FabMenuSlotTrigger = "trigger"
	// related <ui-fab> actions
	FabMenuSlotDefault = ""
)

// Events emitted by <ui-fab-menu>. Forward one to a server action with On:
//
//	FabMenu(props).On(FabMenuEventOpen, "handler-name")
const (
	// menu visible (after the enter animation)
	FabMenuEventOpen = "open"
	// menu removed (after the exit animation)
	FabMenuEventClose = "close"
)

// FabMenuVars is the theming contract of <ui-fab-menu>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	FabMenu(props).Apply(FabMenuVars, map[string]string{"--ui-fab-menu-gap": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var FabMenuVars = alacris.Vars(
	"--ui-fab-menu-gap",
)

// FabMenuProps are the props of <ui-fab-menu>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type FabMenuProps struct {
	// The component defaults it to false.
	Open bool

	// Label is accessible name for the action list.
	//
	// The component defaults it to ''.
	Label string
}

// FabMenu renders <ui-fab-menu>.
//
// <ui-fab-menu> — a Material FAB menu: a trigger FAB that expands related
// actions stacked above it.
//
// <ui-fab-menu>
// <ui-fab slot="trigger" icon="add"></ui-fab>
// <ui-fab icon="edit" label="Edit" size="sm"></ui-fab>
// <ui-fab icon="send" label="Send" size="sm"></ui-fab>
// </ui-fab-menu>
//
// The PARENT may pass `open`; clicking the trigger toggles it and emits
// `open`/`close`. Related actions are a disclosure of buttons (not a menu
// widget) so slotted `<ui-fab>`s keep their native button semantics.
// Escape closes and returns focus to the trigger.
func FabMenu(p FabMenuProps) *alacris.Element {
	e := alacris.E(FabMenuTag)
	if p.Open {
		e.Prop("open", p.Open)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// FabMenuHandle patches a rendered <ui-fab-menu> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with FabMenuElement.
type FabMenuHandle struct {
	handle live.Handle
}

// FabMenuElement addresses the <ui-fab-menu> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	FabMenuElement(c.Session, "id").SetOpen(v)
func FabMenuElement(s *live.Session, id string) FabMenuHandle {
	return FabMenuHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h FabMenuHandle) Handle() live.Handle { return h.handle }

// SetOpen writes the open prop.
func (h FabMenuHandle) SetOpen(v bool) { h.handle.Set("open", v) }

// SetLabel writes the label prop.
func (h FabMenuHandle) SetLabel(v string) { h.handle.Set("label", v) }
