// Code generated by alacris-go from ../assets/ui/components/ui-icon.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// IconTag is the name of the <ui-icon> custom element.
const IconTag = "ui-icon"

// Slots exposed by <ui-icon>. Put one on your own markup to fill it:
//
//	<h3 slot={ IconSlotDefault }>
const (
	// a custom <svg> when no name is given
	IconSlotDefault = ""
)

// IconVars is the theming contract of <ui-icon>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Icon(props).Apply(IconVars, map[string]string{"--ui-icon-size": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var IconVars = alacris.Vars(
	"--ui-icon-size",
)

// IconProps are the props of <ui-icon>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type IconProps struct {
	// Name is registry name (see util/icons.js); empty renders the slot.
	//
	// The component defaults it to ''.
	Name string

	// Label is accessible name; empty marks the icon decorative.
	//
	// The component defaults it to ''.
	Label string

	// Size is CSS length; overrides --ui-icon-size for this element.
	//
	// The component defaults it to ''.
	Size string
}

// Icon renders <ui-icon>.
//
// <ui-icon> — an icon from the registry, or any slotted SVG.
func Icon(p IconProps) *alacris.Element {
	e := alacris.E(IconTag)
	if p.Name != "" {
		e.Prop("name", p.Name)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Size != "" {
		e.Prop("size", p.Size)
	}
	return e
}

// IconHandle patches a rendered <ui-icon> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with IconElement.
type IconHandle struct {
	handle live.Handle
}

// IconElement addresses the <ui-icon> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	IconElement(c.Session, "id").SetName(v)
func IconElement(s *live.Session, id string) IconHandle {
	return IconHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h IconHandle) Handle() live.Handle { return h.handle }

// SetName writes the name prop.
func (h IconHandle) SetName(v string) { h.handle.Set("name", v) }

// SetLabel writes the label prop.
func (h IconHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetSize writes the size prop.
func (h IconHandle) SetSize(v string) { h.handle.Set("size", v) }
