// Code generated by alacris-go from ../assets/ui/components/ui-icon-button.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// IconButtonTag is the name of the <ui-icon-button> custom element.
const IconButtonTag = "ui-icon-button"

// Slots exposed by <ui-icon-button>. Put one on your own markup to fill it:
//
//	<h3 slot={ IconButtonSlotDefault }>
const (
	// custom icon content when `icon` is empty
	IconButtonSlotDefault = ""
)

// Events emitted by <ui-icon-button>. Forward one to a server action with On:
//
//	IconButton(props).On(IconButtonEventChange, "handler-name")
const (
	// toggle flipped; detail: { selected }
	IconButtonEventChange = "change"
)

// IconButtonChangeDetail is the detail of the "change" event of <ui-icon-button>.
//
// toggle flipped; detail: { selected }
type IconButtonChangeDetail struct {
	Selected any `json:"selected"`
}

// IconButtonVars is the theming contract of <ui-icon-button>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	IconButton(props).Apply(IconButtonVars, map[string]string{"--ui-icon-button-size": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var IconButtonVars = alacris.Vars(
	"--ui-icon-button-size",
	"--ui-icon-button-radius",
	"--ui-icon-button-fg",
	"--ui-icon-button-selected-fg",
	"--ui-icon-button-filled-bg",
	"--ui-icon-button-filled-fg",
	"--ui-icon-button-tonal-bg",
	"--ui-icon-button-tonal-fg",
	"--ui-icon-button-outline-color",
)

// IconButtonProps are the props of <ui-icon-button>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type IconButtonProps struct {
	// Icon is registry icon name (or slot an <ui-icon>).
	//
	// The component defaults it to ''.
	Icon string

	// SelectedIcon is icon while selected (toggle mode; defaults to `icon`).
	//
	// The component defaults it to ''.
	SelectedIcon string

	// Label is REQUIRED accessible name.
	//
	// The component defaults it to ''.
	Label string

	// Variant is standard | filled | tonal | outlined.
	//
	// The component defaults it to 'standard'.
	Variant string

	// Toggle is makes it a pressed-state toggle.
	//
	// The component defaults it to false.
	Toggle bool

	// Selected is toggle state.
	//
	// The component defaults it to false.
	Selected bool

	// The component defaults it to false.
	Disabled bool
}

// IconButton renders <ui-icon-button>.
//
// <ui-icon-button> — a 40px icon button, optionally a toggle.
func IconButton(p IconButtonProps) *alacris.Element {
	e := alacris.E(IconButtonTag)
	if p.Icon != "" {
		e.Prop("icon", p.Icon)
	}
	if p.SelectedIcon != "" {
		e.Prop("selectedIcon", p.SelectedIcon)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Variant != "" && p.Variant != "standard" {
		e.Prop("variant", p.Variant)
	}
	if p.Toggle {
		e.Prop("toggle", p.Toggle)
	}
	if p.Selected {
		e.Prop("selected", p.Selected)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	return e
}

// IconButtonHandle patches a rendered <ui-icon-button> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with IconButtonElement.
type IconButtonHandle struct {
	handle live.Handle
}

// IconButtonElement addresses the <ui-icon-button> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	IconButtonElement(c.Session, "id").SetIcon(v)
func IconButtonElement(s *live.Session, id string) IconButtonHandle {
	return IconButtonHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h IconButtonHandle) Handle() live.Handle { return h.handle }

// SetIcon writes the icon prop.
func (h IconButtonHandle) SetIcon(v string) { h.handle.Set("icon", v) }

// SetSelectedIcon writes the selectedIcon prop.
func (h IconButtonHandle) SetSelectedIcon(v string) { h.handle.Set("selectedIcon", v) }

// SetLabel writes the label prop.
func (h IconButtonHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetVariant writes the variant prop.
func (h IconButtonHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetToggle writes the toggle prop.
func (h IconButtonHandle) SetToggle(v bool) { h.handle.Set("toggle", v) }

// SetSelected writes the selected prop.
func (h IconButtonHandle) SetSelected(v bool) { h.handle.Set("selected", v) }

// SetDisabled writes the disabled prop.
func (h IconButtonHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }
