// Code generated by alacris-go from ../assets/ui/components/ui-list-item.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// ListItemTag is the name of the <ui-list-item> custom element.
const ListItemTag = "ui-list-item"

// Slots exposed by <ui-list-item>. Put one on your own markup to fill it:
//
//	<h3 slot={ ListItemSlotDefault }>
const (
	// headline content when the prop is empty
	ListItemSlotDefault = ""
	// icon / avatar / checkbox
	ListItemSlotLeading = "leading"
	// secondary line when the prop is empty
	ListItemSlotSupporting = "supporting"
	// trailing meta text or icon
	ListItemSlotTrailing = "trailing"
)

// ListItemVars is the theming contract of <ui-list-item>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	ListItem(props).Apply(ListItemVars, map[string]string{"--ui-list-item-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var ListItemVars = alacris.Vars(
	"--ui-list-item-height",
	"--ui-list-item-two-line-height",
	"--ui-list-item-pad-inline",
	"--ui-list-item-gap",
	"--ui-list-item-headline-fg",
	"--ui-list-item-headline-font",
	"--ui-list-item-supporting-fg",
	"--ui-list-item-supporting-font",
	"--ui-list-item-trailing-fg",
	"--ui-list-item-trailing-font",
	"--ui-list-item-selected-bg",
	"--ui-list-item-selected-fg",
)

// ListItemProps are the props of <ui-list-item>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type ListItemProps struct {
	// Headline is primary text (or use the default slot).
	//
	// The component defaults it to ''.
	Headline string

	// Supporting is secondary text (or use the supporting slot).
	//
	// The component defaults it to ''.
	Supporting string

	// Interactive is state layer + ripple + role="button".
	//
	// The component defaults it to false.
	Interactive bool

	// Href is renders the row as an <a>.
	//
	// The component defaults it to ''.
	Href string

	// Selected is secondaryContainer background.
	//
	// The component defaults it to false.
	Selected bool

	// The component defaults it to false.
	Disabled bool
}

// ListItem renders <ui-list-item>.
//
// <ui-list-item> — one row of a <ui-list>.
//
// One line (56px) by default; supplying supporting text (prop or slot) makes
// it two lines (72px). `interactive` adds button semantics, a state layer and
// a ripple; `href` renders the row as a link instead. Activation emits only
// the native (bubbling) click — no custom event.
func ListItem(p ListItemProps) *alacris.Element {
	e := alacris.E(ListItemTag)
	if p.Headline != "" {
		e.Prop("headline", p.Headline)
	}
	if p.Supporting != "" {
		e.Prop("supporting", p.Supporting)
	}
	if p.Interactive {
		e.Prop("interactive", p.Interactive)
	}
	if p.Href != "" {
		e.Prop("href", p.Href)
	}
	if p.Selected {
		e.Prop("selected", p.Selected)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	return e
}

// ListItemHandle patches a rendered <ui-list-item> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with ListItemElement.
type ListItemHandle struct {
	handle live.Handle
}

// ListItemElement addresses the <ui-list-item> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	ListItemElement(c.Session, "id").SetHeadline(v)
func ListItemElement(s *live.Session, id string) ListItemHandle {
	return ListItemHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h ListItemHandle) Handle() live.Handle { return h.handle }

// SetHeadline writes the headline prop.
func (h ListItemHandle) SetHeadline(v string) { h.handle.Set("headline", v) }

// SetSupporting writes the supporting prop.
func (h ListItemHandle) SetSupporting(v string) { h.handle.Set("supporting", v) }

// SetInteractive writes the interactive prop.
func (h ListItemHandle) SetInteractive(v bool) { h.handle.Set("interactive", v) }

// SetHref writes the href prop.
func (h ListItemHandle) SetHref(v string) { h.handle.Set("href", v) }

// SetSelected writes the selected prop.
func (h ListItemHandle) SetSelected(v bool) { h.handle.Set("selected", v) }

// SetDisabled writes the disabled prop.
func (h ListItemHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }
