// Code generated by alacris-go from ../assets/ui/components/ui-list.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// ListTag is the name of the <ui-list> custom element.
const ListTag = "ui-list"

// Slots exposed by <ui-list>. Put one on your own markup to fill it:
//
//	<h3 slot={ ListSlotDefault }>
const (
	// <ui-list-item> elements (and <ui-divider>s)
	ListSlotDefault = ""
)

// ListVars is the theming contract of <ui-list>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	List(props).Apply(ListVars, map[string]string{"--ui-list-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var ListVars = alacris.Vars(
	"--ui-list-bg",
	"--ui-list-pad-block",
)

// ListProps are the props of <ui-list>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type ListProps struct {
	// Label is accessible name for the list.
	//
	// The component defaults it to ''.
	Label string
}

// List renders <ui-list>.
//
// <ui-list> — a Material list container for <ui-list-item> children.
//
// role="list" on the host; items carry role="listitem".
func List(p ListProps) *alacris.Element {
	e := alacris.E(ListTag)
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// ListHandle patches a rendered <ui-list> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with ListElement.
type ListHandle struct {
	handle live.Handle
}

// ListElement addresses the <ui-list> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	ListElement(c.Session, "id").SetLabel(v)
func ListElement(s *live.Session, id string) ListHandle {
	return ListHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h ListHandle) Handle() live.Handle { return h.handle }

// SetLabel writes the label prop.
func (h ListHandle) SetLabel(v string) { h.handle.Set("label", v) }
