// Code generated by alacris-go from ../assets/ui/components/ui-loading-indicator.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// LoadingIndicatorTag is the name of the <ui-loading-indicator> custom element.
const LoadingIndicatorTag = "ui-loading-indicator"

// LoadingIndicatorVars is the theming contract of <ui-loading-indicator>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	LoadingIndicator(props).Apply(LoadingIndicatorVars, map[string]string{"--ui-loading-indicator-size": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var LoadingIndicatorVars = alacris.Vars(
	"--ui-loading-indicator-size",
	"--ui-loading-indicator-gap",
	"--ui-loading-indicator-dot",
	"--ui-loading-indicator-contained-bg",
	"--ui-loading-indicator-contained-pad",
	"--ui-loading-indicator-contained-radius",
)

// LoadingIndicatorProps are the props of <ui-loading-indicator>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type LoadingIndicatorProps struct {
	// Variant is uncontained | contained.
	//
	// The component defaults it to 'uncontained'.
	Variant string

	// Label is accessible name.
	//
	// The component defaults it to 'Loading'.
	Label string
}

// LoadingIndicator renders <ui-loading-indicator>.
//
// <ui-loading-indicator> — the Material loading indicator: morphing dots,
// distinct from determinate <ui-progress> / <ui-spinner>.
//
// <ui-loading-indicator label="Loading"></ui-loading-indicator>
// <ui-loading-indicator variant="contained"></ui-loading-indicator>
//
// Always indeterminate. `contained` draws the dots on a tonal pill.
func LoadingIndicator(p LoadingIndicatorProps) *alacris.Element {
	e := alacris.E(LoadingIndicatorTag)
	if p.Variant != "" && p.Variant != "uncontained" {
		e.Prop("variant", p.Variant)
	}
	if p.Label != "" && p.Label != "Loading" {
		e.Prop("label", p.Label)
	}
	return e
}

// LoadingIndicatorHandle patches a rendered <ui-loading-indicator> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with LoadingIndicatorElement.
type LoadingIndicatorHandle struct {
	handle live.Handle
}

// LoadingIndicatorElement addresses the <ui-loading-indicator> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	LoadingIndicatorElement(c.Session, "id").SetVariant(v)
func LoadingIndicatorElement(s *live.Session, id string) LoadingIndicatorHandle {
	return LoadingIndicatorHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h LoadingIndicatorHandle) Handle() live.Handle { return h.handle }

// SetVariant writes the variant prop.
func (h LoadingIndicatorHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetLabel writes the label prop.
func (h LoadingIndicatorHandle) SetLabel(v string) { h.handle.Set("label", v) }
