// Code generated by alacris-go from ../assets/ui/components/ui-menu.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// MenuTag is the name of the <ui-menu> custom element.
const MenuTag = "ui-menu"

// Slots exposed by <ui-menu>. Put one on your own markup to fill it:
//
//	<h3 slot={ MenuSlotAnchor }>
const (
	// the trigger element
	MenuSlotAnchor = "anchor"
	// <ui-menu-item> children
	MenuSlotDefault = ""
)

// Events emitted by <ui-menu>. Forward one to a server action with On:
//
//	Menu(props).On(MenuEventSelect, "handler-name")
const (
	// an item was chosen; detail: { value }
	MenuEventSelect = "select"
	// panel visible (after the enter animation); does not bubble
	MenuEventOpen = "open"
	// panel removed (after the exit animation); does not bubble
	MenuEventClose = "close"
)

// MenuSelectDetail is the detail of the "select" event of <ui-menu>.
//
// an item was chosen; detail: { value }
type MenuSelectDetail struct {
	Value any `json:"value"`
}

// MenuVars is the theming contract of <ui-menu>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Menu(props).Apply(MenuVars, map[string]string{"--ui-menu-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var MenuVars = alacris.Vars(
	"--ui-menu-bg",
	"--ui-menu-radius",
	"--ui-menu-min-width",
	"--ui-menu-max-width",
	"--ui-menu-elevation",
)

// MenuProps are the props of <ui-menu>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type MenuProps struct {
	// The component defaults it to false.
	Open bool

	// Placement is side[-alignment] (see util/position.js).
	//
	// The component defaults it to 'bottom-start'.
	Placement string
}

// Menu renders <ui-menu>.
//
// <ui-menu> — a menu anchored to a slotted trigger.
//
// <ui-menu placement="bottom-start" @select=${(e) => ...}>
// <ui-icon-button slot="anchor" icon="more-vert" label="More"></ui-icon-button>
// <ui-menu-item value="edit" icon="edit">Edit</ui-menu-item>
// <ui-menu-item value="delete" icon="delete" danger>Delete</ui-menu-item>
// </ui-menu>
//
// The "anchor" slot renders inline; clicking it toggles the menu. The panel is
// position:fixed, anchored to the slotted trigger, flips when it would
// overflow, and stays glued through scroll/resize. While open, focus moves to
// the first item and arrows rove vertically; Escape closes and refocuses the
// anchor, Tab and outside pointerdown close. Selecting an item emits `select`
// and closes.
func Menu(p MenuProps) *alacris.Element {
	e := alacris.E(MenuTag)
	if p.Open {
		e.Prop("open", p.Open)
	}
	if p.Placement != "" && p.Placement != "bottom-start" {
		e.Prop("placement", p.Placement)
	}
	return e
}

// MenuHandle patches a rendered <ui-menu> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with MenuElement.
type MenuHandle struct {
	handle live.Handle
}

// MenuElement addresses the <ui-menu> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	MenuElement(c.Session, "id").SetOpen(v)
func MenuElement(s *live.Session, id string) MenuHandle {
	return MenuHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h MenuHandle) Handle() live.Handle { return h.handle }

// SetOpen writes the open prop.
func (h MenuHandle) SetOpen(v bool) { h.handle.Set("open", v) }

// SetPlacement writes the placement prop.
func (h MenuHandle) SetPlacement(v string) { h.handle.Set("placement", v) }
