// Code generated by alacris-go from ../assets/ui/components/ui-menu-item.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// MenuItemTag is the name of the <ui-menu-item> custom element.
const MenuItemTag = "ui-menu-item"

// Slots exposed by <ui-menu-item>. Put one on your own markup to fill it:
//
//	<h3 slot={ MenuItemSlotDefault }>
const (
	// label
	MenuItemSlotDefault = ""
	// custom leading icon when `icon` is empty
	MenuItemSlotIcon = "icon"
	// trailing hint (keyboard shortcut, badge)
	MenuItemSlotTrailing = "trailing"
)

// Events emitted by <ui-menu-item>. Forward one to a server action with On:
//
//	MenuItem(props).On(MenuItemEventUIMenuSelect, "handler-name")
const (
	// internal; detail: { value } (consumed by <ui-menu>)
	MenuItemEventUIMenuSelect = "ui-menu-select"
)

// MenuItemUIMenuSelectDetail is the detail of the "ui-menu-select" event of <ui-menu-item>.
//
// internal; detail: { value } (consumed by <ui-menu>)
type MenuItemUIMenuSelectDetail struct {
	Value any `json:"value"`
}

// MenuItemVars is the theming contract of <ui-menu-item>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	MenuItem(props).Apply(MenuItemVars, map[string]string{"--ui-menu-item-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var MenuItemVars = alacris.Vars(
	"--ui-menu-item-height",
	"--ui-menu-item-pad-inline",
	"--ui-menu-item-gap",
	"--ui-menu-item-font",
	"--ui-menu-item-tracking",
	"--ui-menu-item-fg",
	"--ui-menu-item-icon-fg",
	"--ui-menu-item-trailing-fg",
	"--ui-menu-item-danger-fg",
)

// MenuItemProps are the props of <ui-menu-item>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type MenuItemProps struct {
	// Value is reported in the menu's `select` detail.
	//
	// The component defaults it to ''.
	Value string

	// Icon is leading registry icon.
	//
	// The component defaults it to ''.
	Icon string

	// The component defaults it to false.
	Disabled bool

	// Danger is error color for destructive actions.
	//
	// The component defaults it to false.
	Danger bool
}

// MenuItem renders <ui-menu-item>.
//
// <ui-menu-item> — one action inside <ui-menu>.
//
// The host carries the `menuitem` semantics so the menu's roving tabindex can
// manage it directly in the light DOM.
func MenuItem(p MenuItemProps) *alacris.Element {
	e := alacris.E(MenuItemTag)
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Icon != "" {
		e.Prop("icon", p.Icon)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Danger {
		e.Prop("danger", p.Danger)
	}
	return e
}

// MenuItemHandle patches a rendered <ui-menu-item> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with MenuItemElement.
type MenuItemHandle struct {
	handle live.Handle
}

// MenuItemElement addresses the <ui-menu-item> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	MenuItemElement(c.Session, "id").SetValue(v)
func MenuItemElement(s *live.Session, id string) MenuItemHandle {
	return MenuItemHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h MenuItemHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h MenuItemHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetIcon writes the icon prop.
func (h MenuItemHandle) SetIcon(v string) { h.handle.Set("icon", v) }

// SetDisabled writes the disabled prop.
func (h MenuItemHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetDanger writes the danger prop.
func (h MenuItemHandle) SetDanger(v bool) { h.handle.Set("danger", v) }
