// Code generated by alacris-go from ../assets/ui/components/ui-nav-item.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// NavItemTag is the name of the <ui-nav-item> custom element.
const NavItemTag = "ui-nav-item"

// Slots exposed by <ui-nav-item>. Put one on your own markup to fill it:
//
//	<h3 slot={ NavItemSlotIcon }>
const (
	// custom icon content when `icon` is empty
	NavItemSlotIcon = "icon"
)

// Events emitted by <ui-nav-item>. Forward one to a server action with On:
//
//	NavItem(props).On(NavItemEventUINavSelect, "handler-name")
const (
	// activated; detail: { value }
	NavItemEventUINavSelect = "ui-nav-select"
)

// NavItemUINavSelectDetail is the detail of the "ui-nav-select" event of <ui-nav-item>.
//
// activated; detail: { value }
type NavItemUINavSelectDetail struct {
	Value any `json:"value"`
}

// NavItemVars is the theming contract of <ui-nav-item>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	NavItem(props).Apply(NavItemVars, map[string]string{"--ui-nav-item-pill-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var NavItemVars = alacris.Vars(
	"--ui-nav-item-pill-bg",
	"--ui-nav-item-icon-fg",
	"--ui-nav-item-icon-fg-active",
	"--ui-nav-item-label-fg",
	"--ui-nav-item-label-fg-active",
	"--ui-nav-item-font",
	"--ui-nav-item-tracking",
)

// NavItemProps are the props of <ui-nav-item>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type NavItemProps struct {
	// Value is REQUIRED identity of the destination.
	//
	// The component defaults it to ''.
	Value string

	// Icon is registry icon name.
	//
	// The component defaults it to ''.
	Icon string

	// ActiveIcon is icon while selected (defaults to `icon`).
	//
	// The component defaults it to ''.
	ActiveIcon string

	// Label is visible label (and the accessible name).
	//
	// The component defaults it to ''.
	Label string

	// Selected is managed by <ui-bottom-nav>.
	//
	// The component defaults it to false.
	Selected bool

	// The component defaults it to false.
	Disabled bool
}

// NavItem renders <ui-nav-item>.
//
// <ui-nav-item> — one destination inside <ui-bottom-nav> or <ui-nav-rail>.
//
// Focus: the host is the roving tab stop (<ui-bottom-nav> assigns tabindex);
// focus is forwarded to the inner button so Enter/Space activate natively.
func NavItem(p NavItemProps) *alacris.Element {
	e := alacris.E(NavItemTag)
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Icon != "" {
		e.Prop("icon", p.Icon)
	}
	if p.ActiveIcon != "" {
		e.Prop("activeIcon", p.ActiveIcon)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Selected {
		e.Prop("selected", p.Selected)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	return e
}

// NavItemHandle patches a rendered <ui-nav-item> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with NavItemElement.
type NavItemHandle struct {
	handle live.Handle
}

// NavItemElement addresses the <ui-nav-item> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	NavItemElement(c.Session, "id").SetValue(v)
func NavItemElement(s *live.Session, id string) NavItemHandle {
	return NavItemHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h NavItemHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h NavItemHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetIcon writes the icon prop.
func (h NavItemHandle) SetIcon(v string) { h.handle.Set("icon", v) }

// SetActiveIcon writes the activeIcon prop.
func (h NavItemHandle) SetActiveIcon(v string) { h.handle.Set("activeIcon", v) }

// SetLabel writes the label prop.
func (h NavItemHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetSelected writes the selected prop.
func (h NavItemHandle) SetSelected(v bool) { h.handle.Set("selected", v) }

// SetDisabled writes the disabled prop.
func (h NavItemHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }
