// Code generated by alacris-go from ../assets/ui/components/ui-nav-rail.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// NavRailTag is the name of the <ui-nav-rail> custom element.
const NavRailTag = "ui-nav-rail"

// Slots exposed by <ui-nav-rail>. Put one on your own markup to fill it:
//
//	<h3 slot={ NavRailSlotMenu }>
const (
	// optional leading icon button (typically "menu")
	NavRailSlotMenu = "menu"
	// optional FAB above the destinations
	NavRailSlotFab = "fab"
	// <ui-nav-item> children
	NavRailSlotDefault = ""
)

// Events emitted by <ui-nav-rail>. Forward one to a server action with On:
//
//	NavRail(props).On(NavRailEventChange, "handler-name")
const (
	// a destination was chosen; detail: { value }
	NavRailEventChange = "change"
)

// NavRailChangeDetail is the detail of the "change" event of <ui-nav-rail>.
//
// a destination was chosen; detail: { value }
type NavRailChangeDetail struct {
	Value any `json:"value"`
}

// NavRailVars is the theming contract of <ui-nav-rail>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	NavRail(props).Apply(NavRailVars, map[string]string{"--ui-nav-rail-width": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var NavRailVars = alacris.Vars(
	"--ui-nav-rail-width",
	"--ui-nav-rail-bg",
	"--ui-nav-rail-pad",
)

// NavRailProps are the props of <ui-nav-rail>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type NavRailProps struct {
	// Value is the selected item's `value`.
	//
	// The component defaults it to ''.
	Value string

	// Label is accessible name of the <nav>.
	//
	// The component defaults it to ''.
	Label string

	// Align is start | center | end (where destinations sit).
	//
	// The component defaults it to 'start'.
	Align string
}

// NavRail renders <ui-nav-rail>.
//
// <ui-nav-rail> — the Material navigation rail.
//
// <ui-nav-rail value=${route} @change=${(e) => route(e.detail.value)}>
// <ui-fab slot="fab" icon="add"></ui-fab>
// <ui-nav-item value="home" icon="home" label="Home"></ui-nav-item>
// <ui-nav-item value="search" icon="search" label="Search"></ui-nav-item>
// </ui-nav-rail>
//
// A compact vertical destination list (the large-screen counterpart of
// <ui-bottom-nav>). Reuses <ui-nav-item>. The host flows with the page —
// pin it with position: sticky/fixed yourself.
func NavRail(p NavRailProps) *alacris.Element {
	e := alacris.E(NavRailTag)
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Align != "" && p.Align != "start" {
		e.Prop("align", p.Align)
	}
	return e
}

// NavRailHandle patches a rendered <ui-nav-rail> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with NavRailElement.
type NavRailHandle struct {
	handle live.Handle
}

// NavRailElement addresses the <ui-nav-rail> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	NavRailElement(c.Session, "id").SetValue(v)
func NavRailElement(s *live.Session, id string) NavRailHandle {
	return NavRailHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h NavRailHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h NavRailHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetLabel writes the label prop.
func (h NavRailHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetAlign writes the align prop.
func (h NavRailHandle) SetAlign(v string) { h.handle.Set("align", v) }
