// Code generated by alacris-go from ../assets/ui/components/ui-option.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// OptionTag is the name of the <ui-option> custom element.
const OptionTag = "ui-option"

// Slots exposed by <ui-option>. Put one on your own markup to fill it:
//
//	<h3 slot={ OptionSlotDefault }>
const (
	// the visible label (also used by the select's field text)
	OptionSlotDefault = ""
)

// OptionVars is the theming contract of <ui-option>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Option(props).Apply(OptionVars, map[string]string{"--ui-option-fg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var OptionVars = alacris.Vars(
	"--ui-option-fg",
	"--ui-option-selected-bg",
	"--ui-option-selected-fg",
	"--ui-option-font",
	"--ui-option-height",
)

// OptionProps are the props of <ui-option>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type OptionProps struct {
	// Value is the value this option contributes (required).
	//
	// The component defaults it to ''.
	Value string

	// The component defaults it to false.
	Disabled bool

	// Selected is set by the owning select; mirrors aria-selected.
	//
	// The component defaults it to false.
	Selected bool

	// Active is set by the owning select while keyboard-active.
	//
	// The component defaults it to false.
	Active bool
}

// Option renders <ui-option>.
//
// <ui-option> — one choice inside <ui-select>.
//
// The host itself is the option (role="option"): it lives in the select's
// light DOM and is projected into the select's listbox panel. The select
// drives `selected`/`active` (via their attributes) and handles activation;
// the option only renders itself and its state layer.
func Option(p OptionProps) *alacris.Element {
	e := alacris.E(OptionTag)
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Selected {
		e.Prop("selected", p.Selected)
	}
	if p.Active {
		e.Prop("active", p.Active)
	}
	return e
}

// OptionHandle patches a rendered <ui-option> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with OptionElement.
type OptionHandle struct {
	handle live.Handle
}

// OptionElement addresses the <ui-option> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	OptionElement(c.Session, "id").SetValue(v)
func OptionElement(s *live.Session, id string) OptionHandle {
	return OptionHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h OptionHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h OptionHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetDisabled writes the disabled prop.
func (h OptionHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetSelected writes the selected prop.
func (h OptionHandle) SetSelected(v bool) { h.handle.Set("selected", v) }

// SetActive writes the active prop.
func (h OptionHandle) SetActive(v bool) { h.handle.Set("active", v) }
