// Code generated by alacris-go from ../assets/ui/components/ui-pagination.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// PaginationTag is the name of the <ui-pagination> custom element.
const PaginationTag = "ui-pagination"

// Events emitted by <ui-pagination>. Forward one to a server action with On:
//
//	Pagination(props).On(PaginationEventChange, "handler-name")
const (
	// a page was chosen (numbers, prev, next); detail: { page }
	PaginationEventChange = "change"
)

// PaginationChangeDetail is the detail of the "change" event of <ui-pagination>.
//
// a page was chosen (numbers, prev, next); detail: { page }
type PaginationChangeDetail struct {
	Page any `json:"page"`
}

// PaginationVars is the theming contract of <ui-pagination>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Pagination(props).Apply(PaginationVars, map[string]string{"--ui-pagination-size": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var PaginationVars = alacris.Vars(
	"--ui-pagination-size",
	"--ui-pagination-radius",
	"--ui-pagination-fg",
	"--ui-pagination-current-bg",
	"--ui-pagination-current-fg",
	"--ui-pagination-font",
	"--ui-pagination-tracking",
)

// PaginationProps are the props of <ui-pagination>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type PaginationProps struct {
	// Page is current page (1-based).
	//
	// The component defaults it to 1.
	Page float64

	// Count is total pages.
	//
	// The component defaults it to 1.
	Count float64

	// Siblings is pages shown on each side of the current page.
	//
	// The component defaults it to 1.
	Siblings float64

	// Boundaries is pages always shown at each end.
	//
	// The component defaults it to 1.
	Boundaries float64

	// The component defaults it to false.
	Disabled bool

	// Label is accessible name of the <nav>.
	//
	// The component defaults it to 'Pagination'.
	Label string
}

// Pagination renders <ui-pagination>.
//
// <ui-pagination> — page navigation with sibling/boundary windows.
//
// <ui-pagination count="10" page=${page} @change=${(e) => page(e.detail.page)}>
// </ui-pagination>
func Pagination(p PaginationProps) *alacris.Element {
	e := alacris.E(PaginationTag)
	if p.Page != 0 && p.Page != 1 {
		e.Prop("page", p.Page)
	}
	if p.Count != 0 && p.Count != 1 {
		e.Prop("count", p.Count)
	}
	if p.Siblings != 0 && p.Siblings != 1 {
		e.Prop("siblings", p.Siblings)
	}
	if p.Boundaries != 0 && p.Boundaries != 1 {
		e.Prop("boundaries", p.Boundaries)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Label != "" && p.Label != "Pagination" {
		e.Prop("label", p.Label)
	}
	return e
}

// PaginationHandle patches a rendered <ui-pagination> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with PaginationElement.
type PaginationHandle struct {
	handle live.Handle
}

// PaginationElement addresses the <ui-pagination> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	PaginationElement(c.Session, "id").SetPage(v)
func PaginationElement(s *live.Session, id string) PaginationHandle {
	return PaginationHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h PaginationHandle) Handle() live.Handle { return h.handle }

// SetPage writes the page prop.
func (h PaginationHandle) SetPage(v float64) { h.handle.Set("page", v) }

// SetCount writes the count prop.
func (h PaginationHandle) SetCount(v float64) { h.handle.Set("count", v) }

// SetSiblings writes the siblings prop.
func (h PaginationHandle) SetSiblings(v float64) { h.handle.Set("siblings", v) }

// SetBoundaries writes the boundaries prop.
func (h PaginationHandle) SetBoundaries(v float64) { h.handle.Set("boundaries", v) }

// SetDisabled writes the disabled prop.
func (h PaginationHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetLabel writes the label prop.
func (h PaginationHandle) SetLabel(v string) { h.handle.Set("label", v) }
