// Code generated by alacris-go from ../assets/ui/components/ui-progress.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// ProgressTag is the name of the <ui-progress> custom element.
const ProgressTag = "ui-progress"

// ProgressVars is the theming contract of <ui-progress>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Progress(props).Apply(ProgressVars, map[string]string{"--ui-progress-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var ProgressVars = alacris.Vars(
	"--ui-progress-height",
	"--ui-progress-radius",
	"--ui-progress-track-bg",
	"--ui-progress-bar-bg",
)

// ProgressProps are the props of <ui-progress>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type ProgressProps struct {
	// Value is current value; -1 (any negative) = indeterminate.
	//
	// The component defaults it to -1.
	Value float64

	// Max is value scale.
	//
	// The component defaults it to 100.
	Max float64

	// Label is accessible name (aria-label on the progressbar).
	//
	// The component defaults it to ''.
	Label string
}

// Progress renders <ui-progress>.
//
// <ui-progress> — Material linear progress.
//
// <ui-progress label="Upload" value=${pct}></ui-progress>   determinate
// <ui-progress label="Loading"></ui-progress>               indeterminate
//
// The determinate width rides a custom property bound from the template
// (`--ui-progress-pct`), so a value change is one property write. The
// indeterminate mode is the Material two-bar translate/scale loop, written as
// CSS keyframes; its cycle length derives from the motion tokens so a theme's
// motion scale slows or stops it with everything else.
func Progress(p ProgressProps) *alacris.Element {
	e := alacris.E(ProgressTag)
	if p.Value != 0 && p.Value != -1 {
		e.Prop("value", p.Value)
	}
	if p.Max != 0 && p.Max != 100 {
		e.Prop("max", p.Max)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// ProgressHandle patches a rendered <ui-progress> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with ProgressElement.
type ProgressHandle struct {
	handle live.Handle
}

// ProgressElement addresses the <ui-progress> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	ProgressElement(c.Session, "id").SetValue(v)
func ProgressElement(s *live.Session, id string) ProgressHandle {
	return ProgressHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h ProgressHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h ProgressHandle) SetValue(v float64) { h.handle.Set("value", v) }

// SetMax writes the max prop.
func (h ProgressHandle) SetMax(v float64) { h.handle.Set("max", v) }

// SetLabel writes the label prop.
func (h ProgressHandle) SetLabel(v string) { h.handle.Set("label", v) }
