// Code generated by alacris-go from ../assets/ui/components/ui-radio.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// RadioTag is the name of the <ui-radio> custom element.
const RadioTag = "ui-radio"

// Events emitted by <ui-radio>. Forward one to a server action with On:
//
//	Radio(props).On(RadioEventUIRadioSelect, "handler-name")
const (
	// pressed; detail: { value } (consumed by ui-radio-group)
	RadioEventUIRadioSelect = "ui-radio-select"
)

// RadioUIRadioSelectDetail is the detail of the "ui-radio-select" event of <ui-radio>.
//
// pressed; detail: { value } (consumed by ui-radio-group)
type RadioUIRadioSelectDetail struct {
	Value any `json:"value"`
}

// RadioVars is the theming contract of <ui-radio>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Radio(props).Apply(RadioVars, map[string]string{"--ui-radio-target": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var RadioVars = alacris.Vars(
	"--ui-radio-target",
	"--ui-radio-circle-size",
	"--ui-radio-outline-color",
	"--ui-radio-checked-color",
	"--ui-radio-label-fg",
)

// RadioProps are the props of <ui-radio>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type RadioProps struct {
	// Value is REQUIRED identity within the group.
	//
	// The component defaults it to ''.
	Value string

	// Checked is set by the owning group.
	//
	// The component defaults it to false.
	Checked bool

	// The component defaults it to false.
	Disabled bool

	// Label is visible label; also the accessible name. Empty leaves the control unnamed (authoring error).
	//
	// The component defaults it to ''.
	Label string
}

// Radio renders <ui-radio>.
//
// <ui-radio> — one Material radio button, managed by <ui-radio-group>.
//
// The interactive element is a native <button role="radio"> on a 40px touch
// target. The radio never checks itself: it emits `ui-radio-select` and the
// owning group sets `checked` back down and roves the host's tabindex (the
// host forwards focus to the inner button).
func Radio(p RadioProps) *alacris.Element {
	e := alacris.E(RadioTag)
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Checked {
		e.Prop("checked", p.Checked)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// RadioHandle patches a rendered <ui-radio> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with RadioElement.
type RadioHandle struct {
	handle live.Handle
}

// RadioElement addresses the <ui-radio> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	RadioElement(c.Session, "id").SetValue(v)
func RadioElement(s *live.Session, id string) RadioHandle {
	return RadioHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h RadioHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h RadioHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetChecked writes the checked prop.
func (h RadioHandle) SetChecked(v bool) { h.handle.Set("checked", v) }

// SetDisabled writes the disabled prop.
func (h RadioHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetLabel writes the label prop.
func (h RadioHandle) SetLabel(v string) { h.handle.Set("label", v) }
