// Code generated by alacris-go from ../assets/ui/components/ui-rating.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// RatingTag is the name of the <ui-rating> custom element.
const RatingTag = "ui-rating"

// Events emitted by <ui-rating>. Forward one to a server action with On:
//
//	Rating(props).On(RatingEventChange, "handler-name")
const (
	// committed; detail: { value }
	RatingEventChange = "change"
)

// RatingChangeDetail is the detail of the "change" event of <ui-rating>.
//
// committed; detail: { value }
type RatingChangeDetail struct {
	Value any `json:"value"`
}

// RatingVars is the theming contract of <ui-rating>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Rating(props).Apply(RatingVars, map[string]string{"--ui-rating-active-fg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var RatingVars = alacris.Vars(
	"--ui-rating-active-fg",
	"--ui-rating-empty-fg",
	"--ui-rating-gap",
)

// RatingProps are the props of <ui-rating>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type RatingProps struct {
	// The component defaults it to 0.
	Value float64

	// The component defaults it to 5.
	Max float64

	// Readonly is shows the value, no interaction.
	//
	// The component defaults it to false.
	Readonly bool

	// The component defaults it to false.
	Disabled bool

	// Label is accessible name.
	//
	// The component defaults it to 'Rating'.
	Label string

	// Size is CSS length for the stars (overrides --ui-icon-size).
	//
	// The component defaults it to ''.
	Size string
}

// Rating renders <ui-rating>.
//
// <ui-rating> — a star rating.
//
// A11y choice: the whole rating is ONE control — role="slider" with
// aria-valuenow/-min/-max and aria-valuetext, a single tab stop, and arrow
// keys adjusting the value (Home=0, End=max). The stars themselves are
// pointer affordances only (hover previews, click commits), so there is no
// tab-stop-per-star noise for keyboard and screen-reader users.
//
// Clicking the star matching the current value clears the rating to 0
// (MUI parity).
func Rating(p RatingProps) *alacris.Element {
	e := alacris.E(RatingTag)
	if p.Value != 0 {
		e.Prop("value", p.Value)
	}
	if p.Max != 0 && p.Max != 5 {
		e.Prop("max", p.Max)
	}
	if p.Readonly {
		e.Prop("readonly", p.Readonly)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Label != "" && p.Label != "Rating" {
		e.Prop("label", p.Label)
	}
	if p.Size != "" {
		e.Prop("size", p.Size)
	}
	return e
}

// RatingHandle patches a rendered <ui-rating> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with RatingElement.
type RatingHandle struct {
	handle live.Handle
}

// RatingElement addresses the <ui-rating> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	RatingElement(c.Session, "id").SetValue(v)
func RatingElement(s *live.Session, id string) RatingHandle {
	return RatingHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h RatingHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h RatingHandle) SetValue(v float64) { h.handle.Set("value", v) }

// SetMax writes the max prop.
func (h RatingHandle) SetMax(v float64) { h.handle.Set("max", v) }

// SetReadonly writes the readonly prop.
func (h RatingHandle) SetReadonly(v bool) { h.handle.Set("readonly", v) }

// SetDisabled writes the disabled prop.
func (h RatingHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetLabel writes the label prop.
func (h RatingHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetSize writes the size prop.
func (h RatingHandle) SetSize(v string) { h.handle.Set("size", v) }
