// Code generated by alacris-go from ../assets/ui/components/ui-radio-group.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// RadioGroupTag is the name of the <ui-radio-group> custom element.
const RadioGroupTag = "ui-radio-group"

// Slots exposed by <ui-radio-group>. Put one on your own markup to fill it:
//
//	<h3 slot={ RadioGroupSlotDefault }>
const (
	// the <ui-radio> children
	RadioGroupSlotDefault = ""
)

// Events emitted by <ui-radio-group>. Forward one to a server action with On:
//
//	RadioGroup(props).On(RadioGroupEventChange, "handler-name")
const (
	// detail: { value }
	RadioGroupEventChange = "change"
)

// RadioGroupChangeDetail is the detail of the "change" event of <ui-radio-group>.
//
// detail: { value }
type RadioGroupChangeDetail struct {
	Value any `json:"value"`
}

// RadioGroupVars is the theming contract of <ui-radio-group>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	RadioGroup(props).Apply(RadioGroupVars, map[string]string{"--ui-radio-group-gap": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var RadioGroupVars = alacris.Vars(
	"--ui-radio-group-gap",
)

// RadioGroupProps are the props of <ui-radio-group>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type RadioGroupProps struct {
	// The component defaults it to ''.
	Value string

	// Name is form participation (submits `value`).
	//
	// The component defaults it to ''.
	Name string

	// Label is accessible name for the group.
	//
	// The component defaults it to ''.
	Label string

	// Disabled is disables every radio.
	//
	// The component defaults it to false.
	Disabled bool

	// Orientation is vertical | horizontal (layout only; arrows work on both axes per the APG).
	//
	// The component defaults it to 'vertical'.
	Orientation string
}

// RadioGroup renders <ui-radio-group>.
//
// <ui-radio-group> — owns a set of slotted <ui-radio>s: one selected value,
// one tab stop, arrow keys move AND select (ARIA APG radio group pattern).
//
// <ui-radio-group name="size" value=${size} @change=${(e) => size.set(e.detail.value)}>
// <ui-radio value="s" label="Small"></ui-radio>
// <ui-radio value="m" label="Medium"></ui-radio>
// </ui-radio-group>
func RadioGroup(p RadioGroupProps) *alacris.Element {
	e := alacris.E(RadioGroupTag)
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Name != "" {
		e.Prop("name", p.Name)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Orientation != "" && p.Orientation != "vertical" {
		e.Prop("orientation", p.Orientation)
	}
	return e
}

// RadioGroupHandle patches a rendered <ui-radio-group> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with RadioGroupElement.
type RadioGroupHandle struct {
	handle live.Handle
}

// RadioGroupElement addresses the <ui-radio-group> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	RadioGroupElement(c.Session, "id").SetValue(v)
func RadioGroupElement(s *live.Session, id string) RadioGroupHandle {
	return RadioGroupHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h RadioGroupHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h RadioGroupHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetName writes the name prop.
func (h RadioGroupHandle) SetName(v string) { h.handle.Set("name", v) }

// SetLabel writes the label prop.
func (h RadioGroupHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetDisabled writes the disabled prop.
func (h RadioGroupHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetOrientation writes the orientation prop.
func (h RadioGroupHandle) SetOrientation(v string) { h.handle.Set("orientation", v) }
