// Code generated by alacris-go from ../assets/ui/components/ui-stepper.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// StepperTag is the name of the <ui-stepper> custom element.
const StepperTag = "ui-stepper"

// Slots exposed by <ui-stepper>. Put one on your own markup to fill it:
//
//	<h3 slot={ StepperSlotDefault }>
const (
	// <ui-step> children
	StepperSlotDefault = ""
)

// StepperVars is the theming contract of <ui-stepper>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Stepper(props).Apply(StepperVars, map[string]string{"--ui-stepper-connector": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var StepperVars = alacris.Vars(
	"--ui-stepper-connector",
	"--ui-stepper-connector-active",
)

// StepperProps are the props of <ui-stepper>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type StepperProps struct {
	// Active is index of the active step; steps before it become `completed`, steps after it `upcoming`.
	//
	// The component defaults it to 0.
	Active float64
}

// Stepper renders <ui-stepper>.
//
// <ui-stepper> — a horizontal stepper of <ui-step> children.
//
// <ui-stepper active=${active}>
// <ui-step label="Cart"></ui-step>
// <ui-step label="Shipping" optional-text="Optional"></ui-step>
// <ui-step label="Payment"></ui-step>
// </ui-stepper>
//
// Presentation only — it emits nothing; wiring next/back navigation to
// `active` is application logic. On slotchange (and every `active` write) it
// assigns each child's `index`, `state`, a `data-state` attribute (used by the
// connector CSS), `role="listitem"`, and `aria-current="step"` on the active
// step. Connector lines between steps turn primary once the segment before a
// step is completed.
func Stepper(p StepperProps) *alacris.Element {
	e := alacris.E(StepperTag)
	if p.Active != 0 {
		e.Prop("active", p.Active)
	}
	return e
}

// StepperHandle patches a rendered <ui-stepper> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with StepperElement.
type StepperHandle struct {
	handle live.Handle
}

// StepperElement addresses the <ui-stepper> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	StepperElement(c.Session, "id").SetActive(v)
func StepperElement(s *live.Session, id string) StepperHandle {
	return StepperHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h StepperHandle) Handle() live.Handle { return h.handle }

// SetActive writes the active prop.
func (h StepperHandle) SetActive(v float64) { h.handle.Set("active", v) }
