// Code generated by alacris-go from ../assets/ui/components/ui-switch.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// SwitchTag is the name of the <ui-switch> custom element.
const SwitchTag = "ui-switch"

// Events emitted by <ui-switch>. Forward one to a server action with On:
//
//	Switch(props).On(SwitchEventChange, "handler-name")
const (
	// detail: { checked }
	SwitchEventChange = "change"
)

// SwitchChangeDetail is the detail of the "change" event of <ui-switch>.
//
// detail: { checked }
type SwitchChangeDetail struct {
	Checked any `json:"checked"`
}

// SwitchVars is the theming contract of <ui-switch>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Switch(props).Apply(SwitchVars, map[string]string{"--ui-switch-track-width": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var SwitchVars = alacris.Vars(
	"--ui-switch-track-width",
	"--ui-switch-track-height",
	"--ui-switch-track-bg",
	"--ui-switch-track-bg-checked",
	"--ui-switch-track-outline",
	"--ui-switch-handle-bg",
	"--ui-switch-handle-bg-checked",
	"--ui-switch-icon-fg",
	"--ui-switch-icon-fg-checked",
)

// SwitchProps are the props of <ui-switch>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type SwitchProps struct {
	// The component defaults it to false.
	Checked bool

	// The component defaults it to false.
	Disabled bool

	// Label is visible label; also the accessible name. Empty leaves the control unnamed (authoring error).
	//
	// The component defaults it to ''.
	Label string

	// Name is form field name (submits 'on'/value while checked).
	//
	// The component defaults it to ''.
	Name string

	// The component defaults it to 'on'.
	Value string

	// Icons is show check/close glyphs in the handle.
	//
	// The component defaults it to false.
	Icons bool
}

// Switch renders <ui-switch>.
//
// <ui-switch> — the Material switch.
func Switch(p SwitchProps) *alacris.Element {
	e := alacris.E(SwitchTag)
	if p.Checked {
		e.Prop("checked", p.Checked)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Name != "" {
		e.Prop("name", p.Name)
	}
	if p.Value != "" && p.Value != "on" {
		e.Prop("value", p.Value)
	}
	if p.Icons {
		e.Prop("icons", p.Icons)
	}
	return e
}

// SwitchHandle patches a rendered <ui-switch> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with SwitchElement.
type SwitchHandle struct {
	handle live.Handle
}

// SwitchElement addresses the <ui-switch> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	SwitchElement(c.Session, "id").SetChecked(v)
func SwitchElement(s *live.Session, id string) SwitchHandle {
	return SwitchHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h SwitchHandle) Handle() live.Handle { return h.handle }

// SetChecked writes the checked prop.
func (h SwitchHandle) SetChecked(v bool) { h.handle.Set("checked", v) }

// SetDisabled writes the disabled prop.
func (h SwitchHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetLabel writes the label prop.
func (h SwitchHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetName writes the name prop.
func (h SwitchHandle) SetName(v string) { h.handle.Set("name", v) }

// SetValue writes the value prop.
func (h SwitchHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetIcons writes the icons prop.
func (h SwitchHandle) SetIcons(v bool) { h.handle.Set("icons", v) }
