// Code generated by alacris-go from ../assets/ui/components/ui-side-sheet.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// SideSheetTag is the name of the <ui-side-sheet> custom element.
const SideSheetTag = "ui-side-sheet"

// Slots exposed by <ui-side-sheet>. Put one on your own markup to fill it:
//
//	<h3 slot={ SideSheetSlotDefault }>
const (
	// body content
	SideSheetSlotDefault  = ""
	SideSheetSlotHeadline = "headline"
	SideSheetSlotActions  = "actions"
)

// Events emitted by <ui-side-sheet>. Forward one to a server action with On:
//
//	SideSheet(props).On(SideSheetEventClose, "handler-name")
const (
	// detail: { reason: 'esc' | 'scrim' | 'method' }
	SideSheetEventClose = "close"
	// enter animation finished
	SideSheetEventOpened = "opened"
	// exit animation finished, DOM removed
	SideSheetEventClosed = "closed"
)

// SideSheetCloseDetail is the detail of the "close" event of <ui-side-sheet>.
//
// detail: { reason: 'esc' | 'scrim' | 'method' }
type SideSheetCloseDetail struct {
	Reason any `json:"reason"`
}

// SideSheetVars is the theming contract of <ui-side-sheet>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	SideSheet(props).Apply(SideSheetVars, map[string]string{"--ui-side-sheet-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var SideSheetVars = alacris.Vars(
	"--ui-side-sheet-bg",
	"--ui-side-sheet-fg",
	"--ui-side-sheet-width",
	"--ui-side-sheet-radius",
	"--ui-side-sheet-scrim",
)

// SideSheetProps are the props of <ui-side-sheet>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type SideSheetProps struct {
	// The component defaults it to false.
	Open bool

	// Variant is modal | standard.
	//
	// The component defaults it to 'modal'.
	Variant string

	// Anchor is start | end.
	//
	// The component defaults it to 'end'.
	Anchor string

	// Persistent is escape/scrim do not request closing.
	//
	// The component defaults it to false.
	Persistent bool

	// Label is accessible name if no headline slot.
	//
	// The component defaults it to ''.
	Label string
}

// SideSheet renders <ui-side-sheet>.
//
// <ui-side-sheet> — a Material side sheet for complementary content.
//
// <ui-side-sheet open=${open} @close=${() => open(false)}>
// <span slot="headline">Filters</span>
// Sheet body
// <ui-button slot="actions" variant="text">Apply</ui-button>
// </ui-side-sheet>
//
// Distinct from <ui-drawer> (navigation) and <ui-sheet> (bottom). Modal
// (default): a scrim plus a panel that slides in from the end edge. Focus is
// trapped and page scroll locked while open. The PARENT owns `open`. Standard:
// an in-flow panel that animates its inline size — no scrim, no trap.
func SideSheet(p SideSheetProps) *alacris.Element {
	e := alacris.E(SideSheetTag)
	if p.Open {
		e.Prop("open", p.Open)
	}
	if p.Variant != "" && p.Variant != "modal" {
		e.Prop("variant", p.Variant)
	}
	if p.Anchor != "" && p.Anchor != "end" {
		e.Prop("anchor", p.Anchor)
	}
	if p.Persistent {
		e.Prop("persistent", p.Persistent)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// SideSheetHandle patches a rendered <ui-side-sheet> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with SideSheetElement.
type SideSheetHandle struct {
	handle live.Handle
}

// SideSheetElement addresses the <ui-side-sheet> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	SideSheetElement(c.Session, "id").SetOpen(v)
func SideSheetElement(s *live.Session, id string) SideSheetHandle {
	return SideSheetHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h SideSheetHandle) Handle() live.Handle { return h.handle }

// SetOpen writes the open prop.
func (h SideSheetHandle) SetOpen(v bool) { h.handle.Set("open", v) }

// SetVariant writes the variant prop.
func (h SideSheetHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetAnchor writes the anchor prop.
func (h SideSheetHandle) SetAnchor(v string) { h.handle.Set("anchor", v) }

// SetPersistent writes the persistent prop.
func (h SideSheetHandle) SetPersistent(v bool) { h.handle.Set("persistent", v) }

// SetLabel writes the label prop.
func (h SideSheetHandle) SetLabel(v string) { h.handle.Set("label", v) }
