// Code generated by alacris-go from ../assets/ui/components/ui-slider.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// SliderTag is the name of the <ui-slider> custom element.
const SliderTag = "ui-slider"

// Events emitted by <ui-slider>. Forward one to a server action with On:
//
//	Slider(props).On(SliderEventInput, "handler-name")
const (
	// every drag/keystroke; detail: { value } or { start, end }
	SliderEventInput = "input"
	// committed value; detail: { value } or { start, end }
	SliderEventChange = "change"
)

// SliderInputDetail is the detail of the "input" event of <ui-slider>.
//
// every drag/keystroke; detail: { value } or { start, end }
type SliderInputDetail struct {
	Value any `json:"value"`
}

// SliderChangeDetail is the detail of the "change" event of <ui-slider>.
//
// committed value; detail: { value } or { start, end }
type SliderChangeDetail struct {
	Value any `json:"value"`
}

// SliderVars is the theming contract of <ui-slider>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Slider(props).Apply(SliderVars, map[string]string{"--ui-slider-track-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var SliderVars = alacris.Vars(
	"--ui-slider-track-height",
	"--ui-slider-thumb-size",
	"--ui-slider-track",
	"--ui-slider-active",
	"--ui-slider-thumb",
	"--ui-slider-bubble-bg",
	"--ui-slider-bubble-fg",
)

// SliderProps are the props of <ui-slider>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type SliderProps struct {
	// The component defaults it to 0.
	Value float64

	// The component defaults it to 0.
	Min float64

	// The component defaults it to 100.
	Max float64

	// The component defaults it to 1.
	Step float64

	// Range is two thumbs; uses valueStart / valueEnd.
	//
	// The component defaults it to false.
	Range bool

	// The component defaults it to 0.
	ValueStart float64

	// The component defaults it to 100.
	ValueEnd float64

	// Label is REQUIRED accessible name (aria-label).
	//
	// The component defaults it to ''.
	Label string

	// The component defaults it to false.
	Disabled bool

	// ShowValue is value bubble above the thumb while focused/dragging (animates in and out).
	//
	// The component defaults it to false.
	ShowValue bool

	// Name is form participation.
	//
	// The component defaults it to ''.
	Name string
}

// Slider renders <ui-slider>.
//
// <ui-slider> — a Material slider on native <input type="range">s for
// keyboard and screen-reader behavior.
//
// <ui-slider label="Volume" value=${volume}
// Bind `value` (or `.value`) to a signal like any other control. `input` /
// `change` report a number in `detail.value` (or `detail.start` / `detail.end`
// when `range`). The host `.value` is a string, matching a native range
// input, so composed-path helpers that look for `typeof node.value ===
// 'string'` work the same as they do for text fields.
//
// The active track portion is painted with `--ui-slider-fill` (or start/end
// when `range`) bound from the template into a gradient; the thumb's
// hover/focus halo is a box-shadow state layer.
func Slider(p SliderProps) *alacris.Element {
	e := alacris.E(SliderTag)
	if p.Value != 0 {
		e.Prop("value", p.Value)
	}
	if p.Min != 0 {
		e.Prop("min", p.Min)
	}
	if p.Max != 0 && p.Max != 100 {
		e.Prop("max", p.Max)
	}
	if p.Step != 0 && p.Step != 1 {
		e.Prop("step", p.Step)
	}
	if p.Range {
		e.Prop("range", p.Range)
	}
	if p.ValueStart != 0 {
		e.Prop("valueStart", p.ValueStart)
	}
	if p.ValueEnd != 0 && p.ValueEnd != 100 {
		e.Prop("valueEnd", p.ValueEnd)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.ShowValue {
		e.Prop("showValue", p.ShowValue)
	}
	if p.Name != "" {
		e.Prop("name", p.Name)
	}
	return e
}

// SliderHandle patches a rendered <ui-slider> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with SliderElement.
type SliderHandle struct {
	handle live.Handle
}

// SliderElement addresses the <ui-slider> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	SliderElement(c.Session, "id").SetValue(v)
func SliderElement(s *live.Session, id string) SliderHandle {
	return SliderHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h SliderHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h SliderHandle) SetValue(v float64) { h.handle.Set("value", v) }

// SetMin writes the min prop.
func (h SliderHandle) SetMin(v float64) { h.handle.Set("min", v) }

// SetMax writes the max prop.
func (h SliderHandle) SetMax(v float64) { h.handle.Set("max", v) }

// SetStep writes the step prop.
func (h SliderHandle) SetStep(v float64) { h.handle.Set("step", v) }

// SetRange writes the range prop.
func (h SliderHandle) SetRange(v bool) { h.handle.Set("range", v) }

// SetValueStart writes the valueStart prop.
func (h SliderHandle) SetValueStart(v float64) { h.handle.Set("valueStart", v) }

// SetValueEnd writes the valueEnd prop.
func (h SliderHandle) SetValueEnd(v float64) { h.handle.Set("valueEnd", v) }

// SetLabel writes the label prop.
func (h SliderHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetDisabled writes the disabled prop.
func (h SliderHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetShowValue writes the showValue prop.
func (h SliderHandle) SetShowValue(v bool) { h.handle.Set("showValue", v) }

// SetName writes the name prop.
func (h SliderHandle) SetName(v string) { h.handle.Set("name", v) }
