// Code generated by alacris-go from ../assets/ui/components/ui-step.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// StepTag is the name of the <ui-step> custom element.
const StepTag = "ui-step"

// StepVars is the theming contract of <ui-step>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Step(props).Apply(StepVars, map[string]string{"--ui-step-indicator-size": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var StepVars = alacris.Vars(
	"--ui-step-indicator-size",
	"--ui-step-bg",
	"--ui-step-fg",
	"--ui-step-active-bg",
	"--ui-step-active-fg",
	"--ui-step-label-fg",
	"--ui-step-label-fg-active",
	"--ui-step-font",
	"--ui-step-tracking",
	"--ui-step-optional-font",
	"--ui-step-optional-tracking",
)

// StepProps are the props of <ui-step>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type StepProps struct {
	// The component defaults it to ''.
	Label string

	// Index is 0-based position; assigned by <ui-stepper>.
	//
	// The component defaults it to 0.
	Index float64

	// State is upcoming | active | completed; assigned by <ui-stepper> from its `active` prop.
	//
	// The component defaults it to 'upcoming'.
	State string

	// OptionalText is small secondary line under the label.
	//
	// The component defaults it to ''.
	OptionalText string
}

// Step renders <ui-step>.
//
// <ui-step> — one step inside <ui-stepper>.
//
// Presentation only: the circle shows the 1-based number (or a check when
// completed); <ui-stepper> owns index/state assignment and the connectors.
func Step(p StepProps) *alacris.Element {
	e := alacris.E(StepTag)
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Index != 0 {
		e.Prop("index", p.Index)
	}
	if p.State != "" && p.State != "upcoming" {
		e.Prop("state", p.State)
	}
	if p.OptionalText != "" {
		e.Prop("optionalText", p.OptionalText)
	}
	return e
}

// StepHandle patches a rendered <ui-step> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with StepElement.
type StepHandle struct {
	handle live.Handle
}

// StepElement addresses the <ui-step> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	StepElement(c.Session, "id").SetLabel(v)
func StepElement(s *live.Session, id string) StepHandle {
	return StepHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h StepHandle) Handle() live.Handle { return h.handle }

// SetLabel writes the label prop.
func (h StepHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetIndex writes the index prop.
func (h StepHandle) SetIndex(v float64) { h.handle.Set("index", v) }

// SetState writes the state prop.
func (h StepHandle) SetState(v string) { h.handle.Set("state", v) }

// SetOptionalText writes the optionalText prop.
func (h StepHandle) SetOptionalText(v string) { h.handle.Set("optionalText", v) }
