// Code generated by alacris-go from ../assets/ui/components/ui-select.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// SelectTag is the name of the <ui-select> custom element.
const SelectTag = "ui-select"

// Slots exposed by <ui-select>. Put one on your own markup to fill it:
//
//	<h3 slot={ SelectSlotDefault }>
const (
	// <ui-option> children (projected into the panel)
	SelectSlotDefault = ""
)

// Events emitted by <ui-select>. Forward one to a server action with On:
//
//	Select(props).On(SelectEventChange, "handler-name")
const (
	// an option was chosen; detail: { value }
	SelectEventChange = "change"
	// panel enter animation finished
	SelectEventOpen = "open"
	// panel exit animation finished
	SelectEventClose = "close"
)

// SelectChangeDetail is the detail of the "change" event of <ui-select>.
//
// an option was chosen; detail: { value }
type SelectChangeDetail struct {
	Value any `json:"value"`
}

// SelectVars is the theming contract of <ui-select>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Select(props).Apply(SelectVars, map[string]string{"--ui-select-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var SelectVars = alacris.Vars(
	"--ui-select-bg",
	"--ui-select-fg",
	"--ui-select-label-fg",
	"--ui-select-accent",
	"--ui-select-outline-color",
	"--ui-select-radius",
	"--ui-select-font",
	"--ui-select-height",
	"--ui-select-panel-bg",
)

// SelectProps are the props of <ui-select>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type SelectProps struct {
	// The component defaults it to ''.
	Label string

	// Value is the selected option's value.
	//
	// The component defaults it to ''.
	Value string

	// Variant is filled | outlined.
	//
	// The component defaults it to 'filled'.
	Variant string

	// The component defaults it to false.
	Disabled bool

	// The component defaults it to false.
	Required bool

	// Name is form participation.
	//
	// The component defaults it to ''.
	Name string

	// Placeholder is shown while nothing is selected.
	//
	// The component defaults it to ''.
	Placeholder string
}

// Select renders <ui-select>.
//
// <ui-select> — Material select: a text-field-style field button that opens a
// listbox of slotted <ui-option>s.
//
// <ui-select label="Flavor" value=${flavor} @change=${(e) => flavor(e.detail.value)}>
// <ui-option value="vanilla">Vanilla</ui-option>
// <ui-option value="mint">Mint</ui-option>
// </ui-select>
//
// Keyboard (APG select-only combobox): Enter/Space/ArrowDown/ArrowUp open;
// arrows move the active option, Enter/Space selects it, Escape closes,
// typing jumps to the next option starting with that letter. The panel closes
// on outside pointerdown and returns focus to the field.
//
// Note: the combobox's aria-activedescendant references option ids in the
// host's light DOM; the options also carry aria-selected for AT that walks
// the composed tree.
func Select(p SelectProps) *alacris.Element {
	e := alacris.E(SelectTag)
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Variant != "" && p.Variant != "filled" {
		e.Prop("variant", p.Variant)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Required {
		e.Prop("required", p.Required)
	}
	if p.Name != "" {
		e.Prop("name", p.Name)
	}
	if p.Placeholder != "" {
		e.Prop("placeholder", p.Placeholder)
	}
	return e
}

// SelectHandle patches a rendered <ui-select> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with SelectElement.
type SelectHandle struct {
	handle live.Handle
}

// SelectElement addresses the <ui-select> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	SelectElement(c.Session, "id").SetLabel(v)
func SelectElement(s *live.Session, id string) SelectHandle {
	return SelectHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h SelectHandle) Handle() live.Handle { return h.handle }

// SetLabel writes the label prop.
func (h SelectHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetValue writes the value prop.
func (h SelectHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetVariant writes the variant prop.
func (h SelectHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetDisabled writes the disabled prop.
func (h SelectHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetRequired writes the required prop.
func (h SelectHandle) SetRequired(v bool) { h.handle.Set("required", v) }

// SetName writes the name prop.
func (h SelectHandle) SetName(v string) { h.handle.Set("name", v) }

// SetPlaceholder writes the placeholder prop.
func (h SelectHandle) SetPlaceholder(v string) { h.handle.Set("placeholder", v) }
