// Code generated by alacris-go from ../assets/ui/components/ui-search.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// SearchTag is the name of the <ui-search> custom element.
const SearchTag = "ui-search"

// Slots exposed by <ui-search>. Put one on your own markup to fill it:
//
//	<h3 slot={ SearchSlotLeading }>
const (
	// replaces the search icon
	SearchSlotLeading = "leading"
	// after the clear button (avatar, extra actions)
	SearchSlotTrailing = "trailing"
	// suggestion rows (ui-list-item, …). The panel is a list so those rows keep role="listitem"; it is not a listbox.
	SearchSlotDefault = ""
)

// Events emitted by <ui-search>. Forward one to a server action with On:
//
//	Search(props).On(SearchEventInput, "handler-name")
const (
	// every keystroke; detail: { value }
	SearchEventInput = "input"
	// committed (blur/Enter); detail: { value }
	SearchEventChange = "change"
	// Enter pressed; detail: { value }
	SearchEventSubmit = "submit"
	// the clear affordance was used
	SearchEventClear = "clear"
	// suggestions visible (after the enter animation); does not bubble
	SearchEventOpen = "open"
	// suggestions removed (after the exit animation); does not bubble
	SearchEventClose = "close"
)

// SearchInputDetail is the detail of the "input" event of <ui-search>.
//
// every keystroke; detail: { value }
type SearchInputDetail struct {
	Value any `json:"value"`
}

// SearchChangeDetail is the detail of the "change" event of <ui-search>.
//
// committed (blur/Enter); detail: { value }
type SearchChangeDetail struct {
	Value any `json:"value"`
}

// SearchSubmitDetail is the detail of the "submit" event of <ui-search>.
//
// Enter pressed; detail: { value }
type SearchSubmitDetail struct {
	Value any `json:"value"`
}

// SearchVars is the theming contract of <ui-search>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Search(props).Apply(SearchVars, map[string]string{"--ui-search-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var SearchVars = alacris.Vars(
	"--ui-search-bg",
	"--ui-search-bg-active",
	"--ui-search-fg",
	"--ui-search-placeholder-fg",
	"--ui-search-radius",
	"--ui-search-font",
	"--ui-search-height",
	"--ui-search-panel-bg",
	"--ui-search-panel-radius",
	"--ui-search-divider",
)

// SearchProps are the props of <ui-search>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type SearchProps struct {
	// Label is accessible name (and the floating placeholder).
	//
	// The component defaults it to 'Search'.
	Label string

	// The component defaults it to ''.
	Value string

	// Placeholder is shown in the field; falls back to `label`.
	//
	// The component defaults it to ''.
	Placeholder string

	// Presentation is bar | view.
	//
	// The component defaults it to 'bar'.
	Presentation string

	// Open is view / suggestions visibility.
	//
	// The component defaults it to false.
	Open bool

	// The component defaults it to false.
	Disabled bool

	// Name is form participation.
	//
	// The component defaults it to ''.
	Name string
}

// Search renders <ui-search>.
//
// <ui-search> — Material search bar.
//
// <ui-search label="Search mail" value=${q}
// A pill-shaped field with a leading search icon, a trailing clear control
// while there is text, and an optional trailing slot (avatar, voice, …).
// Enter emits `submit`. The field chrome is the focus indicator — the inner
// input has no extra outline.
//
// `presentation="view"` opens a search view: a back control and a suggestions
// list (the default slot) while open. The list overlays the page — it does
// not grow the layout. Typing a query opens the view; clearing the field
// (keyboard or the clear button) closes it back to the pill bar. Focus on an
// empty view still shows recents, but a clear while focused stays on the bar.
// The open surface is one extra-large rounded container (bar + overlay list)
// with a divider between the field and the list.
func Search(p SearchProps) *alacris.Element {
	e := alacris.E(SearchTag)
	if p.Label != "" && p.Label != "Search" {
		e.Prop("label", p.Label)
	}
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Placeholder != "" {
		e.Prop("placeholder", p.Placeholder)
	}
	if p.Presentation != "" && p.Presentation != "bar" {
		e.Prop("presentation", p.Presentation)
	}
	if p.Open {
		e.Prop("open", p.Open)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Name != "" {
		e.Prop("name", p.Name)
	}
	return e
}

// SearchHandle patches a rendered <ui-search> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with SearchElement.
type SearchHandle struct {
	handle live.Handle
}

// SearchElement addresses the <ui-search> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	SearchElement(c.Session, "id").SetLabel(v)
func SearchElement(s *live.Session, id string) SearchHandle {
	return SearchHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h SearchHandle) Handle() live.Handle { return h.handle }

// SetLabel writes the label prop.
func (h SearchHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetValue writes the value prop.
func (h SearchHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetPlaceholder writes the placeholder prop.
func (h SearchHandle) SetPlaceholder(v string) { h.handle.Set("placeholder", v) }

// SetPresentation writes the presentation prop.
func (h SearchHandle) SetPresentation(v string) { h.handle.Set("presentation", v) }

// SetOpen writes the open prop.
func (h SearchHandle) SetOpen(v bool) { h.handle.Set("open", v) }

// SetDisabled writes the disabled prop.
func (h SearchHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetName writes the name prop.
func (h SearchHandle) SetName(v string) { h.handle.Set("name", v) }
