// Code generated by alacris-go from ../assets/ui/components/ui-sheet.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// SheetTag is the name of the <ui-sheet> custom element.
const SheetTag = "ui-sheet"

// Slots exposed by <ui-sheet>. Put one on your own markup to fill it:
//
//	<h3 slot={ SheetSlotDefault }>
const (
	// body content
	SheetSlotDefault  = ""
	SheetSlotHeadline = "headline"
	SheetSlotActions  = "actions"
)

// Events emitted by <ui-sheet>. Forward one to a server action with On:
//
//	Sheet(props).On(SheetEventClose, "handler-name")
const (
	// detail: { reason: 'esc' | 'scrim' | 'method' }
	SheetEventClose = "close"
	// enter animation finished
	SheetEventOpened = "opened"
	// exit animation finished, DOM removed
	SheetEventClosed = "closed"
)

// SheetCloseDetail is the detail of the "close" event of <ui-sheet>.
//
// detail: { reason: 'esc' | 'scrim' | 'method' }
type SheetCloseDetail struct {
	Reason any `json:"reason"`
}

// SheetVars is the theming contract of <ui-sheet>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Sheet(props).Apply(SheetVars, map[string]string{"--ui-sheet-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var SheetVars = alacris.Vars(
	"--ui-sheet-bg",
	"--ui-sheet-fg",
	"--ui-sheet-radius",
	"--ui-sheet-width",
	"--ui-sheet-handle",
	"--ui-sheet-scrim",
)

// SheetProps are the props of <ui-sheet>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type SheetProps struct {
	// The component defaults it to false.
	Open bool

	// Variant is modal | standard.
	//
	// The component defaults it to 'modal'.
	Variant string

	// Persistent is escape/scrim do not request closing.
	//
	// The component defaults it to false.
	Persistent bool

	// Label is accessible name if no headline slot.
	//
	// The component defaults it to ''.
	Label string
}

// Sheet renders <ui-sheet>.
//
// <ui-sheet> — a Material bottom sheet.
//
// <ui-sheet open=${open} @close=${() => open(false)}>
// <span slot="headline">Title</span>
// Sheet body
// <ui-button slot="actions" variant="text">Close</ui-button>
// </ui-sheet>
//
// Modal (default): a scrim plus a panel that slides up from the bottom.
// Focus is trapped and page scroll locked while open. The PARENT owns
// `open`: Escape and scrim clicks emit `close` with a reason.
// Standard: an in-flow panel that expands from zero height — no scrim,
// no trap.
func Sheet(p SheetProps) *alacris.Element {
	e := alacris.E(SheetTag)
	if p.Open {
		e.Prop("open", p.Open)
	}
	if p.Variant != "" && p.Variant != "modal" {
		e.Prop("variant", p.Variant)
	}
	if p.Persistent {
		e.Prop("persistent", p.Persistent)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// SheetHandle patches a rendered <ui-sheet> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with SheetElement.
type SheetHandle struct {
	handle live.Handle
}

// SheetElement addresses the <ui-sheet> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	SheetElement(c.Session, "id").SetOpen(v)
func SheetElement(s *live.Session, id string) SheetHandle {
	return SheetHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h SheetHandle) Handle() live.Handle { return h.handle }

// SetOpen writes the open prop.
func (h SheetHandle) SetOpen(v bool) { h.handle.Set("open", v) }

// SetVariant writes the variant prop.
func (h SheetHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetPersistent writes the persistent prop.
func (h SheetHandle) SetPersistent(v bool) { h.handle.Set("persistent", v) }

// SetLabel writes the label prop.
func (h SheetHandle) SetLabel(v string) { h.handle.Set("label", v) }
