// Code generated by alacris-go from ../assets/ui/components/ui-snackbar.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// SnackbarTag is the name of the <ui-snackbar> custom element.
const SnackbarTag = "ui-snackbar"

// Events emitted by <ui-snackbar>. Forward one to a server action with On:
//
//	Snackbar(props).On(SnackbarEventAction, "handler-name")
const (
	// action button pressed
	SnackbarEventAction = "action"
	// detail: { reason: 'timeout' | 'action' | 'close' | 'method' }
	SnackbarEventClose = "close"
	// enter animation finished
	SnackbarEventOpened = "opened"
	// exit animation finished, DOM removed
	SnackbarEventClosed = "closed"
)

// SnackbarCloseDetail is the detail of the "close" event of <ui-snackbar>.
//
// detail: { reason: 'timeout' | 'action' | 'close' | 'method' }
type SnackbarCloseDetail struct {
	Reason any `json:"reason"`
}

// SnackbarVars is the theming contract of <ui-snackbar>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Snackbar(props).Apply(SnackbarVars, map[string]string{"--ui-snackbar-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var SnackbarVars = alacris.Vars(
	"--ui-snackbar-bg",
	"--ui-snackbar-fg",
	"--ui-snackbar-action-fg",
	"--ui-snackbar-radius",
	"--ui-snackbar-min-width",
	"--ui-snackbar-max-width",
	"--ui-snackbar-elevation",
)

// SnackbarProps are the props of <ui-snackbar>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type SnackbarProps struct {
	// The component defaults it to false.
	Open bool

	// The component defaults it to ''.
	Message string

	// Action is label for a trailing text action button.
	//
	// The component defaults it to ''.
	Action string

	// Duration is auto-dismiss after ms; 0 = sticky.
	//
	// The component defaults it to 4000.
	Duration float64

	// CloseButton is trailing close icon button.
	//
	// The component defaults it to false.
	CloseButton bool
}

// Snackbar renders <ui-snackbar>.
//
// <ui-snackbar> — a transient bottom-center message, plus `showSnackbar()`,
// an imperative service that queues messages through one shared instance.
//
// Declarative (parent owns the state):
//
// <ui-snackbar open=${open} message="Draft saved" action="Undo"
// Imperative (fire and forget; FIFO — one visible at a time):
//
// const { close, closed } = showSnackbar('Message archived', { action: 'Undo' });
//
// The component requests closing by emitting `close` with a reason — the
// PARENT flips `open`. `closed` fires after the exit animation finishes.
func Snackbar(p SnackbarProps) *alacris.Element {
	e := alacris.E(SnackbarTag)
	if p.Open {
		e.Prop("open", p.Open)
	}
	if p.Message != "" {
		e.Prop("message", p.Message)
	}
	if p.Action != "" {
		e.Prop("action", p.Action)
	}
	if p.Duration != 0 && p.Duration != 4000 {
		e.Prop("duration", p.Duration)
	}
	if p.CloseButton {
		e.Prop("closeButton", p.CloseButton)
	}
	return e
}

// SnackbarHandle patches a rendered <ui-snackbar> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with SnackbarElement.
type SnackbarHandle struct {
	handle live.Handle
}

// SnackbarElement addresses the <ui-snackbar> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	SnackbarElement(c.Session, "id").SetOpen(v)
func SnackbarElement(s *live.Session, id string) SnackbarHandle {
	return SnackbarHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h SnackbarHandle) Handle() live.Handle { return h.handle }

// SetOpen writes the open prop.
func (h SnackbarHandle) SetOpen(v bool) { h.handle.Set("open", v) }

// SetMessage writes the message prop.
func (h SnackbarHandle) SetMessage(v string) { h.handle.Set("message", v) }

// SetAction writes the action prop.
func (h SnackbarHandle) SetAction(v string) { h.handle.Set("action", v) }

// SetDuration writes the duration prop.
func (h SnackbarHandle) SetDuration(v float64) { h.handle.Set("duration", v) }

// SetCloseButton writes the closeButton prop.
func (h SnackbarHandle) SetCloseButton(v bool) { h.handle.Set("closeButton", v) }
