// Code generated by alacris-go from ../assets/ui/components/ui-spinner.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// SpinnerTag is the name of the <ui-spinner> custom element.
const SpinnerTag = "ui-spinner"

// SpinnerVars is the theming contract of <ui-spinner>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Spinner(props).Apply(SpinnerVars, map[string]string{"--ui-spinner-size": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var SpinnerVars = alacris.Vars(
	"--ui-spinner-size",
	"--ui-spinner-color",
	"--ui-spinner-track-color",
)

// SpinnerProps are the props of <ui-spinner>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type SpinnerProps struct {
	// Value is current value; -1 (any negative) = indeterminate.
	//
	// The component defaults it to -1.
	Value float64

	// Max is value scale.
	//
	// The component defaults it to 100.
	Max float64

	// Size is CSS length; overrides --ui-spinner-size (default 48px).
	//
	// The component defaults it to ''.
	Size string

	// Label is accessible name (aria-label on the progressbar).
	//
	// The component defaults it to ''.
	Label string
}

// Spinner renders <ui-spinner>.
//
// <ui-spinner> — Material circular progress.
//
// <ui-spinner label="Loading"></ui-spinner>                 indeterminate
// <ui-spinner label="Upload" value=${pct}></ui-spinner>     determinate
// <ui-spinner label="Loading" size="24px"></ui-spinner>
//
// One SVG circle in a 44-unit viewBox with a 4-unit stroke, so the stroke
// scales with `size`. Determinate progress binds stroke-dashoffset from the
// value; indeterminate is the classic rotate + dash-grow loop as CSS
// keyframes, its cycle derived from the motion tokens.
func Spinner(p SpinnerProps) *alacris.Element {
	e := alacris.E(SpinnerTag)
	if p.Value != 0 && p.Value != -1 {
		e.Prop("value", p.Value)
	}
	if p.Max != 0 && p.Max != 100 {
		e.Prop("max", p.Max)
	}
	if p.Size != "" {
		e.Prop("size", p.Size)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// SpinnerHandle patches a rendered <ui-spinner> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with SpinnerElement.
type SpinnerHandle struct {
	handle live.Handle
}

// SpinnerElement addresses the <ui-spinner> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	SpinnerElement(c.Session, "id").SetValue(v)
func SpinnerElement(s *live.Session, id string) SpinnerHandle {
	return SpinnerHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h SpinnerHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h SpinnerHandle) SetValue(v float64) { h.handle.Set("value", v) }

// SetMax writes the max prop.
func (h SpinnerHandle) SetMax(v float64) { h.handle.Set("max", v) }

// SetSize writes the size prop.
func (h SpinnerHandle) SetSize(v string) { h.handle.Set("size", v) }

// SetLabel writes the label prop.
func (h SpinnerHandle) SetLabel(v string) { h.handle.Set("label", v) }
