// Code generated by alacris-go from ../assets/ui/components/ui-skeleton.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// SkeletonTag is the name of the <ui-skeleton> custom element.
const SkeletonTag = "ui-skeleton"

// SkeletonVars is the theming contract of <ui-skeleton>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Skeleton(props).Apply(SkeletonVars, map[string]string{"--ui-skeleton-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var SkeletonVars = alacris.Vars(
	"--ui-skeleton-bg",
	"--ui-skeleton-wave",
	"--ui-skeleton-radius",
)

// SkeletonProps are the props of <ui-skeleton>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type SkeletonProps struct {
	// Variant is text | circular | rectangular.
	//
	// The component defaults it to 'text'.
	Variant string

	// Width is CSS length; defaults to 100%.
	//
	// The component defaults it to ''.
	Width string

	// Height is CSS length; text defaults to 1em.
	//
	// The component defaults it to ''.
	Height string

	// Animation is pulse | wave | none.
	//
	// The component defaults it to 'pulse'.
	Animation string
}

// Skeleton renders <ui-skeleton>.
//
// <ui-skeleton> — a loading placeholder shape.
//
// <ui-skeleton variant="circular" width="40px" height="40px"></ui-skeleton>
// <ui-skeleton width="60%"></ui-skeleton>
// <ui-skeleton variant="rectangular" height="120px" animation="wave"></ui-skeleton>
//
// Always aria-hidden: a skeleton is decorative. Announce loading state on the
// region that will receive the content (aria-busy), not on the placeholder.
func Skeleton(p SkeletonProps) *alacris.Element {
	e := alacris.E(SkeletonTag)
	if p.Variant != "" && p.Variant != "text" {
		e.Prop("variant", p.Variant)
	}
	if p.Width != "" {
		e.Prop("width", p.Width)
	}
	if p.Height != "" {
		e.Prop("height", p.Height)
	}
	if p.Animation != "" && p.Animation != "pulse" {
		e.Prop("animation", p.Animation)
	}
	return e
}

// SkeletonHandle patches a rendered <ui-skeleton> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with SkeletonElement.
type SkeletonHandle struct {
	handle live.Handle
}

// SkeletonElement addresses the <ui-skeleton> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	SkeletonElement(c.Session, "id").SetVariant(v)
func SkeletonElement(s *live.Session, id string) SkeletonHandle {
	return SkeletonHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h SkeletonHandle) Handle() live.Handle { return h.handle }

// SetVariant writes the variant prop.
func (h SkeletonHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetWidth writes the width prop.
func (h SkeletonHandle) SetWidth(v string) { h.handle.Set("width", v) }

// SetHeight writes the height prop.
func (h SkeletonHandle) SetHeight(v string) { h.handle.Set("height", v) }

// SetAnimation writes the animation prop.
func (h SkeletonHandle) SetAnimation(v string) { h.handle.Set("animation", v) }
