// Code generated by alacris-go from ../assets/ui/components/ui-surface.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// SurfaceTag is the name of the <ui-surface> custom element.
const SurfaceTag = "ui-surface"

// Slots exposed by <ui-surface>. Put one on your own markup to fill it:
//
//	<h3 slot={ SurfaceSlotDefault }>
const (
	SurfaceSlotDefault = ""
)

// SurfaceProps are the props of <ui-surface>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type SurfaceProps struct {
	// Elevation is shadow level 0..5 (--ui-elevation-N).
	//
	// The component defaults it to 0.
	Elevation float64

	// Radius is none | xs | sm | md | lg | xl | full.
	//
	// The component defaults it to 'md'.
	Radius string

	// Bg is any color role name, kebab or camel ('primary-container', 'surfaceContainerHigh'); text color pairs automatically with the role's on- counterpart when one exists, falling back to on-surface.
	//
	// The component defaults it to 'surface'.
	Bg string

	// Outlined is 1px outline-variant border.
	//
	// The component defaults it to false.
	Outlined bool
}

// Surface renders <ui-surface>.
//
// <ui-surface> — a themable surface (the Paper equivalent).
//
// <ui-surface elevation="2" radius="lg" bg="surface-container">…</ui-surface>
func Surface(p SurfaceProps) *alacris.Element {
	e := alacris.E(SurfaceTag)
	if p.Elevation != 0 {
		e.Prop("elevation", p.Elevation)
	}
	if p.Radius != "" && p.Radius != "md" {
		e.Prop("radius", p.Radius)
	}
	if p.Bg != "" && p.Bg != "surface" {
		e.Prop("bg", p.Bg)
	}
	if p.Outlined {
		e.Prop("outlined", p.Outlined)
	}
	return e
}

// SurfaceHandle patches a rendered <ui-surface> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with SurfaceElement.
type SurfaceHandle struct {
	handle live.Handle
}

// SurfaceElement addresses the <ui-surface> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	SurfaceElement(c.Session, "id").SetElevation(v)
func SurfaceElement(s *live.Session, id string) SurfaceHandle {
	return SurfaceHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h SurfaceHandle) Handle() live.Handle { return h.handle }

// SetElevation writes the elevation prop.
func (h SurfaceHandle) SetElevation(v float64) { h.handle.Set("elevation", v) }

// SetRadius writes the radius prop.
func (h SurfaceHandle) SetRadius(v string) { h.handle.Set("radius", v) }

// SetBg writes the bg prop.
func (h SurfaceHandle) SetBg(v string) { h.handle.Set("bg", v) }

// SetOutlined writes the outlined prop.
func (h SurfaceHandle) SetOutlined(v bool) { h.handle.Set("outlined", v) }
