// Code generated by alacris-go from ../assets/ui/components/ui-swipe-row.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// SwipeRowTag is the name of the <ui-swipe-row> custom element.
const SwipeRowTag = "ui-swipe-row"

// Slots exposed by <ui-swipe-row>. Put one on your own markup to fill it:
//
//	<h3 slot={ SwipeRowSlotDefault }>
const (
	// primary row content (e.g. <ui-list-item>, <ui-card>)
	SwipeRowSlotDefault = ""
	// actions revealed when swiping right
	SwipeRowSlotStart = "start"
	// actions revealed when swiping left
	SwipeRowSlotEnd = "end"
)

// Events emitted by <ui-swipe-row>. Forward one to a server action with On:
//
//	SwipeRow(props).On(SwipeRowEventOpen, "handler-name")
const (
	// detail: { side: 'start' | 'end' }
	SwipeRowEventOpen = "open"
	// detail: {}
	SwipeRowEventClose = "close"
	// detail: { side: 'start' | 'end' }
	SwipeRowEventAction = "action"
)

// SwipeRowOpenDetail is the detail of the "open" event of <ui-swipe-row>.
//
// detail: { side: 'start' | 'end' }
type SwipeRowOpenDetail struct {
	Side any `json:"side"`
}

// SwipeRowActionDetail is the detail of the "action" event of <ui-swipe-row>.
//
// detail: { side: 'start' | 'end' }
type SwipeRowActionDetail struct {
	Side any `json:"side"`
}

// SwipeRowVars is the theming contract of <ui-swipe-row>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	SwipeRow(props).Apply(SwipeRowVars, map[string]string{"--ui-swipe-row-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var SwipeRowVars = alacris.Vars(
	"--ui-swipe-row-bg",
	"--ui-swipe-row-action-start-bg",
	"--ui-swipe-row-action-start-fg",
	"--ui-swipe-row-action-end-bg",
	"--ui-swipe-row-action-end-fg",
)

// SwipeRowProps are the props of <ui-swipe-row>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type SwipeRowProps struct {
	// Open is '' | 'start' | 'end'.
	//
	// The component defaults it to ''.
	Open string

	// Disabled is disables gesture tracking.
	//
	// The component defaults it to false.
	Disabled bool

	// Threshold is fraction of action width to snap open.
	//
	// The component defaults it to 0.4.
	Threshold float64

	// FullSwipe is swiping past 65% width triggers action.
	//
	// The component defaults it to false.
	FullSwipe bool
}

// SwipeRow renders <ui-swipe-row>.
//
// <ui-swipe-row> — an Android-style horizontal swipe-to-reveal row container.
//
// <ui-swipe-row>
// <ui-icon-button slot="end" icon="delete" label="Delete" danger></ui-icon-button>
// <ui-icon-button slot="end" icon="archive" label="Archive"></ui-icon-button>
// <ui-list-item headline="Swipeable message" supporting="Swipe left to reveal actions"></ui-list-item>
// </ui-swipe-row>
func SwipeRow(p SwipeRowProps) *alacris.Element {
	e := alacris.E(SwipeRowTag)
	if p.Open != "" {
		e.Prop("open", p.Open)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Threshold != 0 && p.Threshold != 0.4 {
		e.Prop("threshold", p.Threshold)
	}
	if p.FullSwipe {
		e.Prop("fullSwipe", p.FullSwipe)
	}
	return e
}

// SwipeRowHandle patches a rendered <ui-swipe-row> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with SwipeRowElement.
type SwipeRowHandle struct {
	handle live.Handle
}

// SwipeRowElement addresses the <ui-swipe-row> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	SwipeRowElement(c.Session, "id").SetOpen(v)
func SwipeRowElement(s *live.Session, id string) SwipeRowHandle {
	return SwipeRowHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h SwipeRowHandle) Handle() live.Handle { return h.handle }

// SetOpen writes the open prop.
func (h SwipeRowHandle) SetOpen(v string) { h.handle.Set("open", v) }

// SetDisabled writes the disabled prop.
func (h SwipeRowHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetThreshold writes the threshold prop.
func (h SwipeRowHandle) SetThreshold(v float64) { h.handle.Set("threshold", v) }

// SetFullSwipe writes the fullSwipe prop.
func (h SwipeRowHandle) SetFullSwipe(v bool) { h.handle.Set("fullSwipe", v) }
