// Code generated by alacris-go from ../assets/ui/components/ui-stack.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// StackTag is the name of the <ui-stack> custom element.
const StackTag = "ui-stack"

// Slots exposed by <ui-stack>. Put one on your own markup to fill it:
//
//	<h3 slot={ StackSlotDefault }>
const (
	StackSlotDefault = ""
)

// StackProps are the props of <ui-stack>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type StackProps struct {
	// Direction is row | column | row-reverse | column-reverse.
	//
	// The component defaults it to 'column'.
	Direction string

	// Gap is a spacing step (maps to the --ui-space-N token: 1,2,3,4,5,6,7,8,10,12,16,20,24) or any raw CSS length ('1.5rem', '12px').
	//
	// The component defaults it to '2'.
	Gap any

	// Align is align-items value ('' leaves the default).
	//
	// The component defaults it to ''.
	Align string

	// Justify is justify-content value.
	//
	// The component defaults it to ''.
	Justify string

	// Wrap is flex-wrap: wrap.
	//
	// The component defaults it to false.
	Wrap bool
}

// Stack renders <ui-stack>.
//
// <ui-stack> — a flexbox layout primitive.
//
// <ui-stack direction="row" gap="4" align="center">…</ui-stack>
func Stack(p StackProps) *alacris.Element {
	e := alacris.E(StackTag)
	if p.Direction != "" && p.Direction != "column" {
		e.Prop("direction", p.Direction)
	}
	if p.Gap != nil {
		e.Prop("gap", p.Gap)
	}
	if p.Align != "" {
		e.Prop("align", p.Align)
	}
	if p.Justify != "" {
		e.Prop("justify", p.Justify)
	}
	if p.Wrap {
		e.Prop("wrap", p.Wrap)
	}
	return e
}

// StackHandle patches a rendered <ui-stack> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with StackElement.
type StackHandle struct {
	handle live.Handle
}

// StackElement addresses the <ui-stack> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	StackElement(c.Session, "id").SetDirection(v)
func StackElement(s *live.Session, id string) StackHandle {
	return StackHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h StackHandle) Handle() live.Handle { return h.handle }

// SetDirection writes the direction prop.
func (h StackHandle) SetDirection(v string) { h.handle.Set("direction", v) }

// SetGap writes the gap prop.
func (h StackHandle) SetGap(v any) { h.handle.Set("gap", v) }

// SetAlign writes the align prop.
func (h StackHandle) SetAlign(v string) { h.handle.Set("align", v) }

// SetJustify writes the justify prop.
func (h StackHandle) SetJustify(v string) { h.handle.Set("justify", v) }

// SetWrap writes the wrap prop.
func (h StackHandle) SetWrap(v bool) { h.handle.Set("wrap", v) }
