// Code generated by alacris-go from ../assets/ui/components/ui-split-button.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// SplitButtonTag is the name of the <ui-split-button> custom element.
const SplitButtonTag = "ui-split-button"

// Slots exposed by <ui-split-button>. Put one on your own markup to fill it:
//
//	<h3 slot={ SplitButtonSlotDefault }>
const (
	// leading-segment label
	SplitButtonSlotDefault = ""
	// leading icon on the primary action
	SplitButtonSlotIcon = "icon"
	// <ui-menu-item> children
	SplitButtonSlotMenu = "menu"
)

// Events emitted by <ui-split-button>. Forward one to a server action with On:
//
//	SplitButton(props).On(SplitButtonEventSelect, "handler-name")
const (
	// a menu action was chosen; detail: { value }
	SplitButtonEventSelect = "select"
)

// SplitButtonSelectDetail is the detail of the "select" event of <ui-split-button>.
//
// a menu action was chosen; detail: { value }
type SplitButtonSelectDetail struct {
	Value any `json:"value"`
}

// SplitButtonVars is the theming contract of <ui-split-button>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	SplitButton(props).Apply(SplitButtonVars, map[string]string{"--ui-split-button-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var SplitButtonVars = alacris.Vars(
	"--ui-split-button-height",
	"--ui-split-button-pad-inline",
	"--ui-split-button-radius",
	"--ui-split-button-font",
	"--ui-split-button-tracking",
	"--ui-split-button-filled-bg",
	"--ui-split-button-filled-fg",
	"--ui-split-button-tonal-bg",
	"--ui-split-button-tonal-fg",
	"--ui-split-button-outlined-fg",
	"--ui-split-button-outline-color",
	"--ui-split-button-elevated-bg",
	"--ui-split-button-elevated-fg",
	"--ui-split-button-divider",
)

// SplitButtonProps are the props of <ui-split-button>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type SplitButtonProps struct {
	// Variant is filled | tonal | outlined | elevated.
	//
	// The component defaults it to 'filled'.
	Variant string

	// The component defaults it to false.
	Disabled bool
}

// SplitButton renders <ui-split-button>.
//
// <ui-split-button> — a Material split button: a primary action plus a
// connected chevron that opens related actions.
//
// <ui-split-button variant="filled" @click=${save}>
// Save
// <ui-menu-item slot="menu" value="draft">Save draft</ui-menu-item>
// <ui-menu-item slot="menu" value="copy">Save a copy</ui-menu-item>
// </ui-split-button>
//
// The leading segment is the primary action (native click bubbles). Choosing
// a menu item emits `select` with that item's value.
func SplitButton(p SplitButtonProps) *alacris.Element {
	e := alacris.E(SplitButtonTag)
	if p.Variant != "" && p.Variant != "filled" {
		e.Prop("variant", p.Variant)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	return e
}

// SplitButtonHandle patches a rendered <ui-split-button> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with SplitButtonElement.
type SplitButtonHandle struct {
	handle live.Handle
}

// SplitButtonElement addresses the <ui-split-button> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	SplitButtonElement(c.Session, "id").SetVariant(v)
func SplitButtonElement(s *live.Session, id string) SplitButtonHandle {
	return SplitButtonHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h SplitButtonHandle) Handle() live.Handle { return h.handle }

// SetVariant writes the variant prop.
func (h SplitButtonHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetDisabled writes the disabled prop.
func (h SplitButtonHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }
