// Code generated by alacris-go from ../assets/ui/components/ui-tab-panel.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// TabPanelTag is the name of the <ui-tab-panel> custom element.
const TabPanelTag = "ui-tab-panel"

// Slots exposed by <ui-tab-panel>. Put one on your own markup to fill it:
//
//	<h3 slot={ TabPanelSlotDefault }>
const (
	// panel content
	TabPanelSlotDefault = ""
)

// TabPanelVars is the theming contract of <ui-tab-panel>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	TabPanel(props).Apply(TabPanelVars, map[string]string{"--ui-tab-panel-fg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var TabPanelVars = alacris.Vars(
	"--ui-tab-panel-fg",
	"--ui-tab-panel-font",
	"--ui-tab-panel-pad-block",
)

// TabPanelProps are the props of <ui-tab-panel>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type TabPanelProps struct {
	// Value is REQUIRED; matched against the tabs' value.
	//
	// The component defaults it to ''.
	Value string

	// Active is managed by the parent <ui-tabs>.
	//
	// The component defaults it to false.
	Active bool
}

// TabPanel renders <ui-tab-panel>.
//
// <ui-tab-panel> — the content pane paired with a <ui-tab>.
//
// Slot it into <ui-tabs slot="panels">. The parent sets `active` when its
// `value` matches; do not set `active` yourself. The panel is hidden while
// inactive and fades in when it becomes active.
func TabPanel(p TabPanelProps) *alacris.Element {
	e := alacris.E(TabPanelTag)
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Active {
		e.Prop("active", p.Active)
	}
	return e
}

// TabPanelHandle patches a rendered <ui-tab-panel> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with TabPanelElement.
type TabPanelHandle struct {
	handle live.Handle
}

// TabPanelElement addresses the <ui-tab-panel> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	TabPanelElement(c.Session, "id").SetValue(v)
func TabPanelElement(s *live.Session, id string) TabPanelHandle {
	return TabPanelHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h TabPanelHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h TabPanelHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetActive writes the active prop.
func (h TabPanelHandle) SetActive(v bool) { h.handle.Set("active", v) }
