// Code generated by alacris-go from ../assets/ui/components/ui-time-picker.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// TimePickerTag is the name of the <ui-time-picker> custom element.
const TimePickerTag = "ui-time-picker"

// Events emitted by <ui-time-picker>. Forward one to a server action with On:
//
//	TimePicker(props).On(TimePickerEventChange, "handler-name")
const (
	// committed; detail: { value }
	TimePickerEventChange = "change"
	// field keystroke; detail: { value } (the raw text)
	TimePickerEventInput = "input"
	// panel visible (after the enter animation); does not bubble
	TimePickerEventOpen = "open"
	// panel removed (after the exit animation); does not bubble
	TimePickerEventClose = "close"
)

// TimePickerChangeDetail is the detail of the "change" event of <ui-time-picker>.
//
// committed; detail: { value }
type TimePickerChangeDetail struct {
	Value any `json:"value"`
}

// TimePickerInputDetail is the detail of the "input" event of <ui-time-picker>.
//
// field keystroke; detail: { value } (the raw text)
type TimePickerInputDetail struct {
	Value any `json:"value"`
}

// TimePickerVars is the theming contract of <ui-time-picker>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	TimePicker(props).Apply(TimePickerVars, map[string]string{"--ui-time-picker-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var TimePickerVars = alacris.Vars(
	"--ui-time-picker-bg",
	"--ui-time-picker-fg",
	"--ui-time-picker-label-fg",
	"--ui-time-picker-accent",
	"--ui-time-picker-on-accent",
	"--ui-time-picker-outline-color",
	"--ui-time-picker-radius",
	"--ui-time-picker-font",
	"--ui-time-picker-height",
	"--ui-time-picker-panel-bg",
	"--ui-time-picker-panel-radius",
	"--ui-time-picker-digit-bg",
	"--ui-time-picker-selected-bg",
	"--ui-time-picker-selected-fg",
)

// TimePickerProps are the props of <ui-time-picker>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type TimePickerProps struct {
	// The component defaults it to ''.
	Label string

	// Value is 24-hour HH:mm, or '' for none.
	//
	// The component defaults it to ''.
	Value string

	// Variant is filled | outlined.
	//
	// The component defaults it to 'filled'.
	Variant string

	// View is clock | input (dial vs digital grid).
	//
	// The component defaults it to 'clock'.
	View string

	// HourCycle is 12 | 24.
	//
	// The component defaults it to '12'.
	HourCycle string

	// MinuteStep is minute choices (1, 5, or 15 typical).
	//
	// The component defaults it to 5.
	MinuteStep float64

	// Locale is BCP 47 tag; empty uses the runtime locale.
	//
	// The component defaults it to ''.
	Locale string

	// The component defaults it to false.
	Disabled bool

	// The component defaults it to false.
	Required bool

	// Name is form participation.
	//
	// The component defaults it to ''.
	Name string

	// The component defaults it to ''.
	Placeholder string
}

// TimePicker renders <ui-time-picker>.
//
// <ui-time-picker> — Material time picker: a text-field-style control that
// opens an hour/minute chooser. Value is a 24-hour `HH:mm` string.
//
// <ui-time-picker label="Alarm" value=${time}
// The keyboard icon in the panel toggles between the analog dial and the
// digital hour/minute grids (MD3 input-method toggle). Hour and minute
// faces crossfade; the clock hand rotates with the motion tokens.
func TimePicker(p TimePickerProps) *alacris.Element {
	e := alacris.E(TimePickerTag)
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Variant != "" && p.Variant != "filled" {
		e.Prop("variant", p.Variant)
	}
	if p.View != "" && p.View != "clock" {
		e.Prop("view", p.View)
	}
	if p.HourCycle != "" && p.HourCycle != "12" {
		e.Prop("hourCycle", p.HourCycle)
	}
	if p.MinuteStep != 0 && p.MinuteStep != 5 {
		e.Prop("minuteStep", p.MinuteStep)
	}
	if p.Locale != "" {
		e.Prop("locale", p.Locale)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Required {
		e.Prop("required", p.Required)
	}
	if p.Name != "" {
		e.Prop("name", p.Name)
	}
	if p.Placeholder != "" {
		e.Prop("placeholder", p.Placeholder)
	}
	return e
}

// TimePickerHandle patches a rendered <ui-time-picker> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with TimePickerElement.
type TimePickerHandle struct {
	handle live.Handle
}

// TimePickerElement addresses the <ui-time-picker> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	TimePickerElement(c.Session, "id").SetLabel(v)
func TimePickerElement(s *live.Session, id string) TimePickerHandle {
	return TimePickerHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h TimePickerHandle) Handle() live.Handle { return h.handle }

// SetLabel writes the label prop.
func (h TimePickerHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetValue writes the value prop.
func (h TimePickerHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetVariant writes the variant prop.
func (h TimePickerHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetView writes the view prop.
func (h TimePickerHandle) SetView(v string) { h.handle.Set("view", v) }

// SetHourCycle writes the hourCycle prop.
func (h TimePickerHandle) SetHourCycle(v string) { h.handle.Set("hourCycle", v) }

// SetMinuteStep writes the minuteStep prop.
func (h TimePickerHandle) SetMinuteStep(v float64) { h.handle.Set("minuteStep", v) }

// SetLocale writes the locale prop.
func (h TimePickerHandle) SetLocale(v string) { h.handle.Set("locale", v) }

// SetDisabled writes the disabled prop.
func (h TimePickerHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetRequired writes the required prop.
func (h TimePickerHandle) SetRequired(v bool) { h.handle.Set("required", v) }

// SetName writes the name prop.
func (h TimePickerHandle) SetName(v string) { h.handle.Set("name", v) }

// SetPlaceholder writes the placeholder prop.
func (h TimePickerHandle) SetPlaceholder(v string) { h.handle.Set("placeholder", v) }
