// Code generated by alacris-go from ../assets/ui/components/ui-toggle-button.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// ToggleButtonTag is the name of the <ui-toggle-button> custom element.
const ToggleButtonTag = "ui-toggle-button"

// Slots exposed by <ui-toggle-button>. Put one on your own markup to fill it:
//
//	<h3 slot={ ToggleButtonSlotDefault }>
const (
	// label
	ToggleButtonSlotDefault = ""
)

// Events emitted by <ui-toggle-button>. Forward one to a server action with On:
//
//	ToggleButton(props).On(ToggleButtonEventUIToggle, "handler-name")
const (
	// pressed; detail: { value } (consumed by ui-toggle-group)
	ToggleButtonEventUIToggle = "ui-toggle"
)

// ToggleButtonUIToggleDetail is the detail of the "ui-toggle" event of <ui-toggle-button>.
//
// pressed; detail: { value } (consumed by ui-toggle-group)
type ToggleButtonUIToggleDetail struct {
	Value any `json:"value"`
}

// ToggleButtonVars is the theming contract of <ui-toggle-button>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	ToggleButton(props).Apply(ToggleButtonVars, map[string]string{"--ui-toggle-button-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var ToggleButtonVars = alacris.Vars(
	"--ui-toggle-button-height",
	"--ui-toggle-button-radius",
	"--ui-toggle-button-bg",
	"--ui-toggle-button-fg",
	"--ui-toggle-button-selected-bg",
	"--ui-toggle-button-selected-fg",
	"--ui-toggle-button-font",
	"--ui-toggle-button-tracking",
)

// ToggleButtonProps are the props of <ui-toggle-button>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type ToggleButtonProps struct {
	// Value is REQUIRED identity within the group.
	//
	// The component defaults it to ''.
	Value string

	// Selected is set by the owning group.
	//
	// The component defaults it to false.
	Selected bool

	// The component defaults it to false.
	Disabled bool

	// Icon is optional leading icon.
	//
	// The component defaults it to ''.
	Icon string
}

// ToggleButton renders <ui-toggle-button>.
//
// <ui-toggle-button> — one Material segmented button, used inside
// <ui-toggle-group> (the group draws the outlined container and dividers;
// standalone the segment is a flat pill).
//
// Selecting animates a leading check icon in smoothly via width and scale transitions,
// adhering to Material Design 3. When an icon is already present, selecting smoothly
// crossfades and morphs between the custom icon and the checkmark in both directions.
// The button does not own its selection: it emits `ui-toggle` and the group
// (or any parent) sets `selected` back down.
func ToggleButton(p ToggleButtonProps) *alacris.Element {
	e := alacris.E(ToggleButtonTag)
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Selected {
		e.Prop("selected", p.Selected)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Icon != "" {
		e.Prop("icon", p.Icon)
	}
	return e
}

// ToggleButtonHandle patches a rendered <ui-toggle-button> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with ToggleButtonElement.
type ToggleButtonHandle struct {
	handle live.Handle
}

// ToggleButtonElement addresses the <ui-toggle-button> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	ToggleButtonElement(c.Session, "id").SetValue(v)
func ToggleButtonElement(s *live.Session, id string) ToggleButtonHandle {
	return ToggleButtonHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h ToggleButtonHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h ToggleButtonHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetSelected writes the selected prop.
func (h ToggleButtonHandle) SetSelected(v bool) { h.handle.Set("selected", v) }

// SetDisabled writes the disabled prop.
func (h ToggleButtonHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetIcon writes the icon prop.
func (h ToggleButtonHandle) SetIcon(v string) { h.handle.Set("icon", v) }
