// Code generated by alacris-go from ../assets/ui/components/ui-tooltip.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// TooltipTag is the name of the <ui-tooltip> custom element.
const TooltipTag = "ui-tooltip"

// Slots exposed by <ui-tooltip>. Put one on your own markup to fill it:
//
//	<h3 slot={ TooltipSlotDefault }>
const (
	// the target
	TooltipSlotDefault = ""
	// rich tooltip content (title/body/actions) when `rich`
	TooltipSlotContent = "content"
)

// TooltipVars is the theming contract of <ui-tooltip>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Tooltip(props).Apply(TooltipVars, map[string]string{"--ui-tooltip-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var TooltipVars = alacris.Vars(
	"--ui-tooltip-bg",
	"--ui-tooltip-fg",
	"--ui-tooltip-font",
	"--ui-tooltip-radius",
	"--ui-tooltip-max-width",
	"--ui-tooltip-rich-bg",
	"--ui-tooltip-rich-fg",
	"--ui-tooltip-rich-radius",
	"--ui-tooltip-rich-max-width",
)

// TooltipProps are the props of <ui-tooltip>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type TooltipProps struct {
	// Text is plain tooltip content.
	//
	// The component defaults it to ''.
	Text string

	// Position is top | bottom | left | right.
	//
	// The component defaults it to 'top'.
	Position string

	// Delay is hover show delay (ms); focus shows instantly.
	//
	// The component defaults it to 500.
	Delay float64

	// Rich is renders the `content` slot in a surface panel instead of the text pill.
	//
	// The component defaults it to false.
	Rich bool
}

// Tooltip renders <ui-tooltip>.
//
// <ui-tooltip> — a plain (or rich) tooltip on hover/focus around its target.
//
// <ui-tooltip text="Save changes"><ui-button>Save</ui-button></ui-tooltip>
//
// Shows after `delay` ms on pointerenter (timer cancelled on leave) and
// immediately on focusin; hides on pointerleave, focusout, and Escape. The
// panel is position: fixed, anchored to the host with position()/autoUpdate,
// flipping to the opposite side when it would overflow the viewport.
//
// a11y: `aria-describedby` cannot point across shadow boundaries, so the
// association is not programmatic — the panel carries role="tooltip" and the
// target keeps its own accessible name. Give the target a matching
// label/aria-label when the tooltip is the only description.
func Tooltip(p TooltipProps) *alacris.Element {
	e := alacris.E(TooltipTag)
	if p.Text != "" {
		e.Prop("text", p.Text)
	}
	if p.Position != "" && p.Position != "top" {
		e.Prop("position", p.Position)
	}
	if p.Delay != 0 && p.Delay != 500 {
		e.Prop("delay", p.Delay)
	}
	if p.Rich {
		e.Prop("rich", p.Rich)
	}
	return e
}

// TooltipHandle patches a rendered <ui-tooltip> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with TooltipElement.
type TooltipHandle struct {
	handle live.Handle
}

// TooltipElement addresses the <ui-tooltip> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	TooltipElement(c.Session, "id").SetText(v)
func TooltipElement(s *live.Session, id string) TooltipHandle {
	return TooltipHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h TooltipHandle) Handle() live.Handle { return h.handle }

// SetText writes the text prop.
func (h TooltipHandle) SetText(v string) { h.handle.Set("text", v) }

// SetPosition writes the position prop.
func (h TooltipHandle) SetPosition(v string) { h.handle.Set("position", v) }

// SetDelay writes the delay prop.
func (h TooltipHandle) SetDelay(v float64) { h.handle.Set("delay", v) }

// SetRich writes the rich prop.
func (h TooltipHandle) SetRich(v bool) { h.handle.Set("rich", v) }
