// Code generated by alacris-go from ../assets/ui/components/ui-table-footer.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// TableFooterTag is the name of the <ui-table-footer> custom element.
const TableFooterTag = "ui-table-footer"

// Events emitted by <ui-table-footer>. Forward one to a server action with On:
//
//	TableFooter(props).On(TableFooterEventPage, "handler-name")
const (
	// page or page-size changed; detail: { page, pageSize }
	TableFooterEventPage = "page"
)

// TableFooterPageDetail is the detail of the "page" event of <ui-table-footer>.
//
// page or page-size changed; detail: { page, pageSize }
type TableFooterPageDetail struct {
	Page     any `json:"page"`
	Pagesize any `json:"pagesize"`
}

// TableFooterVars is the theming contract of <ui-table-footer>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	TableFooter(props).Apply(TableFooterVars, map[string]string{"--ui-table-footer-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var TableFooterVars = alacris.Vars(
	"--ui-table-footer-height",
	"--ui-table-footer-fg",
	"--ui-table-footer-border-color",
)

// TableFooterProps are the props of <ui-table-footer>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type TableFooterProps struct {
	// The component defaults it to 1.
	Page float64

	// PageSize is 0 hides the pager and shows a total only.
	//
	// The component defaults it to 0.
	PageSize float64

	// The component defaults it to 0.
	RowCount float64

	// PageSizeOptions is default 5, 10, 25.
	//
	// Crosses as JSON in the page-size-options attribute.
	PageSizeOptions []any

	// The component defaults it to false.
	Disabled bool

	// The component defaults it to 'Table pagination'.
	Label string
}

// TableFooter renders <ui-table-footer>.
//
// <ui-table-footer> — pagination and row-count for <ui-table>.
// Composes <ui-pagination> for the page window and a rows-per-page <select>.
//
// <ui-table-footer page=${page} page-size="10" row-count=${n}
func TableFooter(p TableFooterProps) *alacris.Element {
	e := alacris.E(TableFooterTag)
	if p.Page != 0 && p.Page != 1 {
		e.Prop("page", p.Page)
	}
	if p.PageSize != 0 {
		e.Prop("pageSize", p.PageSize)
	}
	if p.RowCount != 0 {
		e.Prop("rowCount", p.RowCount)
	}
	if len(p.PageSizeOptions) > 0 {
		e.Prop("pageSizeOptions", p.PageSizeOptions)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Label != "" && p.Label != "Table pagination" {
		e.Prop("label", p.Label)
	}
	return e
}

// TableFooterHandle patches a rendered <ui-table-footer> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with TableFooterElement.
type TableFooterHandle struct {
	handle live.Handle
}

// TableFooterElement addresses the <ui-table-footer> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	TableFooterElement(c.Session, "id").SetPage(v)
func TableFooterElement(s *live.Session, id string) TableFooterHandle {
	return TableFooterHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h TableFooterHandle) Handle() live.Handle { return h.handle }

// SetPage writes the page prop.
func (h TableFooterHandle) SetPage(v float64) { h.handle.Set("page", v) }

// SetPageSize writes the pageSize prop.
func (h TableFooterHandle) SetPageSize(v float64) { h.handle.Set("pageSize", v) }

// SetRowCount writes the rowCount prop.
func (h TableFooterHandle) SetRowCount(v float64) { h.handle.Set("rowCount", v) }

// SetPageSizeOptions writes the pageSizeOptions prop.
func (h TableFooterHandle) SetPageSizeOptions(v []any) { h.handle.Set("pageSizeOptions", v) }

// SetDisabled writes the disabled prop.
func (h TableFooterHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetLabel writes the label prop.
func (h TableFooterHandle) SetLabel(v string) { h.handle.Set("label", v) }
