// Code generated by alacris-go from ../assets/ui/components/ui-table-toolbar.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// TableToolbarTag is the name of the <ui-table-toolbar> custom element.
const TableToolbarTag = "ui-table-toolbar"

// Slots exposed by <ui-table-toolbar>. Put one on your own markup to fill it:
//
//	<h3 slot={ TableToolbarSlotHeadline }>
const (
	// replaces the headline text
	TableToolbarSlotHeadline   = "headline"
	TableToolbarSlotSupporting = "supporting"
	// extra trailing controls (after the built-in tools)
	TableToolbarSlotActions = "actions"
)

// Events emitted by <ui-table-toolbar>. Forward one to a server action with On:
//
//	TableToolbar(props).On(TableToolbarEventFilter, "handler-name")
const (
	// quick filter changed; detail: { value }
	TableToolbarEventFilter = "filter"
	// density chosen; detail: { density }
	TableToolbarEventDensity = "density"
	// a column was toggled; detail: { hidden }
	TableToolbarEventColumnVisibility = "column-visibility"
	// export requested; detail: { format: 'csv' }
	TableToolbarEventExport = "export"
)

// TableToolbarFilterDetail is the detail of the "filter" event of <ui-table-toolbar>.
//
// quick filter changed; detail: { value }
type TableToolbarFilterDetail struct {
	Value any `json:"value"`
}

// TableToolbarDensityDetail is the detail of the "density" event of <ui-table-toolbar>.
//
// density chosen; detail: { density }
type TableToolbarDensityDetail struct {
	Density any `json:"density"`
}

// TableToolbarColumnVisibilityDetail is the detail of the "column-visibility" event of <ui-table-toolbar>.
//
// a column was toggled; detail: { hidden }
type TableToolbarColumnVisibilityDetail struct {
	Hidden any `json:"hidden"`
}

// TableToolbarExportDetail is the detail of the "export" event of <ui-table-toolbar>.
//
// export requested; detail: { format: 'csv' }
type TableToolbarExportDetail struct {
	Format any `json:"format"`
}

// TableToolbarVars is the theming contract of <ui-table-toolbar>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	TableToolbar(props).Apply(TableToolbarVars, map[string]string{"--ui-table-toolbar-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var TableToolbarVars = alacris.Vars(
	"--ui-table-toolbar-height",
	"--ui-table-toolbar-bg",
	"--ui-table-toolbar-selected-bg",
	"--ui-table-toolbar-selected-fg",
	"--ui-table-toolbar-panel-bg",
	"--ui-table-toolbar-radius",
	"--ui-table-toolbar-elevation",
)

// TableToolbarProps are the props of <ui-table-toolbar>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type TableToolbarProps struct {
	// The component defaults it to ''.
	Headline string

	// The component defaults it to ''.
	Supporting string

	// SelectedCount is when >0 the bar switches to the "N selected" selection state.
	//
	// The component defaults it to 0.
	SelectedCount float64

	// Filter is quick-filter value.
	//
	// The component defaults it to ''.
	Filter string

	// The component defaults it to false.
	QuickFilter bool

	// The component defaults it to false.
	ColumnMenu bool

	// The component defaults it to false.
	DensityMenu bool

	// The component defaults it to false.
	CsvExport bool

	// Columns is { key, label } (JSON or property).
	//
	// Crosses as JSON in the columns attribute.
	Columns []any

	// Crosses as JSON in the hidden-columns attribute.
	HiddenColumns []any

	// Density is compact | standard | comfortable.
	//
	// The component defaults it to 'standard'.
	Density string

	// The component defaults it to false.
	Disabled bool
}

// TableToolbar renders <ui-table-toolbar>.
//
// <ui-table-toolbar> — DataGrid chrome: title, selection count, quick filter,
// column visibility, density, and CSV export. Built from <ui-search>,
// <ui-icon-button>, <ui-menu>, and <ui-checkbox>.
//
// <ui-table-toolbar headline="Nutrition" quick-filter column-menu
// density-menu csv-export
// columns=${cols} hidden-columns=${hidden}
func TableToolbar(p TableToolbarProps) *alacris.Element {
	e := alacris.E(TableToolbarTag)
	if p.Headline != "" {
		e.Prop("headline", p.Headline)
	}
	if p.Supporting != "" {
		e.Prop("supporting", p.Supporting)
	}
	if p.SelectedCount != 0 {
		e.Prop("selectedCount", p.SelectedCount)
	}
	if p.Filter != "" {
		e.Prop("filter", p.Filter)
	}
	if p.QuickFilter {
		e.Prop("quickFilter", p.QuickFilter)
	}
	if p.ColumnMenu {
		e.Prop("columnMenu", p.ColumnMenu)
	}
	if p.DensityMenu {
		e.Prop("densityMenu", p.DensityMenu)
	}
	if p.CsvExport {
		e.Prop("csvExport", p.CsvExport)
	}
	if len(p.Columns) > 0 {
		e.Prop("columns", p.Columns)
	}
	if len(p.HiddenColumns) > 0 {
		e.Prop("hiddenColumns", p.HiddenColumns)
	}
	if p.Density != "" && p.Density != "standard" {
		e.Prop("density", p.Density)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	return e
}

// TableToolbarHandle patches a rendered <ui-table-toolbar> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with TableToolbarElement.
type TableToolbarHandle struct {
	handle live.Handle
}

// TableToolbarElement addresses the <ui-table-toolbar> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	TableToolbarElement(c.Session, "id").SetHeadline(v)
func TableToolbarElement(s *live.Session, id string) TableToolbarHandle {
	return TableToolbarHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h TableToolbarHandle) Handle() live.Handle { return h.handle }

// SetHeadline writes the headline prop.
func (h TableToolbarHandle) SetHeadline(v string) { h.handle.Set("headline", v) }

// SetSupporting writes the supporting prop.
func (h TableToolbarHandle) SetSupporting(v string) { h.handle.Set("supporting", v) }

// SetSelectedCount writes the selectedCount prop.
func (h TableToolbarHandle) SetSelectedCount(v float64) { h.handle.Set("selectedCount", v) }

// SetFilter writes the filter prop.
func (h TableToolbarHandle) SetFilter(v string) { h.handle.Set("filter", v) }

// SetQuickFilter writes the quickFilter prop.
func (h TableToolbarHandle) SetQuickFilter(v bool) { h.handle.Set("quickFilter", v) }

// SetColumnMenu writes the columnMenu prop.
func (h TableToolbarHandle) SetColumnMenu(v bool) { h.handle.Set("columnMenu", v) }

// SetDensityMenu writes the densityMenu prop.
func (h TableToolbarHandle) SetDensityMenu(v bool) { h.handle.Set("densityMenu", v) }

// SetCsvExport writes the csvExport prop.
func (h TableToolbarHandle) SetCsvExport(v bool) { h.handle.Set("csvExport", v) }

// SetColumns writes the columns prop.
func (h TableToolbarHandle) SetColumns(v []any) { h.handle.Set("columns", v) }

// SetHiddenColumns writes the hiddenColumns prop.
func (h TableToolbarHandle) SetHiddenColumns(v []any) { h.handle.Set("hiddenColumns", v) }

// SetDensity writes the density prop.
func (h TableToolbarHandle) SetDensity(v string) { h.handle.Set("density", v) }

// SetDisabled writes the disabled prop.
func (h TableToolbarHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }
