// Code generated by alacris-go from ../assets/ui/components/ui-toolbar.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// ToolbarTag is the name of the <ui-toolbar> custom element.
const ToolbarTag = "ui-toolbar"

// Slots exposed by <ui-toolbar>. Put one on your own markup to fill it:
//
//	<h3 slot={ ToolbarSlotDefault }>
const (
	// icon buttons and other actions
	ToolbarSlotDefault = ""
	// optional <ui-fab> attached to the end
	ToolbarSlotFab = "fab"
)

// ToolbarVars is the theming contract of <ui-toolbar>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Toolbar(props).Apply(ToolbarVars, map[string]string{"--ui-toolbar-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var ToolbarVars = alacris.Vars(
	"--ui-toolbar-height",
	"--ui-toolbar-bg",
	"--ui-toolbar-fg",
	"--ui-toolbar-radius",
	"--ui-toolbar-pad",
	"--ui-toolbar-elevation",
)

// ToolbarProps are the props of <ui-toolbar>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type ToolbarProps struct {
	// Label is accessible name for the toolbar.
	//
	// The component defaults it to ''.
	Label string
}

// Toolbar renders <ui-toolbar>.
//
// <ui-toolbar> — a Material contextual toolbar: a floating strip of icon
// actions, optionally with an attached FAB.
//
// <ui-toolbar label="Selection">
// <ui-icon-button icon="edit" label="Edit"></ui-icon-button>
// <ui-icon-button icon="delete" label="Delete"></ui-icon-button>
// <ui-fab slot="fab" icon="add" size="sm"></ui-fab>
// </ui-toolbar>
func Toolbar(p ToolbarProps) *alacris.Element {
	e := alacris.E(ToolbarTag)
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// ToolbarHandle patches a rendered <ui-toolbar> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with ToolbarElement.
type ToolbarHandle struct {
	handle live.Handle
}

// ToolbarElement addresses the <ui-toolbar> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	ToolbarElement(c.Session, "id").SetLabel(v)
func ToolbarElement(s *live.Session, id string) ToolbarHandle {
	return ToolbarHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h ToolbarHandle) Handle() live.Handle { return h.handle }

// SetLabel writes the label prop.
func (h ToolbarHandle) SetLabel(v string) { h.handle.Set("label", v) }
