// Code generated by alacris-go from ../assets/ui/components/ui-tab.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// TabTag is the name of the <ui-tab> custom element.
const TabTag = "ui-tab"

// Slots exposed by <ui-tab>. Put one on your own markup to fill it:
//
//	<h3 slot={ TabSlotDefault }>
const (
	// label
	TabSlotDefault = ""
)

// Events emitted by <ui-tab>. Forward one to a server action with On:
//
//	Tab(props).On(TabEventUITabSelect, "handler-name")
const (
	// internal; detail: { value } (consumed by <ui-tabs>)
	TabEventUITabSelect = "ui-tab-select"
)

// TabUITabSelectDetail is the detail of the "ui-tab-select" event of <ui-tab>.
//
// internal; detail: { value } (consumed by <ui-tabs>)
type TabUITabSelectDetail struct {
	Value any `json:"value"`
}

// TabVars is the theming contract of <ui-tab>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Tab(props).Apply(TabVars, map[string]string{"--ui-tab-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var TabVars = alacris.Vars(
	"--ui-tab-height",
	"--ui-tab-pad-inline",
	"--ui-tab-gap",
	"--ui-tab-font",
	"--ui-tab-tracking",
	"--ui-tab-fg",
	"--ui-tab-selected-fg",
)

// TabProps are the props of <ui-tab>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type TabProps struct {
	// Value is REQUIRED; matched against the tabs' value.
	//
	// The component defaults it to ''.
	Value string

	// Icon is leading registry icon.
	//
	// The component defaults it to ''.
	Icon string

	// The component defaults it to false.
	Disabled bool

	// Selected is managed by the parent <ui-tabs>.
	//
	// The component defaults it to false.
	Selected bool
}

// Tab renders <ui-tab>.
//
// <ui-tab> — one tab inside <ui-tabs>.
//
// The host element carries the `tab` semantics (role, aria-selected,
// focusability) so <ui-tabs>' roving tabindex can manage it directly in the
// light DOM. `selected` is written by the parent <ui-tabs>; do not set it
// yourself — set the tabs' `value` instead.
func Tab(p TabProps) *alacris.Element {
	e := alacris.E(TabTag)
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Icon != "" {
		e.Prop("icon", p.Icon)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Selected {
		e.Prop("selected", p.Selected)
	}
	return e
}

// TabHandle patches a rendered <ui-tab> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with TabElement.
type TabHandle struct {
	handle live.Handle
}

// TabElement addresses the <ui-tab> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	TabElement(c.Session, "id").SetValue(v)
func TabElement(s *live.Session, id string) TabHandle {
	return TabHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h TabHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h TabHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetIcon writes the icon prop.
func (h TabHandle) SetIcon(v string) { h.handle.Set("icon", v) }

// SetDisabled writes the disabled prop.
func (h TabHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetSelected writes the selected prop.
func (h TabHandle) SetSelected(v bool) { h.handle.Set("selected", v) }
