// Code generated by alacris-go from ../assets/ui/components/ui-tabs.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// TabsTag is the name of the <ui-tabs> custom element.
const TabsTag = "ui-tabs"

// Slots exposed by <ui-tabs>. Put one on your own markup to fill it:
//
//	<h3 slot={ TabsSlotDefault }>
const (
	// <ui-tab> children
	TabsSlotDefault = ""
	// <ui-tab-panel> children
	TabsSlotPanels = "panels"
)

// Events emitted by <ui-tabs>. Forward one to a server action with On:
//
//	Tabs(props).On(TabsEventChange, "handler-name")
const (
	// user selected a tab; detail: { value }
	TabsEventChange = "change"
)

// TabsChangeDetail is the detail of the "change" event of <ui-tabs>.
//
// user selected a tab; detail: { value }
type TabsChangeDetail struct {
	Value any `json:"value"`
}

// TabsVars is the theming contract of <ui-tabs>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Tabs(props).Apply(TabsVars, map[string]string{"--ui-tabs-indicator": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var TabsVars = alacris.Vars(
	"--ui-tabs-indicator",
	"--ui-tabs-indicator-height",
	"--ui-tabs-divider",
)

// TabsProps are the props of <ui-tabs>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type TabsProps struct {
	// Value is the selected tab's value.
	//
	// The component defaults it to ''.
	Value string

	// Variant is primary | secondary.
	//
	// The component defaults it to 'primary'.
	Variant string

	// Label is accessible name for the tablist.
	//
	// The component defaults it to ''.
	Label string
}

// Tabs renders <ui-tabs>.
//
// <ui-tabs> — Material tabs: a tab bar with an animated active indicator.
//
// <ui-tabs value="one" label="Demo tabs" @change=${(e) => ...}>
// <ui-tab value="one" icon="home">One</ui-tab>
// <ui-tab value="two">Two</ui-tab>
// <ui-tab-panel slot="panels" value="one">…</ui-tab-panel>
// <ui-tab-panel slot="panels" value="two">…</ui-tab-panel>
// </ui-tabs>
//
// Tabs go in the default slot, panels in the "panels" slot. The parent
// reflects `selected` onto each <ui-tab> and `active` onto each
// <ui-tab-panel>, and wires aria-controls/aria-labelledby ids between them.
// Activation is AUTOMATIC per the ARIA APG: arrow keys move focus AND select
// (one Tab stop for the whole bar via roving tabindex).
func Tabs(p TabsProps) *alacris.Element {
	e := alacris.E(TabsTag)
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Variant != "" && p.Variant != "primary" {
		e.Prop("variant", p.Variant)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// TabsHandle patches a rendered <ui-tabs> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with TabsElement.
type TabsHandle struct {
	handle live.Handle
}

// TabsElement addresses the <ui-tabs> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	TabsElement(c.Session, "id").SetValue(v)
func TabsElement(s *live.Session, id string) TabsHandle {
	return TabsHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h TabsHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h TabsHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetVariant writes the variant prop.
func (h TabsHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetLabel writes the label prop.
func (h TabsHandle) SetLabel(v string) { h.handle.Set("label", v) }
