// Code generated by alacris-go from ../assets/ui/components/ui-table.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// TableTag is the name of the <ui-table> custom element.
const TableTag = "ui-table"

// Slots exposed by <ui-table>. Put one on your own markup to fill it:
//
//	<h3 slot={ TableSlotDefault }>
const (
	// native <table> (markup mode)
	TableSlotDefault = ""
	// replaces the default <ui-table-toolbar>
	TableSlotToolbar = "toolbar"
	// projected into the default toolbar
	TableSlotHeadline = "headline"
	// projected into the default toolbar
	TableSlotSupporting = "supporting"
	// projected into the default toolbar
	TableSlotActions = "actions"
	// replaces the default <ui-table-footer>
	TableSlotFooter = "footer"
	TableSlotEmpty  = "empty"
)

// Events emitted by <ui-table>. Forward one to a server action with On:
//
//	Table(props).On(TableEventChange, "handler-name")
const (
	// selection; detail: { selected }
	TableEventChange = "change"
	// detail: { key, dir }
	TableEventSort = "sort"
	// detail: { page, pageSize }
	TableEventPage = "page"
	// detail: { value }
	TableEventFilter = "filter"
	// detail: { density }
	TableEventDensity = "density"
	// detail: { hidden }
	TableEventColumnVisibility = "column-visibility"
	// a group was toggled; detail: { key, expanded, expandedGroups }
	TableEventGroup = "group"
	// detail: { id, row }
	TableEventRowClick = "row-click"
	// CSV produced; detail: { format, filename }
	TableEventExport = "export"
)

// TableChangeDetail is the detail of the "change" event of <ui-table>.
//
// selection; detail: { selected }
type TableChangeDetail struct {
	Selected any `json:"selected"`
}

// TableSortDetail is the detail of the "sort" event of <ui-table>.
//
// detail: { key, dir }
type TableSortDetail struct {
	Key any `json:"key"`
	Dir any `json:"dir"`
}

// TablePageDetail is the detail of the "page" event of <ui-table>.
//
// detail: { page, pageSize }
type TablePageDetail struct {
	Page     any `json:"page"`
	Pagesize any `json:"pagesize"`
}

// TableFilterDetail is the detail of the "filter" event of <ui-table>.
//
// detail: { value }
type TableFilterDetail struct {
	Value any `json:"value"`
}

// TableDensityDetail is the detail of the "density" event of <ui-table>.
//
// detail: { density }
type TableDensityDetail struct {
	Density any `json:"density"`
}

// TableColumnVisibilityDetail is the detail of the "column-visibility" event of <ui-table>.
//
// detail: { hidden }
type TableColumnVisibilityDetail struct {
	Hidden any `json:"hidden"`
}

// TableGroupDetail is the detail of the "group" event of <ui-table>.
//
// a group was toggled; detail: { key, expanded, expandedGroups }
type TableGroupDetail struct {
	Key            any `json:"key"`
	Expanded       any `json:"expanded"`
	Expandedgroups any `json:"expandedgroups"`
}

// TableRowClickDetail is the detail of the "row-click" event of <ui-table>.
//
// detail: { id, row }
type TableRowClickDetail struct {
	ID  any `json:"id"`
	Row any `json:"row"`
}

// TableExportDetail is the detail of the "export" event of <ui-table>.
//
// CSV produced; detail: { format, filename }
type TableExportDetail struct {
	Format   any `json:"format"`
	Filename any `json:"filename"`
}

// TableVars is the theming contract of <ui-table>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	Table(props).Apply(TableVars, map[string]string{"--ui-table-row-height": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var TableVars = alacris.Vars(
	"--ui-table-row-height",
	"--ui-table-dense-row-height",
	"--ui-table-comfortable-row-height",
	"--ui-table-check-col",
	"--ui-table-border-color",
	"--ui-table-header-fg",
	"--ui-table-header-bg",
	"--ui-table-fg",
	"--ui-table-bg",
	"--ui-table-hover-bg",
	"--ui-table-selected-bg",
	"--ui-table-stripe-bg",
	"--ui-table-group-bg",
	"--ui-table-agg-fg",
	"--ui-table-radius",
)

// TableProps are the props of <ui-table>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type TableProps struct {
	// The component defaults it to ''.
	Label string

	// The component defaults it to ''.
	Headline string

	// The component defaults it to ''.
	Supporting string

	// Variant is outlined | standard.
	//
	// The component defaults it to 'outlined'.
	Variant string

	// Density is compact | standard | comfortable.
	//
	// The component defaults it to 'standard'.
	Density string

	// Dense is alias for density="compact".
	//
	// The component defaults it to false.
	Dense bool

	// The component defaults it to false.
	StickyHeader bool

	// The component defaults it to false.
	StickyFirst bool

	// The component defaults it to false.
	Striped bool

	// The component defaults it to false.
	Loading bool

	// The component defaults it to ''.
	MaxHeight string

	// Selectable is none | single | multiple.
	//
	// The component defaults it to 'none'.
	Selectable string

	// Crosses as JSON in the selected attribute.
	Selected []any

	// Crosses as JSON in the columns attribute.
	Columns []any

	// Crosses as JSON in the rows attribute.
	Rows []any

	// GetRowID is (row, index) => id.
	//
	// The component defaults it to null.
	//
	// Crosses as JSON in the get-row-id attribute.
	GetRowID map[string]any

	// The component defaults it to ''.
	SortBy string

	// SortDir is asc | desc.
	//
	// The component defaults it to 'asc'.
	SortDir string

	// SortMode is client | server.
	//
	// The component defaults it to 'client'.
	SortMode string

	// The component defaults it to ''.
	Filter string

	// GroupBy is column key to group rows.
	//
	// The component defaults it to ''.
	GroupBy string

	// ExpandedGroups is empty means all groups expanded.
	//
	// Crosses as JSON in the expanded-groups attribute.
	ExpandedGroups []any

	// Crosses as JSON in the hidden-columns attribute.
	HiddenColumns []any

	// The component defaults it to 1.
	Page float64

	// PageSize is 0 shows every row.
	//
	// The component defaults it to 0.
	PageSize float64

	// The component defaults it to 0.
	RowCount float64

	// PaginationMode is client | server.
	//
	// The component defaults it to 'client'.
	PaginationMode string

	// Crosses as JSON in the page-size-options attribute.
	PageSizeOptions []any

	// The component defaults it to false.
	QuickFilter bool

	// The component defaults it to false.
	ColumnMenu bool

	// The component defaults it to false.
	DensityMenu bool

	// The component defaults it to false.
	CsvExport bool

	// The component defaults it to 'table.csv'.
	CsvFileName string

	// The component defaults it to 'No results'.
	EmptyText string
}

// Table renders <ui-table>.
//
// <ui-table> — Material data-table / DataGrid.
//
// Markup mode — pass a native <table> (adopted into the shadow so cells can
// be themed). `data-sortable` / `data-numeric` decorate headers.
//
// <ui-table label="Nutrition">
// <table>…</table>
// </ui-table>
//
// Data mode — `columns` + `rows`. The grid is `role="table"` (Alacris cannot
// bind inside native <tr>). Pipeline (filter → sort → group → paginate →
// aggregate) lives in `util/table.js`. Chrome is <ui-table-toolbar> and
// <ui-table-footer>, composed from search, menus, checkboxes, and pagination.
//
// <ui-table headline="Trades" columns=${cols} rows=${rows}
// selectable="multiple" group-by="commodity"
// quick-filter column-menu density-menu csv-export
// page-size="10"></ui-table>
//
// Column objects: { key, label, numeric, sortable, width, hidden, align,
// aggregate: 'sum'|'avg'|'min'|'max'|'count', render(row, col), sortValue(row) }
func Table(p TableProps) *alacris.Element {
	e := alacris.E(TableTag)
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Headline != "" {
		e.Prop("headline", p.Headline)
	}
	if p.Supporting != "" {
		e.Prop("supporting", p.Supporting)
	}
	if p.Variant != "" && p.Variant != "outlined" {
		e.Prop("variant", p.Variant)
	}
	if p.Density != "" && p.Density != "standard" {
		e.Prop("density", p.Density)
	}
	if p.Dense {
		e.Prop("dense", p.Dense)
	}
	if p.StickyHeader {
		e.Prop("stickyHeader", p.StickyHeader)
	}
	if p.StickyFirst {
		e.Prop("stickyFirst", p.StickyFirst)
	}
	if p.Striped {
		e.Prop("striped", p.Striped)
	}
	if p.Loading {
		e.Prop("loading", p.Loading)
	}
	if p.MaxHeight != "" {
		e.Prop("maxHeight", p.MaxHeight)
	}
	if p.Selectable != "" && p.Selectable != "none" {
		e.Prop("selectable", p.Selectable)
	}
	if len(p.Selected) > 0 {
		e.Prop("selected", p.Selected)
	}
	if len(p.Columns) > 0 {
		e.Prop("columns", p.Columns)
	}
	if len(p.Rows) > 0 {
		e.Prop("rows", p.Rows)
	}
	if len(p.GetRowID) > 0 {
		e.Prop("getRowId", p.GetRowID)
	}
	if p.SortBy != "" {
		e.Prop("sortBy", p.SortBy)
	}
	if p.SortDir != "" && p.SortDir != "asc" {
		e.Prop("sortDir", p.SortDir)
	}
	if p.SortMode != "" && p.SortMode != "client" {
		e.Prop("sortMode", p.SortMode)
	}
	if p.Filter != "" {
		e.Prop("filter", p.Filter)
	}
	if p.GroupBy != "" {
		e.Prop("groupBy", p.GroupBy)
	}
	if len(p.ExpandedGroups) > 0 {
		e.Prop("expandedGroups", p.ExpandedGroups)
	}
	if len(p.HiddenColumns) > 0 {
		e.Prop("hiddenColumns", p.HiddenColumns)
	}
	if p.Page != 0 && p.Page != 1 {
		e.Prop("page", p.Page)
	}
	if p.PageSize != 0 {
		e.Prop("pageSize", p.PageSize)
	}
	if p.RowCount != 0 {
		e.Prop("rowCount", p.RowCount)
	}
	if p.PaginationMode != "" && p.PaginationMode != "client" {
		e.Prop("paginationMode", p.PaginationMode)
	}
	if len(p.PageSizeOptions) > 0 {
		e.Prop("pageSizeOptions", p.PageSizeOptions)
	}
	if p.QuickFilter {
		e.Prop("quickFilter", p.QuickFilter)
	}
	if p.ColumnMenu {
		e.Prop("columnMenu", p.ColumnMenu)
	}
	if p.DensityMenu {
		e.Prop("densityMenu", p.DensityMenu)
	}
	if p.CsvExport {
		e.Prop("csvExport", p.CsvExport)
	}
	if p.CsvFileName != "" && p.CsvFileName != "table.csv" {
		e.Prop("csvFileName", p.CsvFileName)
	}
	if p.EmptyText != "" && p.EmptyText != "No results" {
		e.Prop("emptyText", p.EmptyText)
	}
	return e
}

// TableHandle patches a rendered <ui-table> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with TableElement.
type TableHandle struct {
	handle live.Handle
}

// TableElement addresses the <ui-table> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	TableElement(c.Session, "id").SetLabel(v)
func TableElement(s *live.Session, id string) TableHandle {
	return TableHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h TableHandle) Handle() live.Handle { return h.handle }

// SetLabel writes the label prop.
func (h TableHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetHeadline writes the headline prop.
func (h TableHandle) SetHeadline(v string) { h.handle.Set("headline", v) }

// SetSupporting writes the supporting prop.
func (h TableHandle) SetSupporting(v string) { h.handle.Set("supporting", v) }

// SetVariant writes the variant prop.
func (h TableHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetDensity writes the density prop.
func (h TableHandle) SetDensity(v string) { h.handle.Set("density", v) }

// SetDense writes the dense prop.
func (h TableHandle) SetDense(v bool) { h.handle.Set("dense", v) }

// SetStickyHeader writes the stickyHeader prop.
func (h TableHandle) SetStickyHeader(v bool) { h.handle.Set("stickyHeader", v) }

// SetStickyFirst writes the stickyFirst prop.
func (h TableHandle) SetStickyFirst(v bool) { h.handle.Set("stickyFirst", v) }

// SetStriped writes the striped prop.
func (h TableHandle) SetStriped(v bool) { h.handle.Set("striped", v) }

// SetLoading writes the loading prop.
func (h TableHandle) SetLoading(v bool) { h.handle.Set("loading", v) }

// SetMaxHeight writes the maxHeight prop.
func (h TableHandle) SetMaxHeight(v string) { h.handle.Set("maxHeight", v) }

// SetSelectable writes the selectable prop.
func (h TableHandle) SetSelectable(v string) { h.handle.Set("selectable", v) }

// SetSelected writes the selected prop.
func (h TableHandle) SetSelected(v []any) { h.handle.Set("selected", v) }

// SetColumns writes the columns prop.
func (h TableHandle) SetColumns(v []any) { h.handle.Set("columns", v) }

// SetRows writes the rows prop.
func (h TableHandle) SetRows(v []any) { h.handle.Set("rows", v) }

// SetGetRowID writes the getRowId prop.
func (h TableHandle) SetGetRowID(v map[string]any) { h.handle.Set("getRowId", v) }

// SetSortBy writes the sortBy prop.
func (h TableHandle) SetSortBy(v string) { h.handle.Set("sortBy", v) }

// SetSortDir writes the sortDir prop.
func (h TableHandle) SetSortDir(v string) { h.handle.Set("sortDir", v) }

// SetSortMode writes the sortMode prop.
func (h TableHandle) SetSortMode(v string) { h.handle.Set("sortMode", v) }

// SetFilter writes the filter prop.
func (h TableHandle) SetFilter(v string) { h.handle.Set("filter", v) }

// SetGroupBy writes the groupBy prop.
func (h TableHandle) SetGroupBy(v string) { h.handle.Set("groupBy", v) }

// SetExpandedGroups writes the expandedGroups prop.
func (h TableHandle) SetExpandedGroups(v []any) { h.handle.Set("expandedGroups", v) }

// SetHiddenColumns writes the hiddenColumns prop.
func (h TableHandle) SetHiddenColumns(v []any) { h.handle.Set("hiddenColumns", v) }

// SetPage writes the page prop.
func (h TableHandle) SetPage(v float64) { h.handle.Set("page", v) }

// SetPageSize writes the pageSize prop.
func (h TableHandle) SetPageSize(v float64) { h.handle.Set("pageSize", v) }

// SetRowCount writes the rowCount prop.
func (h TableHandle) SetRowCount(v float64) { h.handle.Set("rowCount", v) }

// SetPaginationMode writes the paginationMode prop.
func (h TableHandle) SetPaginationMode(v string) { h.handle.Set("paginationMode", v) }

// SetPageSizeOptions writes the pageSizeOptions prop.
func (h TableHandle) SetPageSizeOptions(v []any) { h.handle.Set("pageSizeOptions", v) }

// SetQuickFilter writes the quickFilter prop.
func (h TableHandle) SetQuickFilter(v bool) { h.handle.Set("quickFilter", v) }

// SetColumnMenu writes the columnMenu prop.
func (h TableHandle) SetColumnMenu(v bool) { h.handle.Set("columnMenu", v) }

// SetDensityMenu writes the densityMenu prop.
func (h TableHandle) SetDensityMenu(v bool) { h.handle.Set("densityMenu", v) }

// SetCsvExport writes the csvExport prop.
func (h TableHandle) SetCsvExport(v bool) { h.handle.Set("csvExport", v) }

// SetCsvFileName writes the csvFileName prop.
func (h TableHandle) SetCsvFileName(v string) { h.handle.Set("csvFileName", v) }

// SetEmptyText writes the emptyText prop.
func (h TableHandle) SetEmptyText(v string) { h.handle.Set("emptyText", v) }
