// Code generated by alacris-go from ../assets/ui/components/ui-text-field.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// TextFieldTag is the name of the <ui-text-field> custom element.
const TextFieldTag = "ui-text-field"

// Slots exposed by <ui-text-field>. Put one on your own markup to fill it:
//
//	<h3 slot={ TextFieldSlotLeading }>
const (
	// icon before the input
	TextFieldSlotLeading = "leading"
	// icon after the input (replaced by ✕ while clearable+content)
	TextFieldSlotTrailing = "trailing"
)

// Events emitted by <ui-text-field>. Forward one to a server action with On:
//
//	TextField(props).On(TextFieldEventInput, "handler-name")
const (
	// every keystroke;   detail: { value }
	TextFieldEventInput = "input"
	// committed (blur/Enter); detail: { value }
	TextFieldEventChange = "change"
	// the clear affordance was used
	TextFieldEventClear = "clear"
)

// TextFieldInputDetail is the detail of the "input" event of <ui-text-field>.
//
// every keystroke;   detail: { value }
type TextFieldInputDetail struct {
	Value any `json:"value"`
}

// TextFieldChangeDetail is the detail of the "change" event of <ui-text-field>.
//
// committed (blur/Enter); detail: { value }
type TextFieldChangeDetail struct {
	Value any `json:"value"`
}

// TextFieldVars is the theming contract of <ui-text-field>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	TextField(props).Apply(TextFieldVars, map[string]string{"--ui-text-field-bg": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var TextFieldVars = alacris.Vars(
	"--ui-text-field-bg",
	"--ui-text-field-fg",
	"--ui-text-field-label-fg",
	"--ui-text-field-accent",
	"--ui-text-field-error-fg",
	"--ui-text-field-outline-color",
	"--ui-text-field-radius",
	"--ui-text-field-font",
	"--ui-text-field-height",
	"--ui-text-field-stepper-width",
)

// TextFieldProps are the props of <ui-text-field>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type TextFieldProps struct {
	// Variant is filled | outlined.
	//
	// The component defaults it to 'filled'.
	Variant string

	// The component defaults it to ''.
	Label string

	// The component defaults it to ''.
	Value string

	// Type is any native input type; 'textarea' renders one.
	//
	// The component defaults it to 'text'.
	Type string

	// The component defaults it to ''.
	Placeholder string

	// Helper is supporting text under the field.
	//
	// The component defaults it to ''.
	Helper string

	// Error is error message; non-empty switches to error state.
	//
	// The component defaults it to ''.
	Error string

	// The component defaults it to false.
	Disabled bool

	// The component defaults it to false.
	Required bool

	// Clearable is trailing ✕ while there is content.
	//
	// The component defaults it to false.
	Clearable bool

	// Name is form participation.
	//
	// The component defaults it to ''.
	Name string

	// Maxlength is >0 shows a character counter and enforces it.
	//
	// The component defaults it to 0.
	Maxlength float64

	// The component defaults it to 3.
	Rows float64

	// Autocomplete is absent unless set; 'off' keeps the browser's saved-value list out of a field whose contents are not a name, an address or a password.
	//
	// The component defaults it to ''.
	Autocomplete string

	// Autocapitalize is 'off' for anything case-sensitive.
	//
	// The component defaults it to ''.
	Autocapitalize string

	// Autocorrect is 'off' to stop substitutions.
	//
	// The component defaults it to ''.
	Autocorrect string

	// Spellcheck is 'false' for code and query syntax.
	//
	// The component defaults it to ''.
	Spellcheck string

	// The component defaults it to ''.
	Inputmode string

	// Enterkeyhint is textarea rows.
	//
	// The component defaults it to ''.
	Enterkeyhint string
}

// TextField renders <ui-text-field>.
//
// <ui-text-field> — Material text field, filled and outlined, floating label.
func TextField(p TextFieldProps) *alacris.Element {
	e := alacris.E(TextFieldTag)
	if p.Variant != "" && p.Variant != "filled" {
		e.Prop("variant", p.Variant)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	if p.Value != "" {
		e.Prop("value", p.Value)
	}
	if p.Type != "" && p.Type != "text" {
		e.Prop("type", p.Type)
	}
	if p.Placeholder != "" {
		e.Prop("placeholder", p.Placeholder)
	}
	if p.Helper != "" {
		e.Prop("helper", p.Helper)
	}
	if p.Error != "" {
		e.Prop("error", p.Error)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Required {
		e.Prop("required", p.Required)
	}
	if p.Clearable {
		e.Prop("clearable", p.Clearable)
	}
	if p.Name != "" {
		e.Prop("name", p.Name)
	}
	if p.Maxlength != 0 {
		e.Prop("maxlength", p.Maxlength)
	}
	if p.Rows != 0 && p.Rows != 3 {
		e.Prop("rows", p.Rows)
	}
	if p.Autocomplete != "" {
		e.Prop("autocomplete", p.Autocomplete)
	}
	if p.Autocapitalize != "" {
		e.Prop("autocapitalize", p.Autocapitalize)
	}
	if p.Autocorrect != "" {
		e.Prop("autocorrect", p.Autocorrect)
	}
	if p.Spellcheck != "" {
		e.Prop("spellcheck", p.Spellcheck)
	}
	if p.Inputmode != "" {
		e.Prop("inputmode", p.Inputmode)
	}
	if p.Enterkeyhint != "" {
		e.Prop("enterkeyhint", p.Enterkeyhint)
	}
	return e
}

// TextFieldHandle patches a rendered <ui-text-field> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with TextFieldElement.
type TextFieldHandle struct {
	handle live.Handle
}

// TextFieldElement addresses the <ui-text-field> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	TextFieldElement(c.Session, "id").SetVariant(v)
func TextFieldElement(s *live.Session, id string) TextFieldHandle {
	return TextFieldHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h TextFieldHandle) Handle() live.Handle { return h.handle }

// SetVariant writes the variant prop.
func (h TextFieldHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetLabel writes the label prop.
func (h TextFieldHandle) SetLabel(v string) { h.handle.Set("label", v) }

// SetValue writes the value prop.
func (h TextFieldHandle) SetValue(v string) { h.handle.Set("value", v) }

// SetType writes the type prop.
func (h TextFieldHandle) SetType(v string) { h.handle.Set("type", v) }

// SetPlaceholder writes the placeholder prop.
func (h TextFieldHandle) SetPlaceholder(v string) { h.handle.Set("placeholder", v) }

// SetHelper writes the helper prop.
func (h TextFieldHandle) SetHelper(v string) { h.handle.Set("helper", v) }

// SetError writes the error prop.
func (h TextFieldHandle) SetError(v string) { h.handle.Set("error", v) }

// SetDisabled writes the disabled prop.
func (h TextFieldHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetRequired writes the required prop.
func (h TextFieldHandle) SetRequired(v bool) { h.handle.Set("required", v) }

// SetClearable writes the clearable prop.
func (h TextFieldHandle) SetClearable(v bool) { h.handle.Set("clearable", v) }

// SetName writes the name prop.
func (h TextFieldHandle) SetName(v string) { h.handle.Set("name", v) }

// SetMaxlength writes the maxlength prop.
func (h TextFieldHandle) SetMaxlength(v float64) { h.handle.Set("maxlength", v) }

// SetRows writes the rows prop.
func (h TextFieldHandle) SetRows(v float64) { h.handle.Set("rows", v) }

// SetAutocomplete writes the autocomplete prop.
func (h TextFieldHandle) SetAutocomplete(v string) { h.handle.Set("autocomplete", v) }

// SetAutocapitalize writes the autocapitalize prop.
func (h TextFieldHandle) SetAutocapitalize(v string) { h.handle.Set("autocapitalize", v) }

// SetAutocorrect writes the autocorrect prop.
func (h TextFieldHandle) SetAutocorrect(v string) { h.handle.Set("autocorrect", v) }

// SetSpellcheck writes the spellcheck prop.
func (h TextFieldHandle) SetSpellcheck(v string) { h.handle.Set("spellcheck", v) }

// SetInputmode writes the inputmode prop.
func (h TextFieldHandle) SetInputmode(v string) { h.handle.Set("inputmode", v) }

// SetEnterkeyhint writes the enterkeyhint prop.
func (h TextFieldHandle) SetEnterkeyhint(v string) { h.handle.Set("enterkeyhint", v) }
