// Code generated by alacris-go from ../assets/ui/components/ui-text.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// TextTag is the name of the <ui-text> custom element.
const TextTag = "ui-text"

// Slots exposed by <ui-text>. Put one on your own markup to fill it:
//
//	<h3 slot={ TextSlotDefault }>
const (
	TextSlotDefault = ""
)

// TextProps are the props of <ui-text>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type TextProps struct {
	// Variant is any type role: display|headline|title|body|label × lg|md|sm.
	//
	// The component defaults it to 'body-md'.
	Variant string

	// Color is a color role name ('primary', 'onSurfaceVariant', …).
	//
	// The component defaults it to ''.
	Color string
}

// Text renders <ui-text>.
//
// <ui-text> — typography, the type scale as an element.
//
// <ui-text variant="headline-md" as="h2">Section</ui-text>
//
// Semantics: <ui-text> is styling only. Keep real headings in your markup
// (`<h2><ui-text variant="headline-md">…</ui-text></h2>`) or set an ARIA role
// on the host when the document outline needs one.
func Text(p TextProps) *alacris.Element {
	e := alacris.E(TextTag)
	if p.Variant != "" && p.Variant != "body-md" {
		e.Prop("variant", p.Variant)
	}
	if p.Color != "" {
		e.Prop("color", p.Color)
	}
	return e
}

// TextHandle patches a rendered <ui-text> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with TextElement.
type TextHandle struct {
	handle live.Handle
}

// TextElement addresses the <ui-text> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	TextElement(c.Session, "id").SetVariant(v)
func TextElement(s *live.Session, id string) TextHandle {
	return TextHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h TextHandle) Handle() live.Handle { return h.handle }

// SetVariant writes the variant prop.
func (h TextHandle) SetVariant(v string) { h.handle.Set("variant", v) }

// SetColor writes the color prop.
func (h TextHandle) SetColor(v string) { h.handle.Set("color", v) }
