// Code generated by alacris-go from ../assets/ui/components/ui-toggle-group.js. DO NOT EDIT.

package ui

import (
	alacris "github.com/bmartel/alacris-go"
	live "github.com/bmartel/alacris-go/live"
)

// ToggleGroupTag is the name of the <ui-toggle-group> custom element.
const ToggleGroupTag = "ui-toggle-group"

// Slots exposed by <ui-toggle-group>. Put one on your own markup to fill it:
//
//	<h3 slot={ ToggleGroupSlotDefault }>
const (
	// the <ui-toggle-button> children
	ToggleGroupSlotDefault = ""
)

// Events emitted by <ui-toggle-group>. Forward one to a server action with On:
//
//	ToggleGroup(props).On(ToggleGroupEventChange, "handler-name")
const (
	// selection changed; detail: { value } (string, or array when multi)
	ToggleGroupEventChange = "change"
)

// ToggleGroupChangeDetail is the detail of the "change" event of <ui-toggle-group>.
//
// selection changed; detail: { value } (string, or array when multi)
type ToggleGroupChangeDetail struct {
	Value any `json:"value"`
}

// ToggleGroupVars is the theming contract of <ui-toggle-group>: the custom properties it
// is styled through, and the only supported way to restyle it from outside its
// shadow root.
//
//	ToggleGroup(props).Apply(ToggleGroupVars, map[string]string{"--ui-toggle-group-radius": "#111"})
//
// Applying a property that is not in the contract is an error, so a rename in the
// component turns up here rather than as styling that silently stops working.
var ToggleGroupVars = alacris.Vars(
	"--ui-toggle-group-radius",
	"--ui-toggle-group-outline-color",
)

// ToggleGroupProps are the props of <ui-toggle-group>.
//
// A field left at its zero value, or set to the component's own default, is
// left off the element, so the component keeps its default. To send a zero
// value deliberately, set it with Prop on the returned element.
type ToggleGroupProps struct {
	// Value is selected value, or array when `multi`.
	//
	// The component defaults it to ''.
	Value any

	// Multi is multiple segments may be selected.
	//
	// The component defaults it to false.
	Multi bool

	// Disabled is disables every segment.
	//
	// The component defaults it to false.
	Disabled bool

	// Label is accessible name for the group.
	//
	// The component defaults it to ''.
	Label string
}

// ToggleGroup renders <ui-toggle-group>.
//
// <ui-toggle-group> — Material segmented buttons: an outlined container that
// owns the selection of its slotted <ui-toggle-button>s.
//
// <ui-toggle-group value=${align} @change=${(e) => align.set(e.detail.value)}>
// <ui-toggle-button value="left">Left</ui-toggle-button>
// <ui-toggle-button value="right">Right</ui-toggle-button>
// </ui-toggle-group>
//
// Single-select by default (`value` is the selected string, ” for none;
// pressing the selected segment deselects it). With `multi`, `value` is an
// array (a JSON array string works as an attribute). Buttons are natural tab
// stops — no roving tabindex, per the toolbar-of-toggle-buttons pattern.
func ToggleGroup(p ToggleGroupProps) *alacris.Element {
	e := alacris.E(ToggleGroupTag)
	if p.Value != nil {
		e.Prop("value", p.Value)
	}
	if p.Multi {
		e.Prop("multi", p.Multi)
	}
	if p.Disabled {
		e.Prop("disabled", p.Disabled)
	}
	if p.Label != "" {
		e.Prop("label", p.Label)
	}
	return e
}

// ToggleGroupHandle patches a rendered <ui-toggle-group> over a live session.
//
// Each setter writes one component prop — one property write, one DOM update on
// the page. Obtain one with ToggleGroupElement.
type ToggleGroupHandle struct {
	handle live.Handle
}

// ToggleGroupElement addresses the <ui-toggle-group> rendered with this id, for
// patching its props with compile-checked names instead of strings:
//
//	ToggleGroupElement(c.Session, "id").SetValue(v)
func ToggleGroupElement(s *live.Session, id string) ToggleGroupHandle {
	return ToggleGroupHandle{handle: s.Element(id)}
}

// Handle returns the untyped handle, for attributes, classes and slot HTML.
func (h ToggleGroupHandle) Handle() live.Handle { return h.handle }

// SetValue writes the value prop.
func (h ToggleGroupHandle) SetValue(v any) { h.handle.Set("value", v) }

// SetMulti writes the multi prop.
func (h ToggleGroupHandle) SetMulti(v bool) { h.handle.Set("multi", v) }

// SetDisabled writes the disabled prop.
func (h ToggleGroupHandle) SetDisabled(v bool) { h.handle.Set("disabled", v) }

// SetLabel writes the label prop.
func (h ToggleGroupHandle) SetLabel(v string) { h.handle.Set("label", v) }
